PaladinCloud/CE

- webapp/src/app/pacman-features/modules/compliance/card/card.component.html
- webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.html
- webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.ts
- webapp/src/app/pacman-features/secondary-components/aws-resource-details/aws-resource-details.component.html
- webapp/src/app/shared/data-table/data-table.component.html
- webapp/src/app/shared/data-table/data-table.component.ts
- webapp/src/app/shared/filter-dropdown/filter-dropdown.component.html
- webapp/src/app/shared/filter-dropdown/filter-dropdown.component.ts
- webapp/src/app/shared/title-burger-head/title-burger-head.component.html
- webapp/src/app/shared/title-burger-head/title-burger-head.component.ts
- webapp/src/config/static-content.ts
1. Added loader to dashboard cards and filter
2. Renamed column from Policy Name to Rule Name in policy violations table header
3. Changed home screen sub heading and product brief.
Fixed image for all-clouds asset group selection in asset summary page.
> fix: text in homescreen, loader, all-cloud img

- installer/resources/pacbot_app/files/DB.sql
… 
fix: changed the length of the policyId of cf_policy table similar to cf_ruleInstance table
> fix: changed the length of the policyId of cf_policy table similar to cf_ruleInstance table

- webapp/package.json
The latest version of @types/geojson is causing the UI build failure. Adding a previous version to avoid failure.
failing UI build
The build is passing with this change.
> hotfix: Fixed UI build failure

- .github/workflows/codeQl.yaml
codeql is static code analysis by github
> Codeql setup

- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/file/FileManager.java
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/util/InventoryUtil.java
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/vo/ASGLaunchConfigVH.java
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/vo/ASGVH.java
Added AWS ASG LaunchConfiguration sub type to AWS ASG
.
> Modified existing AWS ASG to collect AWS ASG LaunchConfiguration data.

- CONTRIBUTING.md
- README.md
- code_of_conduct.md
- installer/README.md
Main readme and installation readme updated.
The contribution file is added.
Readme update
> chore: Update readme

- CONTRIBUTING.md
- README.md
Updated CONTRIBUTING.md
doc change
> docs: updated CONTRIBUTING.md

- installer/provison.sh
Updated provision.sh comments.
> Added Amazon linux on the top of commands list

- webapp/src/app/pacman-features/modules/compliance/horizontal-bar-chart/horizontal-bar-chart.component.ts
- webapp/src/app/pacman-features/secondary-components/aws-resource-details/aws-resource-details.component.css
- webapp/src/app/pacman-features/secondary-components/aws-resource-details/aws-resource-details.component.html
- webapp/src/app/pacman-features/secondary-components/compliance-overview-trend/compliance-overview-trend.component.ts
- webapp/src/app/pacman-features/secondary-components/issues-trend-history/issues-trend-history.component.ts
- webapp/src/app/pacman-features/secondary-components/policy-assets-trend/policy-assets-trend.component.ts
- webapp/src/app/pacman-features/secondary-components/policy-trend/policy-trend.component.ts
- webapp/src/app/pacman-features/secondary-components/tagging-assets-trend/tagging-assets-trend.component.ts
- webapp/src/app/pacman-features/secondary-components/tagging-compliance-trend/tagging-compliance-trend.component.ts
- webapp/src/app/pacman-features/secondary-components/tagging-trend/tagging-trend.component.ts
- webapp/src/app/shared/empty-state/empty-state.component.css
- webapp/src/app/shared/filter-dropdown/filter-dropdown.component.css
Fixed minor bugs related to rendering of graphs and loader.
> fix: fixed bugs related to graph, loader, empty-state

- webapp/pom.xml
- webapp/src/app/core/services/auth.service.ts
Fixed Session Timeout Issue
Downgraded npm version to 7.24.0
> fix(): Fixed session-timeout issue and docker build fail issue

- webapp/src/config/configurations.ts
Modified domains in configurations.ts file
> chore:modified domains in config file

- installer/resources/lambda_rule_engine/function.py
- installer/resources/lambda_submit/function.py
- webapp/src/config/configurations.ts
updated lambda runtime Python 3.6 to Python 3.8 
> Lambdaruntime

- installer/resources/pacbot_app/files/DB.sql
fix:removed extra quote in db.sql file
> fix:removed mismatched quote in db.sql file

- installer/core/terraform/resources/aws/load_balancer.py
- installer/resources/pacbot_app/alb_https_listener.py
- installer/resources/pacbot_app/alb_listener_rules.py
changed loadbalancer listener's deprecated changes to latest changes  
its an intermediate branch for terraform upgrade to latest version
> upgraded terraform to 0.14 version

- installer/resources/pacbot_app/files/DB.sql
Fix for updating the target type display name
> fix:fixing the target type table display name update

- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/KmsKeyInventoryCollector.java
- Corrected the import for gcpCredentialProvider in KMS collector
> fix: GCP discovery issue

- jobs/job-scheduler/src/main/java/com/paladincloud/jobscheduler/service/JobScheduler.java
Changed the code to run the rules for aws, azure and gcp in parallel instead of sequential. So that all the rule running can be completed in 20 mins as before.
> fix: running the three cloud rules in parallel, instead of sequentially

- installer/settings/common.py
updated common.py file with default AUTHENTICATION_TYPE
tested in redeploy
> common.py update

- installer/settings/common.py
updated common.py file with default AUTHENTICATION_TYPE
> updated common.py file with default AUTHENTICATION_TYPE

- installer/resources/lambda_submit/function.py
- installer/resources/pacbot_app/utils.py
- installer/settings/default.local.py
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/InventoryFetchOrchestrator.java
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/dao/RDSDBManager.java
- added support for multiple aws account name
- added recording the aws accounts in table for auditing
> fix:Support for multiple aws account names

- installer/core/mixins.py
- installer/resources/datastore/db.py
- installer/resources/pacbot_app/alb.py
- installer/settings/default.local.py
changes in displaying output while install/status command
1. changed pacbot url to paladincloud url
2. added db username and db password
> changes in displaying output

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/BatchAccountInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/FunctionAppInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/LoadBalancerInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/NetworkInterfaceInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/PostgreSQLInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/PublicIpAddressInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/RedisCacheInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/ResourceGroupInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/SQLDatabaseInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/SQLServerInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/StorageAccountInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/VaultInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/WebAppInventoryCollector.java
- jobs/gcp-discovery/pom.xml
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/GCPFetchOrchestrator.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/auth/GCPCredentialsProvider.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/BigQueryInventoryCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/CloudDNSInventoryCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/CloudSqlInventoryCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/DataProcInventoryCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/FirewallInventoryCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/GKEClusterInventoryCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/KmsKeyInventoryCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/NetworkInventoryCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/PubSubInventoryCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/StorageCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/VMInventoryCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/file/AssetFileGenerator.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/vo/GCPVH.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/vo/ProjectVH.java
Fix for missing account name and region for Azure and GCP
- Added project name and corrected projectId for GCP collected files
- Corrected region for Azure collected files
> fix:Fixed accountname and region for Azure and GCP

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetServiceImpl.java
- webapp/src/app/core/services/request-interceptor.service.ts
Replaced RefreshToken with user/refresh
Modified the Asset Details Resources attribute list
> fix: Fixed Refresh Token Expiry and Display EC2 Resources Attributes

- README.md
- installer/README.md
> docs: updated reademe

- .github/workflows/SonarCodeAnalysis.yaml
updated sonar cloud with pull requests and decorate 
> chore: sonarcloud update

- .github/workflows/SonarCodeAnalysis.yaml
fixed the issues for push build fail
> chore:update sonorcloud

- installer/resources/pacbot_app/files/DB_Azure_AD.sql
Fix: Removed Duplicate client id from db
> fix: remove duplicate client id records

- api/pacman-api-admin/pom.xml
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/config/PacmanConfiguration.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/domain/AWSProperty.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/domain/AzureProperty.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/domain/Bus.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/domain/Eventbridge.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/domain/GcpProperty.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/RuleServiceImpl.java
- api/pacman-api-admin/src/main/resources/bootstrap.yml
- api/pacman-api-admin/src/test/java/com/tmobile/pacman/api/admin/repository/service/JobExecutionManagerServiceImplTest.java
- api/pacman-api-admin/src/test/java/com/tmobile/pacman/api/admin/repository/service/RuleServiceImplTest.java
- Updated pom dependency for aws events
- Fixed admin update rule API to look on the custom event bus instead of default event bus
> Fix for rule enable-disable issue

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/ComplianceServiceImpl.java
Added debug logs for broken screen violations by severity 
> Added debug logs

- .github/workflows/SonarCodeAnalysis.yaml
changed workflow name and sonar cloud analysis for the push.
> chore:changed workflow name and sonarcloud anaylsis for push

- .github/workflows/SonarCodeAnalysis.yaml
> changed workflow name

- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.html
- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.spec.ts
- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.ts
Added test cases for compliance dashboard component
> test: added missing tests for compliance dashboard

- webapp/src/app/pacman-features/modules/compliance/card/card.component.html
- webapp/src/app/pacman-features/modules/compliance/card/card.component.ts
1. Fixed data load issue in dashboard
2. Fixed console log errors in dashboard
> fix: fixed data load issue in dashboard - follow up of api calls fix

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/controller/AssetTrendController.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepository.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepositoryImpl.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetService.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetServiceImpl.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/AssetGroupStatsCollector.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/es/ESManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/util/AssetGroupUtil.java
- Modified shipper job to collect the data for total asset count.
- Added new API endpoint to fetch the trends data for asset count.
> feat: Added new API to get the trend of daily assets count

- api/pacman-api-statistics/src/main/java/com/tmobile/pacman/api/statistics/repository/StatisticsRepository.java
- api/pacman-api-statistics/src/main/java/com/tmobile/pacman/api/statistics/repository/StatisticsRepositoryImpl.java
- api/pacman-api-statistics/src/main/java/com/tmobile/pacman/api/statistics/service/StatisticsServiceImpl.java
- Corrected statistics API to fetch total accounts from AWS, GCP and Azure
> fix: Corrected number of account in statistic API

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/controller/FilterController.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/FilterRepository.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/FilterRepositoryImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/FilterService.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/FilterServiceImpl.java
- webapp/src/app/pacman-features/modules/admin/rules/rules.component.ts
Added severity and Category filter APIs
Fixed options in rules dropdown 
> feat: Added APIs to fetch data for severity and category filters

- installer/core/terraform/resources/aws/elasticsearch.py
- installer/resources/datastore/es.py
- installer/settings/default.local.py
elastic search added extra node and enabled master node
> chore:elasticsearch adding extra node and enabled master node

- installer/resources/pacbot_app/alb_https_listener.py
enabled Vulnerability for VulnerabilityALBHttpsListenerRule
> enabled Vulnerability for VulnerabilityALBHttpsListenerRule

- webapp/src/app/core/core.module.ts
- webapp/src/app/core/services/window-expansion.service.ts
- webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.css
- webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.html
- webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.spec.ts
- webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.ts
- webapp/src/app/post-login-app/post-login-app.component.ts
- webapp/src/app/shared/dropdown/dropdown.component.ts
- webapp/src/app/shared/table/table.component.css
- webapp/src/app/shared/table/table.component.html
- webapp/src/app/shared/table/table.component.ts
1. Added column selector
2. Modified filters container
3. Made table dynamically adjustable with screen size
4. Added infinite scroll to the table
> feat: replaced violations table with new table

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/SubscriptionInventoryCollector.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/azurerules/StorageAccount/CMKEncryptionForStorageAccountActivityLogRule.java
> fix:Collector and rule.

- api/pacman-api-statistics/src/main/java/com/tmobile/pacman/api/statistics/repository/StatisticsRepositoryImpl.java
- api/pacman-api-statistics/src/main/java/com/tmobile/pacman/api/statistics/service/StatisticsServiceImpl.java
- Corrected number of gcp and azure accounts in statistics API.
> fix: Correcting count of accounts in statistics API

- installer/core/terraform/resources/aws/cloudwatch.py
- installer/resources/lambda_rule_engine/function.py
- installer/resources/lambda_rule_engine/utils.py
- installer/resources/lambda_submit/function.py
Fix for disabling qualys collectors and rule in case qualys is disabled from installer.
> Fix: Disabling qualys collector and rules when its disabled from installer

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/AssetConstants.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/controller/AssetCountController.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepository.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepositoryImpl.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetService.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetServiceImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/controller/ComplianceController.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepository.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/ComplianceService.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/ComplianceServiceImpl.java
- api/pacman-api-compliance/src/test/java/com/tmobile/pacman/api/compliance/controller/ComplianceControllerTest.java
- api/pacman-api-compliance/src/test/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImplTest.java
- api/pacman-api-compliance/src/test/java/com/tmobile/pacman/api/compliance/service/ComplianceServiceImplTest.java
- webapp/src/app/pacman-features/modules/compliance/issue-details/issue-details.component.ts
Added an API to fetch exempted assets count
Modified an API to add and revoke exemption to all asset Groups
> feat: added exempted assets count Api

- webapp/src/app/pacman-features/modules/admin/asset-groups/create-asset-groups/create-asset-groups.component.html
- webapp/src/app/pacman-features/modules/admin/asset-groups/create-asset-groups/create-asset-groups.component.ts
Fixed Dropdown issue for Attribute values in create Asset Group component.
> fix: fixed dropdown bug in create asset group page

- webapp/src/app/pacman-features/modules/admin/asset-groups/create-asset-groups/create-asset-groups.component.html
- webapp/src/app/pacman-features/modules/admin/asset-groups/create-asset-groups/create-asset-groups.component.ts
Fixed Dropdown issue for Attribute values in create Asset Group component.
> fix: fixed attribute value fix in create asset group page

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/controller/ComplianceController.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepository.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/ComplianceService.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/ComplianceServiceImpl.java
- api/pacman-api-compliance/src/test/java/com/tmobile/pacman/api/compliance/controller/ComplianceControllerTest.java
1. Added an API to get distribution of asset count, policy count and average age by severity.
> feat: added api for distribution by severity

- webapp/src/app/core/core.module.ts
- webapp/src/app/core/services/table-state.service.ts
- webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.html
- webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.ts
- webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase/policy-knowledgebase.component.html
- webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase/policy-knowledgebase.component.ts
- webapp/src/app/pacman-features/secondary-components/pacman-policy-violations/pacman-policy-violations.component.ts
- webapp/src/app/shared/table/table.component.html
- webapp/src/app/shared/table/table.component.ts
Fixed list state which now tracks the rows fetched and position of scrollbar in table.
Violations screen
Policy screen
> fix: list state

- installer/settings/default.local.py
updated default values for elastic search
> updated default values for es

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
- webapp/src/app/pacman-features/modules/compliance/cloud-notifications/cloud-notifications.component.ts
- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.ts
- webapp/src/app/pacman-features/modules/compliance/event-details/event-details.component.html
- webapp/src/app/pacman-features/modules/compliance/event-details/event-details.component.ts
- webapp/src/app/pacman-features/modules/compliance/issue-details/issue-details.component.css
- webapp/src/app/pacman-features/modules/compliance/issue-details/issue-details.component.ts
- webapp/src/app/pacman-features/secondary-components/all-policy-violations/all-policy-violations.component.ts
- webapp/src/app/pacman-features/secondary-components/autofix-schedule/autofix-schedule.component.html
- webapp/src/app/pacman-features/secondary-components/autofix-schedule/autofix-schedule.component.ts
- webapp/src/app/pacman-features/services/issue-audit.service.ts
- webapp/src/app/shared/services/utils.service.ts
Modified date formats in all the screens
> fix:modified date formats

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/controller/ComplianceController.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/domain/IssueAuditLogRequest.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepository.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/ComplianceService.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/ComplianceServiceImpl.java
- api/pacman-api-compliance/src/test/java/com/tmobile/pacman/api/compliance/controller/ComplianceControllerTest.java
- api/pacman-api-compliance/src/test/java/com/tmobile/pacman/api/compliance/service/ComplianceServiceImplTest.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/repo/ElasticSearchRepository.java
fix  for Audit log api :
added datasource params Issue Audit log api
> fix : fix for audit log api

- installer/resources/pacbot_app/alb.py
- installer/resources/pacbot_app/alb_listener_rules.py
- installer/resources/vpc/security_group.py
> Revert "chore/external_alb_need_https"

- installer/settings/common.py
> chore: updated version

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/constants/PacmanRuleConstants.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/cloudstorage/AutomatedBackupCloudSQLRule.java
Added the correct elastic search index .
> fix:Automated backups for cloudsql

- webapp/src/app/pacman-features/modules/compliance/issue-details/issue-details.component.ts
- webapp/src/app/shared/services/utils.service.ts
Added asset groups in query params for Exception and Audit API's
Modified Date format
> fix: added asset groups in query params for Exception and Audit API's

- webapp/src/app/pacman-features/modules/compliance/issue-details/issue-details.component.ts
- webapp/src/app/shared/services/utils.service.ts
Added asset group for exception and audit Api's
> fix: added asset group for exception and audit

- installer/resources/pacbot_app/files/DB.sql
Corrected the metadata for asset group target details for ecs.
> Fix: Asset group update failure

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/utils/CommonUtils.java
fix for adding and revoking exception records to audit log
fix for adding and revoking exception records to audit log
> Fix/audit log issue v1.5.0

- installer/resources/pacbot_app/files/DB.sql
> updated sql query to disable unused target type

- installer/resources/lambda_rule_engine/function.py
updated environmental variable CONFIG_URL to rule engine  
> added config_url to rule_engine rules

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/azurerules/DiskRule/CMKEncryptionForOsAndDataDiskRule.java
> fix:Os and Data disk are encypted using customer managed keys.

- webapp/src/app/pacman-features/modules/assets/asset-dashboard/asset-dashboard.component.ts
- webapp/src/app/pacman-features/modules/compliance/issue-details/issue-details.component.ts
- webapp/src/app/pacman-features/secondary-components/policy-violation-desc/policy-violation-desc.component.html
Fixed Audit Log Issue and Exempted Asset count bug
> fixed audit log bug

- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.ts
- webapp/src/app/shared/table/table.component.html
- webapp/src/assets/icons/violations-low-icon.svg
1. Added violations column in compliance overview table in dashboard
Dashboard
> chore: added violations column in compliance overview table in dashboard

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/federated/RootAccountHardwareMFACheck.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/federated/RootAccountHardwareMFACheckTest.java
This fix is for checking Hardware MFA device is not configured for root account 
> fix:Root account hardware MFA check

- webapp/src/app/pacman-features/modules/assets/asset-dashboard/asset-dashboard.component.ts
- webapp/src/app/pacman-features/modules/assets/asset-distribution/asset-distribution.component.ts
- webapp/src/app/pacman-features/modules/assets/asset-list/asset-list.component.css
- webapp/src/app/pacman-features/modules/assets/asset-list/asset-list.component.html
- webapp/src/app/pacman-features/modules/assets/asset-list/asset-list.component.ts
- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.ts
- webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.ts
- webapp/src/app/post-login-app/asset-groups/asset-groups.component.ts
- webapp/src/app/shared/multiline-zoom-graph/multiline-zoom-graph.component.ts
- webapp/src/app/shared/table/table.component.html
- webapp/src/app/shared/table/table.component.ts
Replaced asset details table with new table.
Asset Details
> feat: Replaced asset details table

- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/file/FileManager.java
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/util/InventoryUtil.java
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/vo/CloudTrailEventSelectorVH.java
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/vo/CloudTrailVH.java
> feat: added event selector object to cloud trail data collector

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/Constants.java
- webapp/src/app/pacman-features/secondary-components/policy-violation-desc/policy-violation-desc.component.ts
Fixed broken link for arn resource Ids in Violation List Page.
Fixed broken link for arn resource Ids in Violation Details Page to fetch Asset List Details.
> fix: fixed violation details, asset list page bugs for arn resource Id

- webapp/src/app/pacman-features/modules/admin/asset-groups/asset-groups.component.ts
- webapp/src/app/pacman-features/modules/admin/asset-groups/create-asset-groups/create-asset-groups.component.ts
- webapp/src/app/pacman-features/modules/admin/asset-groups/delete-asset-groups/delete-asset-groups.component.ts
- webapp/src/app/pacman-features/modules/admin/asset-groups/domains/create-update-domain/create-update-domain.component.ts
- webapp/src/app/pacman-features/modules/admin/asset-groups/domains/domains.component.ts
- webapp/src/app/pacman-features/modules/admin/asset-groups/target-types/create-update-target-types/create-update-target-types.component.ts
- webapp/src/app/pacman-features/modules/admin/asset-groups/target-types/target-types.component.ts
- webapp/src/app/pacman-features/modules/admin/create-edit-policy/create-edit-policy.component.ts
- webapp/src/app/pacman-features/modules/admin/create-rule/create-rule.component.ts
- webapp/src/app/pacman-features/modules/admin/job-execution-manager/create-job-execution-manager/create-job-execution-manager.component.ts
- webapp/src/app/pacman-features/modules/admin/job-execution-manager/job-execution-manager.component.ts
- webapp/src/app/pacman-features/modules/admin/job-execution-manager/update-job-execution-manager/update-job-execution-manager.component.ts
- webapp/src/app/pacman-features/modules/admin/policies/policies.component.ts
- webapp/src/app/pacman-features/modules/admin/roles-allocation/roles-allocation.component.ts
- webapp/src/app/pacman-features/modules/admin/roles/create-update-roles/create-update-roles.component.ts
- webapp/src/app/pacman-features/modules/admin/roles/roles.component.ts
- webapp/src/app/pacman-features/modules/admin/rules/rules.component.ts
- webapp/src/app/pacman-features/modules/admin/sticky-exceptions/create-sticky-exceptions/create-sticky-exceptions.component.ts
- webapp/src/app/pacman-features/modules/admin/sticky-exceptions/delete-sticky-exceptions/delete-sticky-exceptions.component.ts
- webapp/src/app/pacman-features/modules/admin/sticky-exceptions/sticky-exceptions.component.ts
- webapp/src/app/pacman-features/modules/assets/asset-dashboard/asset-dashboard.component.html
- webapp/src/app/pacman-features/modules/assets/asset-dashboard/asset-dashboard.component.ts
- webapp/src/app/pacman-features/modules/assets/asset-distribution/asset-distribution.component.ts
- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.ts
- webapp/src/app/pacman-features/secondary-components/multiline-brush-zoom/multiline-brush-zoom.component.ts
- webapp/src/app/pacman-features/secondary-components/policy-violation-desc/policy-violation-desc.component.ts
- webapp/src/app/post-login-app/post-login-app.component.ts
- webapp/src/app/shared/multiline-zoom-graph/multiline-zoom-graph.component.ts
1. Fixed breadcrumbs in admin screens
2. Added breadcrumbs when navigating from asset summary or distribution to asset details.
3. Made asset trend graph y-axis dynamic with minimum data point value
> fix: fixed breadcrumbs in admin screens and fixed few p0 items

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
- webapp/src/app/pacman-features/modules/assets/asset-distribution/asset-distribution.component.css
- webapp/src/app/pacman-features/modules/assets/asset-distribution/asset-distribution.component.html
- webapp/src/app/pacman-features/modules/assets/asset-list/asset-list.component.ts
- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.spec.ts
- webapp/src/app/pacman-features/modules/compliance/issue-details/issue-details.component.html
- webapp/src/app/pacman-features/modules/compliance/issue-details/issue-details.component.ts
- webapp/src/app/pacman-features/secondary-components/policy-violation-desc/policy-violation-desc.component.html
- webapp/src/app/post-login-app/common/contextual-menu/contextual-menu.component.ts
Modified all Exceptions to Exemptions
Placed search bar in List view in Asset Distribution Screen
> fix: fixed few bugs related to Exemptions and Asset Distribution

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/VaultInventoryCollector.java
ix for azure keyvalut collector not collecting all keyvaults
> fix: fix for azure keyvalut collector not collecting all keyvaults

- installer/resources/pacbot_app/files/DB_Azure_AD.sql
> AzureAD mandatory properties name change in the DB

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/cloudwatchalarm/LogMetricFilterAndAlarmRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/iam/IAMRoleWithUnapprovedAccessRule.java
Fixed rules that were breaking policyViolationReason end point in compliance API
Compliance API
> fix: fixed rules that were breaking policyViolationReason end point in compliance api

- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/jobs/HostAssetDataImporter.java
- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/jobs/HostAssetsEsIndexer.java
Bug in the rules related to S3, S4 and S5 vulnerabilities reported by Qualys is fixed.
> fix: s3, s4, s5 qualys vulnerability rules fix

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/s3/S3ObjectLevelReadLoggingRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/s3/S3ObjectLevelWriteLoggingRule.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/s3/S3ObjectLevelLoggingRuleTest.java
This fix is for fixing an UI issue
these extra spaces were causing the UI/API to break
> fix: AWS Removed extra spaces

- emailTemplates/pacman-v2-email-template/html.handlebars
- webapp/src/app/pacman-features/modules/compliance/issue-details/issue-details.component.ts
> "feat: added ResourceID link and Policy link to the email template"

- webapp/src/app/pacman-features/modules/compliance/card/card.component.ts
- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.ts
- webapp/src/app/pacman-features/modules/compliance/policy-details/policy-details.component.html
- webapp/src/app/pacman-features/secondary-components/policy-summary/policy-summary.component.ts
- webapp/src/app/post-login-app/asset-groups/asset-groups.component.ts
- webapp/src/app/post-login-app/common/asset-switcher/asset-switcher.component.ts
- webapp/src/styles.css
1. Fixed violation tiles to display correct data when asset group is switched.
2. Fixed breadcrumb to show up when navigated to asset list from dashboard/policy compliance.
3. Fixed asset trend graph to show first tick value.
Dashboard violation tiles.
> fix: fixed violation tiles to display correct data when one of the tiles has 0 values.

- installer/resources/vpc/security_group.py
changed in bound rules in sg allowing 80 and 443 from outside and 3306 from cidr block
> chore ASG added inbound rule

- installer/resources/vpc/security_group.py
made changes in sg inbound rule (opened HTTP and HTTPS from outside word and rds within the cidr block) 
Fixes # (feature)
> chore/https sg chages 

- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/GKEClusterInventoryCollector.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/azurerules/AppService/CheckForTlsVersionRule.java
> fix: Added correct legacy Authorization enabled flag

- webapp/src/app/pacman-features/modules/assets/asset-distribution/asset-distribution.component.css
- webapp/src/app/pacman-features/modules/assets/asset-distribution/asset-distribution.component.html
- webapp/src/app/pacman-features/modules/assets/asset-distribution/asset-distribution.component.ts
Made asset distribution and coloring dynamic
> fix:dynamic distribution of assets

- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/GKEClusterInventoryCollector.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/azurerules/AppService/CheckForTlsVersionRule.java
> fix:Changed the minTlsVersion flag according to the collector

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/SQLServerInventoryCollector.java
Bug fix for Enforce configuration of Vulnerability Assessment (VA) setting 'Send scan reports to' for a SQL server
> fix: emails was not getting populated

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/ComplianceServiceImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/Constants.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/ResourceWithSeverityVulnerabilityRule.java
- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/jobs/HostAssetsEsIndexer.java
> fix:display qualys cve number and link in UI

- webapp/src/app/pacman-features/secondary-components/policy-violation-desc/policy-violation-desc.component.ts
> fix: qualys data

- installer/README.md
- installer/settings/common.py
Updated release number and readme
> chore: updated version number

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/cloudwatchalarm/LogMetricFilterAndAlarmRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/federated/CheckSecurityHubEnabledRule.java
This fix is for  AWS security hub and CloudWatch log metric filter and alarm rules
> fix:Policy AWS security hub and CloudWatch log metric filter and alarm rule

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/domain/Request.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/repo/ElasticSearchRepository.java
- webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.html
- webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.ts
- webapp/src/app/shared/table/table.component.ts
Added server side sorting for Violations
> feat: Added server side sorting

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/loadbalancer/EnableHttpsRule.java
Fixed typo in Enabled Https Load balancer rule.
> fix:Enable Https rule

- installer/resources/pacbot_app/ecs_services.py
> chore:ecs_service_tagging

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/BlobContainerInventoryCollector.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/azurerules/BlobContainer/BlobContainerImmutableRule.java
Bug fix for as blob collector was not collecting any data and violation was not being raised
> fix : null pointer exception for immutability policy and legal hold

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
1. Fixed add-revoke API failure which was causing for issueId "c127ab872a3af7c6b42019acdcad1abc". 
The API is fetching data related to autofix corresponding to the issue for which exemption is added/revoked.
> fix: fixed add-revoke API failure

- installer/resources/lambda_rule_engine/utils.py
- installer/settings/common.py
1. number of bucket configurable
> chore:batch size 

- installer/resources/lambda_rule_engine/utils.py
- installer/settings/common.py
> chore:batch_size_number

- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/LoadBalancerCollector.java
Resolving bad request error in load balancer collector for ssl policies
> fix : resolving bad request error

- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.ts
- webapp/src/app/shared/multiline-zoom-graph/multiline-zoom-graph.component.ts
1. Modified graph component to use linear scale with custom tick values on y-axis.
2. Modified issue-listing and asset-list filters function.
> fix: modified graph to use linear scale with custom values on y-axis

- installer/resources/pacbot_app/files/DB.sql
- Corrected asset API to fetch all details by default
> fix: Missing asset details

- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/APIKeysInventoryCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/CloudDNSInventoryCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/CloudSqlInventoryCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/DataProcInventoryCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/GKEClusterInventoryCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/IAMUserCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/KmsKeyInventoryCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/LoadBalancerCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/PubSubInventoryCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/StorageCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/VMInventoryCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/vo/CloudDNSVH.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/vo/CloudSqlVH.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/vo/ClusterVH.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/vo/GCPVH.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/vo/GKEClusterVH.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/vo/KMSKeyVH.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/vo/NodePoolVH.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/vo/SslPolicyVH.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/vo/StorageVH.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/vo/TopicVH.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/vo/VirtualMachineVH.java
changes for tags, region and fix duplicate entries which causes failure during shipper
> fix : set tags, resourceGroup name and subscription for gcp

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/BatchAccountInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/BlobContainerInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/BlobServiceInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/DatabricksInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/DiagnosticSettingsCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/FunctionAppInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/KubernetesServicesCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/MySQLFlexibleInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/NetworkInterfaceInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/PostgreSQLInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/RedisCacheInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/RouteTableInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/SQLServerInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/SecurityContactsCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/SubnetInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/Util.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/WebAppInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/vo/BlobServiceVH.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/vo/DatabricksVH.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/vo/FunctionAppVH.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/vo/KubernetesClustersVH.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/vo/MySQLFlexibleVH.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/vo/PostgreSQLServerVH.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/vo/RedisCacheVH.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/vo/WebAppVH.java
Reviewing azure collectors to ensure tags , resource Group Name and subscription is being collected
> fix : set tags, resourceGroup name and subscription for azure

- webapp/src/app/pacman-features/modules/admin/create-edit-policy/create-edit-policy.component.ts
- webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase-details/policy-knowledgebase-details.component.css
- webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase-details/policy-knowledgebase-details.component.html
- webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase-details/policy-knowledgebase-details.component.ts
- webapp/src/environments/environment.prod.ts
- webapp/src/environments/environment.stg.ts
- webapp/src/environments/environment.ts
Integrated Policy Details API
Added isAutofixEnabled property while creating or updating policies 
> fix: fixed policy details api issue and added isAutofixEnabled

- api/pacman-api-auth/src/main/java/com/tmobile/pacman/api/auth/services/CognitoAuthServiceImpl.java
- Added fix for login issue for multiple users for same email
> fix:Multiple users for same email

- installer/resources/pacbot_app/files/DB.sql
> chore:sql_fix

- installer/resources/pacbot_app/files/DB_Azure_AD.sql
Azure Ad redeploy is causing the issue while picking up the email claims. Fixed the same to pick the email claims correctly.
> fix: updated azure ad email id claim

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/s3/S3ObjectLevelReadLoggingRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/s3/S3ObjectLevelWriteLoggingRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/utils/PacmanUtils.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/utils/S3PacbotUtils.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/s3/S3ObjectLevelLoggingRuleTest.java
AWS rules related to s3 object level logging
> fix: aws rules related to s3 object level logging

- webapp/src/environments/environment.prod.ts
Fixing getPolicyById API failure
> fix: changed getPolicyId API endpoint

- webapp/src/environments/environment.prod.ts
Fixing getPolicyById API failure 
> fix: changed getPolicyById API endpoint

- installer/custom/commands/redeploy.py
- installer/resources/cognito/userpool.py
- installer/settings/default.local.py
> chore:Cognito_bug_fix

- installer/custom/commands/redeploy.py
- installer/resources/cognito/userpool.py
- installer/settings/default.local.py
> chore:Cognito_fix

- installer/resources/cognito/userpool.py
- installer/resources/pacbot_app/alb.py
Cognito Creation after es creation
> chore:Cognito_creation_after_ES_creation

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/controller/AssetController.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepository.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepositoryImpl.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetService.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetServiceImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/client/AssetServiceClient.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/controller/FilterController.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/domain/AssetApiData.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/FilterRepository.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/FilterRepositoryImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/FilterService.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/FilterServiceImpl.java
- installer/resources/pacbot_app/files/DB.sql
- Corrected the tags filter on asset and violation screen
> Fix-filter tags on asset and violation

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/controller/AssetController.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepository.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepositoryImpl.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetService.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetServiceImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/client/AssetServiceClient.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/controller/FilterController.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/domain/AssetApiData.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/FilterRepository.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/FilterRepositoryImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/FilterService.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/FilterServiceImpl.java
- installer/resources/pacbot_app/files/DB.sql
- corrected tagging filter for asset list API
- corrected tagging filter for violation API
> fix: Tagging filters on asset and violation

- installer/resources/cognito/userpool.py
- installer/settings/common.py
- installer/settings/default.local.py
> Chore/default local.py update

- installer/resources/cognito/userpool.py
- installer/settings/common.py
- installer/settings/default.local.py
> chore:default.local.py_update

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
- webapp/src/app/pacman-features/modules/admin/asset-groups/target-types/create-update-target-types/create-update-target-types.component.html
- webapp/src/app/pacman-features/modules/admin/job-execution-manager/create-job-execution-manager/create-job-execution-manager.component.html
- webapp/src/app/pacman-features/modules/admin/policies/policies.component.html
- webapp/src/app/pacman-features/modules/compliance/issue-details/issue-details.component.html
- webapp/src/app/pacman-features/secondary-components/multiline-brush-zoom/multiline-brush-zoom.component.css
- webapp/src/app/pacman-features/secondary-components/multiline-brush-zoom/multiline-brush-zoom.component.html
- webapp/src/app/pacman-features/secondary-components/policy-violation-desc/policy-violation-desc.component.html
- webapp/src/app/post-login-app/common/header/header.component.ts
- webapp/src/app/shared/multiline-zoom-graph/multiline-zoom-graph.component.ts
- webapp/src/app/shared/table/table.component.css
- webapp/src/app/shared/table/table.component.html
> fix: bug fixes

- webapp/src/app/shared/table/table.component.ts
> fix: fix sorting issue for column containing numbers

- webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.ts
> fixed sorting arrow in violations

- webapp/src/app/pacman-features/modules/assets/asset-list/asset-list.component.ts
- webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.ts
> fix: fixed filters for tags in violations and asset list

- webapp/src/app/pacman-features/modules/assets/asset-list/asset-list.component.ts
- webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.ts
- webapp/src/app/shared/table/table.component.ts
> Fix/bugs UI

- webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase-details/policy-knowledgebase-details.component.ts
- webapp/src/app/pacman-features/secondary-components/tagging-across-target-type/tagging-across-target-type.component.ts
- webapp/src/app/pacman-features/secondary-components/target-type-tagging-tile/target-type-tagging-tile.component.html
- webapp/src/app/pacman-features/secondary-components/total-tag-compliance/total-tag-compliance.component.ts
1. Fixed tagging across target type widget, breadcrumbs in tagging
2. Fixed severity and category data assignment in policy knowledgebase details screen.
> fix: fixed tagging across target type widget, breadcrumbs in tagging

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/AssetConstants.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/controller/AssetController.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepository.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepositoryImpl.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetService.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetServiceImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/client/AssetServiceClient.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/controller/FilterController.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/FilterRepository.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/FilterRepositoryImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/FilterService.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/FilterServiceImpl.java
- installer/resources/pacbot_app/files/DB.sql
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/MultiThreadedPolicyRunner.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/PolicyExecutor.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/PolicyRunner.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/SingleThreadPolicyRunner.java
- corrected category filter for violation API
- corrected tagging filter for violation API
- Tested locally with paladin UI
> fix: Filters on violation

- webapp/src/app/shared/table/table.component.ts
Fixed Account id sorting in asset list
> fix: fixed Account id sorting in asset list

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/AssetConstants.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/controller/AssetController.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepository.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepositoryImpl.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetService.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetServiceImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/client/AssetServiceClient.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/controller/FilterController.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/FilterRepository.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/FilterRepositoryImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/FilterService.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/FilterServiceImpl.java
- installer/resources/pacbot_app/files/DB.sql
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/MultiThreadedPolicyRunner.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/PolicyExecutor.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/PolicyRunner.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/SingleThreadPolicyRunner.java
- corrected category filter for violation API
- corrected tagging filter for violation API
> fix: Filters on asset and violation

- README.md
Received feedback that the readme was laborious to wade through due to a lack of paragraphs. 
Added paragraphs and cleaned up some of the wording for the readme.
> Readme more readable

- installer/resources/pacbot_app/files/DB_Policy.sql
Removing updated that are not required.
> bug:build db error resolution

- webapp/src/app/pacman-features/modules/admin/asset-groups/create-asset-groups/create-asset-groups.component.ts
- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.ts
- webapp/src/app/shared/table/table.component.ts
Removed compliance% and violation filters from dashboard list view
> fix: removed compliance% and violation filters from dashboard list view

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/domain/TargetTypesDetails.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AssetGroupServiceImpl.java
- webapp/src/app/pacman-features/modules/admin/asset-groups/create-asset-groups/create-asset-groups.component.ts
fixed create and update asset groups API
> fixed create and update asset groups API

- webapp/src/app/pacman-features/modules/admin/asset-groups/create-asset-groups/create-asset-groups.component.ts
> fix: create edit asset group

- api/pacman-api-admin/pom.xml
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/controller/UserManagementController.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/domain/CognitoUserDetails.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/domain/CreateCognitoUserDetails.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/model/CognitoUser.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/UserService.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/UserServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/service/AmazonCognitoConnector.java
1.GET-list of users and user roles from AWS Cognito userpool 
2.PUT-Edit status of user(Enable/Disable) and add/remove roles to user
3.POST-Create new user in userpool
4.DELETE-remove user from userpool
> feat:Added User_Management Api's

- webapp/package.json
- webapp/src/app/app.module.ts
- webapp/src/config/configurations.ts
Added option to use configurable Google Analytics in UI
> feat: google analytics

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/controller/ComplianceController.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepository.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/ComplianceService.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/ComplianceServiceImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/IssueTrendServiceImpl.java
- api/pacman-api-compliance/src/test/java/com/tmobile/pacman/api/compliance/controller/ComplianceControllerTest.java
- api/pacman-api-compliance/src/test/java/com/tmobile/pacman/api/compliance/controller/DownloadControllerTest.java
- api/pacman-api-compliance/src/test/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImplTest.java
- api/pacman-api-compliance/src/test/java/com/tmobile/pacman/api/compliance/service/ComplianceServiceImplTest.java
- api/pacman-api-compliance/src/test/java/com/tmobile/pacman/api/compliance/service/IssueTrendServiceImplTest.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/repo/ElasticSearchRepository.java
- webapp/src/app/pacman-features/modules/admin/asset-groups/create-asset-groups/create-asset-groups.component.ts
- webapp/src/app/pacman-features/modules/admin/create-edit-policy/create-edit-policy.component.css
- webapp/src/app/pacman-features/modules/assets/asset-distribution/asset-distribution.component.css
- webapp/src/app/pacman-features/modules/assets/asset-distribution/asset-distribution.component.html
- webapp/src/app/pacman-features/modules/assets/asset-distribution/asset-distribution.component.ts
Fixed server side sorting in Violations screen
Fixed few bugs in asset Distribution
> fixed server side sorting for violations list

- CONTRIBUTING.md
- code_of_conduct.md
- pull_request_template.md
Adding in an option for chore
removed some references to in product documentation and added a section for sharing doc updates that will go into the wiki
Our wiki should have a section on contribution that links to our different md files.
> chore:ContributionUpdates

- README.md
Bumping the release badge in the readme to 2.0
> Readme Version Bump

- webapp/src/app/pacman-features/modules/admin/policies/policies.component.ts
- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.html
- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.ts
- webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.ts
- webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase/policy-knowledgebase.component.html
- webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase/policy-knowledgebase.component.ts
- webapp/src/app/post-login-app/common/contextual-menu/contextual-menu.component.ts
- webapp/src/app/shared/multiline-zoom-graph/multiline-zoom-graph.component.ts
- webapp/src/app/shared/table/table.component.ts
> Fix v2/bugs UI

- commons/pac-batch-commons/pom.xml
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/database/RDSDBManager.java
- installer/resources/pacbot_app/files/DB.sql
- installer/resources/pacbot_app/import_db.py
- installer/settings/common.py
- installer/settings/default.local.py
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/AzureDiscoveryApplication.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/AzureFetchOrchestrator.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/GCPDiscoveryApplication.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/GCPFetchOrchestrator.java
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/InventoryFetchApplication.java
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/InventoryFetchOrchestrator.java
Taking accounts from sql database instead of rule params
> feat:removing accounts from rule params

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/controller/ComplianceController.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepository.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/ComplianceService.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/ComplianceServiceImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/IssueTrendServiceImpl.java
- api/pacman-api-compliance/src/test/java/com/tmobile/pacman/api/compliance/controller/ComplianceControllerTest.java
- api/pacman-api-compliance/src/test/java/com/tmobile/pacman/api/compliance/service/ComplianceServiceImplTest.java
- api/pacman-api-compliance/src/test/java/com/tmobile/pacman/api/compliance/service/IssueTrendServiceImplTest.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/PacmanSdkConstants.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/Main.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/dao/RDSDBManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/IssueCountManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/util/AssetGroupUtil.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/PolicyRunner.java
Populate violations count into table from shipper
> feat: update violation count from shipper

- installer/settings/common.py
> chore: updated release version

- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.ts
1. Fixed secondary sort in Dashboard
> fix: fixed secondary sort

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/FunctionAppInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/MySQLFlexibleInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/SecurityContactsCollector.java
Set subscription  id , so that counts of assets according to subscription ID is correct
> fix: set subscription id

- webapp/src/app/core/services/auth.service.ts
stores userInfo details which consist user roles after fetching new access token when session expires
> fix: adding userinfo after generating new access token

- installer/resources/pacbot_app/files/DB.sql
Rename ruleId to policyId and ruleName to policyName
> fix: rename columns from rule to policy

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepositoryImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/TaggingServiceImpl.java
> fix:Correctly mapped count value to its respective key

- installer/settings/common.py
> chore: updated release number

- webapp/src/app/core/services/auth.service.ts
> fix:cognito user info fix

- webapp/src/app/core/services/workflow.service.ts
- webapp/src/app/pacman-features/modules/compliance/issue-details/issue-details.component.ts
- webapp/src/app/pacman-features/secondary-components/all-policy-violations/all-policy-violations.component.ts
- webapp/src/app/pacman-features/secondary-components/policy-content-slider/policy-content-slider.component.ts
- webapp/src/app/shared/table/table.component.ts
1. Fixed  navigation bug in policy compliance screen
2. Fixed title and description bug in policy compliance screen
3. Fixed add exemption bug in issue details screen.
4. Fixed list view bug in Policy screen.
> fix: fixed policy compliance screen and policy knowledgebase ui bugs

- webapp/src/app/pacman-features/modules/admin/admin.module.ts
- webapp/src/app/pacman-features/modules/admin/create-edit-policy/create-edit-policy.component.css
- webapp/src/app/pacman-features/modules/admin/create-edit-policy/create-edit-policy.component.html
- webapp/src/app/pacman-features/modules/admin/create-edit-policy/create-edit-policy.component.ts
- webapp/src/app/pacman-features/modules/admin/policies/policies.component.ts
- webapp/src/app/shared/shared.module.ts
Removed steppers and developed as per new design
> refactored editpolicy screen

- installer/resources/pacbot_app/files/DB_Policy.sql
added elapsedtime column in policytable alter command.
> fix: elapsedtime column add in altertable

- webapp/src/app/pacman-features/modules/admin/create-edit-policy/create-edit-policy.component.css
- webapp/src/app/pacman-features/modules/admin/create-edit-policy/create-edit-policy.component.html
- webapp/src/app/pacman-features/modules/admin/create-edit-policy/create-edit-policy.component.ts
- webapp/src/app/pacman-features/modules/admin/policies/policies.component.ts
> fix: fixed edit policy and getting updated list on successful Update

- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/jobs/HostAssetsEsIndexer.java
-removed hard coded Qualys API URL
> fix: Corrected qualys KB API URL

- webapp/src/app/pacman-features/modules/admin/create-edit-policy/create-edit-policy.component.html
- webapp/src/app/pacman-features/modules/admin/create-edit-policy/create-edit-policy.component.ts
fixed multiple hits to update API
> fixed multiple hits to update API

- api/pacman-api-admin/pom.xml
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/domain/AccountList.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/domain/AccountValidationResponse.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AbstractAccountServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AccountsService.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AzureAccountServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/GcpAccountServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/QualysAccountServiceImpl.java
- Corrected get account list response
- Added validate for azure and qualys
- Modified delete account to effect immediately
- Enabling gcp and azure enabled flag from add account operation
> fix: Account management fixes

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/controller/UserManagementController.java
> fix:Removed default value of filter in UserManagement

- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/jobs/HostAssetsEsIndexer.java
Removed hard coded API base path
> fix: Qualys KB url

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/controller/AccountsController.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/GcpAccountServiceImpl.java
-Added API to get base account details
> fix: added API to get base account details

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/misc/ExternalVpcPeeringConnections.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/utils/PacmanUtils.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/misc/ExternalVpcPeeringConnectionsTest.java
Changes for external vpc policy bug
> fix - aws external vpc changes

- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/PacmanSdkConstants.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/dao/RDSDBManager.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/policy/Annotation.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/utils/Constants.java
- installer/resources/lambda_rule_engine/function.py
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/config/ConfigManager.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/PolicyExecutor.java
When search violation screen with "tag" or "assign" , the result says no data
In order to get results , we have added policy name to elastic search
> fix: insert policy name in elastic search

- jobs/gcp-discovery/pom.xml
- removed maven assembly plugin
> fix: GCP collector issue

- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/jobs/HostAssetDataImporter.java
- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/jobs/HostAssetsEsIndexer.java
- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/jobs/QualysDataImporter.java
- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/jobs/Util.java
- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/util/ElasticSearchManager.java
- removed API call to get vulnerability details
> fix: Qualys collector issue

- webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase/policy-knowledgebase.component.ts
Changed column header value from "Title" in webapp\src\app\pacman-features\modules\compliance\policy-knowledgebase\policy-knowledgebase.component.ts to "Policy"
> Issue#969 Changed column name from Title to Policy

- webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase-details/policy-knowledgebase-details.component.html
This PR is for the the isue #939. I have changed the text from Creation On to Date Created
Fixes # 939
> Rename Creation On to Date Created on policy details page

- webapp/src/app/pacman-features/modules/admin/policies/policies.component.ts
- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.ts
- webapp/src/app/pacman-features/modules/compliance/issue-details/issue-details.component.ts
- webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.ts
- webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase/policy-knowledgebase.component.ts
Rename the columns Title to Policy, Asset to Asset Type, and Cloud to Cloud Type.
Fixes #970 
3](https://user-images.githubusercontent.com/101788554/226360804-6c2a004a-d4d2-476d-8994-72b49ec28df8.png)
> Fix: Rename the columns

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/controller/NotificationsController.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/domain/NotificationPrefsRequest.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/service/NotificationSettings.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/service/NotificationSettingsImpl.java
- installer/resources/pacbot_app/files/DB_Cognito.sql
- installer/resources/pacbot_app/files/DB_Policy.sql
> feat: create apis for get and update notification preferences

- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/ec2/AmazonEC2ReservedInstanceLeaseExpirationRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/ec2/CheckApplicationTagRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/ec2/EC2DeprecatedInstanceTypeRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/ec2/EC2InstanceGenerationRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/ec2/EC2PublicAccessForConfiguredPortRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/ec2/EC2StoppedInstanceForLongRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/ec2/EC2WithPublicIPAccessTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/ec2/EC2withSeverityVulnerabilityRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/ec2/Ec2PublicAccessPortWithS5vulnerabilitiesRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/ec2/ElasticSearchInternalAccessRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/ec2/LowUtilizationAmazonEC2InstancesRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/ec2/ResourceScannedByQualysRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/ec2/ResourceWithSeverityVulnerabilityRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/ec2/SSMAgentCheckRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/ec2/TaggingRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/ec2/UnrestrictedNACLRuleForConfiguredPortTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/ecs/ECSTaskLogDriverInUseRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/efs/EfsEncryptionUsingKMSCMKsTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/efs/ElasticFileSystemEncryptionRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/eks/CheckEKSClusterEncryptionEnabledRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/eks/CheckEKSClusterLoggingEnabledRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/eks/CheckEKSClusterPublicAccessDisabledRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/eks/CheckEKSClusterVersionIsUpdatedRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/eks/CheckEKSInboundTrafficRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/eks/EksSecretsEncryptionRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/elasticache/ElastiCacheInTransitAndAtRestEncryptionRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/elasticip/UnusedElasticIpRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/elasticsearch/ElasticSearchPublicAccessRuleTest.java
Junits fixed as they were breaking
> fix: JUnits fixed

- webapp/src/app/pacman-features/modules/assets/asset-distribution/asset-distribution.component.ts
In Asset -> Distribution: Test in the box need to fit.  "IAM Customer Managed Policy" doesn't fit, can it be wrapped?
> fix:wrap label in treemap

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/elasticsearch/ESEncryptionAtRestRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/elasticsearch/ESEncryptionUsingKMSCMKsRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/elasticsearch/ESNodetoNodeEncryptionRule.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/elasticsearch/ESEncryptionAtRestRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/elasticsearch/ESEncryptionUsingKMSCMKsRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/elasticsearch/ESNodetoNodeEncryptionRuleTest.java
Changes to include open search version
> fix: JUnits and Rule logic for elastic search upgrade

- webapp/src/app/pacman-features/modules/assets/asset-dashboard/asset-dashboard.component.spec.ts
- webapp/src/app/pacman-features/modules/compliance/card/card.component.css
- webapp/src/app/pacman-features/modules/compliance/card/card.component.html
- webapp/src/app/shared/components/molecules/custom-card/custom-card.component.css
- webapp/src/app/shared/components/molecules/custom-card/custom-card.component.html
- webapp/src/app/shared/date-selection/date-selection.component.css
- webapp/src/app/shared/date-selection/date-selection.component.html
- webapp/src/app/shared/date-selection/date-selection.component.ts
- webapp/src/app/shared/shared.module.ts
https://user-images.githubusercontent.com/4422785/227731781-20b23511-1778-42ee-b0a7-d2ac19ee7e88.mp4
Fixes #998
> feat: custom date selection datepicker

- webapp/src/app/pacman-features/secondary-components/issues-trend-history/issues-trend-history.component.ts
- webapp/src/app/pacman-features/services/issues-history.service.ts
> fix: violations by severity tile legend order

- webapp/src/app/pacman-features/secondary-components/issues-trend-history/issues-trend-history.component.css
- webapp/src/app/pacman-features/secondary-components/issues-trend-history/issues-trend-history.component.html
> fix: updated violations by severity title

- installer/files/scripts/cloudformation_script.py
> template_fix

- webapp/src/app/pacman-features/modules/compliance/card/card.component.ts
- webapp/src/app/shared/components/molecules/custom-card/custom-card.component.ts
- webapp/src/app/shared/date-selection/date-selection.component.css
- webapp/src/app/shared/date-selection/date-selection.component.html
- webapp/src/app/shared/dropdown/dropdown.component.ts
https://user-images.githubusercontent.com/4422785/228889486-a5d3e552-aadf-4e76-b5e4-8fb30f211d58.mp4
Fixes #1022
> Bug: dashboard custom date empty menu

- webapp/src/app/pacman-features/modules/compliance/violations-card/violations-card.component.css
- webapp/src/app/pacman-features/modules/compliance/violations-card/violations-card.component.html
- webapp/src/app/pacman-features/modules/compliance/violations-card/violations-card.component.ts
- webapp/src/app/pacman-features/secondary-components/compliance-overview-trend/compliance-overview-trend.component.ts
- webapp/src/app/pacman-features/services/compliance-overview.service.ts
> feat: center text compliance dashboard & compliance trend legend order

- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.ts
- webapp/src/app/pacman-features/modules/compliance/compliance.module.ts
- webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase/policy-knowledgebase.component.css
- webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase/policy-knowledgebase.component.html
- webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase/policy-knowledgebase.component.ts
- webapp/src/app/shared/table/table.component.html
https://user-images.githubusercontent.com/4422785/229140569-0e1715fc-eeae-4526-a421-a38355a160b1.mp4
Fixes #1017
> feat: policy knowledgebase filtration

- api/pacman-api-asset/pom.xml
> reverting pom

- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/federated/CheckACMCertificateExpiredTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/federated/CheckIAMCertificateExpiredTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/federated/CheckSecurityHubEnabledRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/federated/RemoveRootUserAccountAccessKeyTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/federated/RootAccountHardwareMFACheckTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/guardduty/CheckGuardDutyFindingsExistsTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/guardduty/CheckGuardDutyForAllAccountsRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/iam/AWSSupportAccessRoleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/iam/AccessKeyRotatedRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/iam/AwsIamAccountWithPermanentAccessKeysRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/iam/CheckIamPasswordPolicyRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/iam/CheckInactiveIamUsersRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/iam/CustomerMangdPolicyWithAdminPrevilegeRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/iam/IAMAccessGrantForNonAdminAccountRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/iam/IAMRoleWithFullAdminPrevilegeRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/iam/IAMUserWithFullAdminPrevilegeRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/iam/IAMUserWithMultipleAccessKeyRuleTest.java
Junits and testing for following target types : federated, guardduty and iam
> fix: JUnits fixed for federated,guardduty and iam

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/utils/PacmanUtils.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/iam/PermissionsThroughGroupRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/iam/ServiceAccountPrivilegesRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/kms/CheckKeyRotationEnabledRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/lambda/CheckLambdaFunWithAdminOrIAMPrivilegesTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/lambda/LambdaFunctionInvocationCountRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/misc/CheckAWSCloudTrailConfigTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/misc/CheckAwsActivityInBlacklistedRegionRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/onprem/OnPremiseServerKernelComplianceRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/onprem/OnpremScannedByQualysRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/rds/AmazonRDSIdleDBInstancesRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/rds/CheckForRDSAutoMinorVersionUpgradeEnabledTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/rds/CheckForRDSSnapshotWithPublicAccessTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/rds/RDSDBPublicAcessRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/rds/RDSDBUnencryptedPublicAcessRuleTest.java
Fixed Junits. Fixed getting counts of total in OpenSearch
> fix: get value of total. JUnits fixed as well

- webapp/src/app/shared/table/table.component.html
- webapp/src/app/shared/table/table.component.ts
https://user-images.githubusercontent.com/4422785/229304217-a669ff75-a88a-4761-9384-4e342e4b7b22.mp4
Fixes #1031
> feat(table-component): clearing serach input and filters, when clear button clicked 

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/common/AdminConstants.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/NotificationServiceImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/NotificationServiceImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/util/Constants.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/Constants.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/utils/Constants.java
- installer/resources/pacbot_app/files/DB_Policy.sql
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/common/PacmanSdkConstants.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/commons/autofix/manager/IAutofixManger.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/dto/AutofixNotificationRequest.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/dto/PolicyViolationNotificationRequest.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/util/NotificationUtils.java
Added functionality to trigger lambda function url for autofix related notifications.
> feat: Trigger autofix related notifications from batch job

- webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.html
- webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.ts
> feat(issue-listing): row size has been set to small

- installer/resources/pacbot_app/files/DB_Policy.sql
Updated the value since dashboard screens were broken due to "autoFixEnabled" being null
> fix: update autoFixEnabled value

- webapp/src/app/pacman-features/modules/assets/asset-list/asset-list.component.html
- webapp/src/app/pacman-features/modules/assets/asset-list/asset-list.component.ts
- webapp/src/app/post-login-app/common/contextual-menu/contextual-menu.component.ts
also fixed missing fetchAssetTypes call in the context-menu constructor
Fixes #1057
> feat: asset-list row style

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/controller/NotificationsController.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/service/NotificationSettings.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/service/NotificationSettingsImpl.java
Create new api to return notification settings and corresponding email addresses for different channels(like email, slack etc..)
> feat: new api for notification settings and configurations

- installer/resources/pacbot_app/files/DB_Policy.sql
"Enable Soft Delete for Blob Storage" should not be deleted
> fix: enable soft delete for blob storage recovered

- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/jobs/HostAssetDataImporter.java
- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/jobs/HostAssetsEsIndexer.java
- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/util/ElasticSearchManager.java
- Corrected scroll query to read entire qualys knowledge base data
> fix: Host Asset Data Importer job

- webapp/src/app/pacman-features/secondary-components/policy-violation-desc/policy-violation-desc.component.html
Changed Creation date to Date Created and added a time stamp of the current day. 
Fixes #885
Viewed the text in a view window it was a text only change.
This is my first ever pull request.  I assumed time stamp meant current time.  Thanks for letting me try to contribute, hopefully I can learn from this.
> Fix: policy-violation-desc.html 

- jobs/gcp-discovery/pom.xml
Updated the maven assembly plugin version to match with mvn 3.0.5
> fix: modified pom.xml to use correct version for assembly plugin

- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/PacmanSdkConstants.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/utils/PacmanUtils.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/constants/PacmanRuleConstants.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/service/ServiceLimitRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/serviceaccounts/CheckImproperAccountNamesRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/serviceaccounts/ServiceAccountAdministratorsRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/serviceaccounts/ServiceAccountWithSvcRuleTest.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/PolicyExecutor.java
roleIdentifyingString fix and getSeviceLimit function fix
> roleIdentifyingString fix and getSeviceLimit function fix

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/common/AdminConstants.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/controller/AssetGroupController.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/domain/AssetGroupView.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/domain/CreateAssetGroup.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/domain/DataSourceObj.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/domain/UpdateAssetGroupDetails.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/AssetGroupCriteriaDetailsRepository.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/AssetGroupRepository.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/DatasourceRepository.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/model/AssetGroupCriteriaDetails.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/model/AssetGroupDetails.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AssetGroupService.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AssetGroupServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AssetGroupTargetDetailsService.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AssetGroupTargetDetailsServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/CreateAssetGroupService.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/CreateAssetGroupServiceImpl.java
- api/pacman-api-admin/src/test/java/com/tmobile/pacman/api/admin/controller/AssetGroupControllerTest.java
- api/pacman-api-admin/src/test/java/com/tmobile/pacman/api/admin/repository/service/AssetGroupServiceImplTest.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/Constants.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/repo/ElasticSearchRepository.java
> feat:asset group api code

- installer/resources/pacbot_app/files/DB_Policy.sql
> change policy display name

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/controller/AccountsController.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/domain/CreateAccountRequest.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/TenableAccountServiceImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/Constants.java
This PR is to add / enable tenable integration with Paladin
> feat: Support for tenable

- webapp/src/app/pacman-features/modules/compliance/issue-details/issue-details.component.ts
Added revoked by email in params for revoke exemption
> feat: Added revoked by email in params for revoke exemption

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/utils/RulesElasticSearchRepositoryUtil.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/constants/PacmanRuleConstants.java
Changes for Elastic search query executing function
[PC2-125](https://paladincloud.atlassian.net/browse/PC2-125)
[PC2-27]: https://paladincloud.atlassian.net/browse/PC2-27?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PC2-125]: https://paladincloud.atlassian.net/browse/PC2-125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Changes for Elastic search query executing function, resolves [PC2-125]

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/controller/AssetGroupController.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AssetGroupService.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AssetGroupServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AssetGroupTargetDetailsService.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AssetGroupTargetDetailsServiceImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/repo/ElasticSearchRepository.java
API to get Drop Down Key-Value pair from all CloudProviders.
> feat:API to get Drop Down Key-Value pair from all CloudProviders

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AwsAccountServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/util/AdminUtils.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/config/CredentialProvider.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/secrets/AwsSecretManagerUtil.java
- installer/resources/iam/base_role.py
Corrected AWS account validation API
> fix: Corrected AWS account validation API

- installer/resources/pacbot_app/files/DB.sql
> changed Resource Type to Asset Type

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/QualysAccountServiceImpl.java
- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/jobs/QualysDataImporter.java
-corrcetd secret manager path for qualys
> fix: Qualys collector fix

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/domain/PolicyViolationDetails.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/ComplianceServiceImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/Constants.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/ResourceWithSeverityVulnerabilityRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/model/CveDetails.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/model/QualysVulnerabilityinfo.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/utils/PacmanUtils.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/constants/PacmanRuleConstants.java
- added vulnerability details for qualys violations
- corrected qualys rule to populate
> fix: Qualys violation details

- webapp/src/app/shared/table/table.component.css
- webapp/src/app/shared/table/table.component.html
https://user-images.githubusercontent.com/4422785/233339702-bb79f547-5800-4319-8413-489f9b370e60.mp4
Fixes #1126
> feat(app-table): replaced custom sort icon with default one

- installer/resources/pacbot_app/files/DB.sql
- added filter chip fpr exempted and tagged asset list
> fix: PC2-301- Filter chips for exempted and tagged asset list

- installer/resources/pacbot_app/files/DB.sql
Corrected the issue in the db.sql
> fix: corrected the bug in db.sql

- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/config/CredentialProvider.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/utils/Constants.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/ResourceWithSeverityVulnerabilityRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/model/QualysVulnerabilityinfo.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/utils/PacmanUtils.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/PolicyExecutor.java
- added qualys vulnerabity url
> fix: Qualys vulnerabity URLS

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AwsAccountServiceImpl.java
> fix: AWS role name

- installer/resources/pacbot_app/files/DB.sql
update description and group type for asset group in database
> feat:update description and group type for asset group in database

- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/Constants.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/utils/Constants.java
- installer/settings/common.py
- lambda-functions/notification-invoke-service/src/main/java/com/paladincloud/SendNotification.java
- lambda-functions/notification-template-formatter-service/src/main/java/com/paladincloud/Constants.java
Rename event_source_name from 'PaladinCloud' to 'Paladin Cloud'.
> fix: change event_source_name from 'PaladinCloud' to 'Paladin Cloud'

- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/aws/CredentialProvider.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/ResourceWithSeverityVulnerabilityRule.java
- correcting the package to avoid conflicts
> fix: API task failure

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/BlobContainerInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/MariaDBInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/MySQLInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/NamespaceInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/PolicyStatesInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/PostgreSQLInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/SearchServiceInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/SecurityAlertsInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/SecurityPricingsInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/SitesInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/SnapshotInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/SubnetInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/VaultInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/WebAppInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/WorkflowInventoryCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/CloudAssetInventoryCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/GKEClusterInventoryCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/ProjectInventoryCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/StorageCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/vo/CloudAssetVH.java
updating region for azure and gcp inventory
> feat:adding region and resource group name for azure inventory

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/ResourceWithSeverityVulnerabilityRule.java
Updated Qualys CVE URL to NIST
> fix: Updated qualys cve url

- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/PolicyExecutor.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/util/NotificationUtils.java
> fix: remove multi threading for notifications

- webapp/src/app/pacman-features/modules/assets/asset-distribution/asset-distribution.component.html
- webapp/src/app/pacman-features/modules/assets/asset-distribution/asset-distribution.component.ts
- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.ts
- webapp/src/app/pacman-features/modules/compliance/violations-card/violations-card.component.html
- webapp/src/app/shared/components/molecules/overview-tile/overview-tile.component.html
- webapp/src/app/shared/multiline-zoom-graph/multiline-zoom-graph.component.ts
- webapp/src/app/shared/table/table.component.html
Applied numbers pipe to some places across the application
Fixes #1134
> feat: numbers formatting

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/ResourceWithSeverityVulnerabilityRule.java
Fixed broken qualys vulnerability details url
> fix: broken vulnerability details url

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/EC2withSeverityVulnerabilityRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/Ec2PublicAccessPortWithS5vulnerabilitiesRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/ResourceWithSeverityVulnerabilityRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/utils/PacmanUtils.java
Added qualys vulnerability for port access policy 
> fix: vulnerability details for qualys port policy

- webapp/src/app/post-login-app/default-asset-group/default-asset-group.component.html
> feat(numbers-formatting): asset count

- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.css
- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.html
- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.ts
- webapp/src/app/pacman-features/modules/compliance/services/dashboard-arrangement.service.spec.ts
- webapp/src/app/pacman-features/modules/compliance/services/dashboard-arrangement.service.ts
- webapp/src/app/shared/shared.module.ts
https://user-images.githubusercontent.com/4422785/234588346-2d654307-5228-432c-878f-dba1ce76ed3f.mp4
Fixes #1170
> feat: dashboard arrangement

- webapp/src/app/pacman-features/modules/notifications/cloud-notifications/cloud-notifications.component.ts
> feat(cloud-notifications): applied date pipe to created date

- webapp/src/app/pacman-features/modules/compliance/card/card.component.css
- webapp/src/app/pacman-features/modules/compliance/card/card.component.html
- webapp/src/app/pacman-features/modules/compliance/card/card.component.ts
- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.html
- webapp/src/app/pacman-features/modules/compliance/progress-bar-chart/progress-bar-chart.component.css
- webapp/src/app/pacman-features/modules/compliance/progress-bar-chart/progress-bar-chart.component.html
- webapp/src/app/pacman-features/modules/compliance/progress-bar-chart/progress-bar-chart.component.ts
https://user-images.githubusercontent.com/4422785/234896966-0f6719d0-b272-4bf5-9eec-5649c9d4b077.mp4
Fixes #1171
> feat(compliance-dashboard): navigation to violations by category

- installer/resources/pacbot_app/files/DB.sql
Added filter metadata for asset,violation,notifications
> fix: filter metadata

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/utils/RulesElasticSearchRepositoryUtil.java
> fix: aws fix for policy[MVP2023-174]

- webapp/src/app/pacman-features/modules/assets/asset-list/asset-list.component.ts
- webapp/src/app/shared/table/table.component.html
1. Fixed asset list when navigate through asset summary
2. Fixed breadcrumb in asset list
> fix: asset list when navigate through asset summary

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/AssetConstants.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/controller/AssetListController.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/domain/Request.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepository.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepositoryImpl.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/CloudNotificationsRepositoryImpl.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetService.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetServiceImpl.java
- api/pacman-api-asset/src/test/java/com/tmobile/pacman/api/asset/controller/AssetListControllerTest.java
- api/pacman-api-asset/src/test/java/com/tmobile/pacman/api/asset/repository/AssetRepositoryTest.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/controller/FilterController.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/FilterRepository.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/FilterRepositoryImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/FilterService.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/FilterServiceImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/Constants.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/repo/ElasticSearchRepository.java
Filter support for violation, asset and notifications
> fix: filter support in violations, assets and notifications

- lambda-functions/notification-template-formatter-service/src/main/java/com/paladincloud/CommonUtils.java
- lambda-functions/notification-template-formatter-service/src/main/java/com/paladincloud/Constants.java
- lambda-functions/notification-template-formatter-service/src/main/resources/approveExemptionRequestEmailTemplate.html
- lambda-functions/notification-template-formatter-service/src/main/resources/cancelExemptionRequestEmailTemplate.html
- lambda-functions/notification-template-formatter-service/src/main/resources/createExemptionRequestEmailTemplate.html
- lambda-functions/notification-template-formatter-service/src/main/resources/revokeExemptionRequestEmailTemplate.html
changes for MVP2023-105
MVP2023-105
> changes for MVP2023-105

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/QualysAccountServiceImpl.java
> fix: Qualys delete account fix

- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/config/CredentialProvider.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/PacmanSdkConstants.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/aws/clients/impl/AWSClientManagerImpl.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/policy/Annotation.java
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/auth/CredentialProvider.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/common/PacmanSdkConstants.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/PolicyExecutor.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/util/CommonUtils.java
Added a check to use External ID in case it is required to use while assuming the role.
> feat: added ability to use external id [MVP2023-300]

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/CloudNotificationsRepositoryImpl.java
- lambda-functions/notification-es-logging-service/src/main/java/com/paladincloud/notification_log/LogNotificationToOpenSearch.java
Fix for notifications API and lambda function
> fix for notifications

- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/util/CommonUtils.java
Corrected the system props overriding issue, which is causing the collectors to fail.
> fix: corrected system properties overload issue [MVP2023-300]

- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/util/PolicyExecutionUtils.java
non-compliance resource severity and category fix.
> fix: non-compliance resource severity and category fix

- installer/files/scripts/build_pacbot.py
- installer/provison.sh
Upgraded maven to resolve GCP collector failure
> fix: MVP2023-351- upgrading maven to resolve gcp collector issue

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/constants/PacmanRuleConstants.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/MultiThreadedPolicyRunner.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/SingleThreadPolicyRunner.java
Add accountid and accountname fields for all violations. accountid will be same as projectId/subscription fields and accountname will be same as projectName and subscriptionName fields.
> [MVP2023-12] add accountid and account name for gcp and azure violations

- jobs/recommendation-enricher/src/main/java/com/tmobile/cso/pacbot/recommendation/entity/RecommendationCollector.java
- jobs/recommendation-enricher/src/main/java/com/tmobile/cso/pacbot/recommendation/es/ESManager.java
Upgrade recommendation enricher for open search
> fix for [MVP2023-336]

- README.md
Updating the survey link to go to the right location.
> fix for broken link

- installer/resources/pacbot_app/files/DB.sql
Corrected metadata for violation filters
> fix- Mvp2023 376 metadata

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/util/AssetGroupUtil.java
Corrected data shipper to fetch asset and violation count
> fix: MVP2023-366- Data shipper

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/VMInventoryCollector.java
- corrected VM fetch endpoint
- Handled error so as not to fail entire job
> fix: MVP2023-345-Azure collector

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/AssetGroupStatsCollector.java
Same id is getting generated for different documents. Updated the code such that unique id is generated for each asset stats.
> [MVP2023-108] fix for asset trend and violation trend data

- jobs/pacman-aqua-enricher/src/main/java/com/tmobile/cso/pacman/aqua/jobs/AquaFunctionVulnerabilityDataImporter.java
- jobs/pacman-aqua-enricher/src/main/java/com/tmobile/cso/pacman/aqua/jobs/AquaImageVulnerabilityDataImporter.java
- jobs/pacman-aqua-enricher/src/main/java/com/tmobile/cso/pacman/aqua/jobs/AquaVMVulnerabilityDataImporter.java
- jobs/pacman-aqua-enricher/src/main/java/com/tmobile/cso/pacman/aqua/util/ElasticSearchManager.java
> removed type and introduced docType for aqua collector [MVP2023-253]

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AbstractAccountServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AwsAccountServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AzureAccountServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/GcpAccountServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/QualysAccountServiceImpl.java
- Handled account failures to delete DB entry
> fix: MVP2023-128-Account-created-on-failure

- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/publisher/impl/AnnotationPublisher.java
- Corrected annotation publisher relations mapping
> fix: MVP2023-459

- README.md
Fixed several dead links to installation guidance which led to non-existing pages.
> Update links to installation page

- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/jobs/HostAssetDataImporter.java
> fix: qualys data shipper

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/VMsScannedByTenableRule.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/jobs/TenableVMVulnerabilityDataImporter.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/util/ElasticSearchManager.java
Upgrade tenable collector and policies for open search
> os upgrade[MVP2023-254]

- api/pacman-api-vulnerability/src/main/java/com/tmobile/pacman/api/vulnerability/repository/VulnerabilityRepository.java
- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/jobs/HostAssetsEsIndexer.java
- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/jobs/Util.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/PolicyExecutor.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/ShutDownHook.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/reactors/PacEventHandler.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/service/ExceptionManagerImpl.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/service/ResourceOwnerService.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/util/AuditUtils.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/util/ESUtils.java
- lambda-functions/notification-es-logging-service/src/main/java/com/paladincloud/notification_log/LogNotificationToOpenSearch.java
> bug:issue audit log violations [MVP2023-510]

- installer/resources/pacbot_app/files/DB_Cognito.sql
Added permission for acc management for enabling account management APIS
> Account permission for account APIs

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/BlobContainerInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/SecurityPricingsInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/SubnetInventoryCollector.java
fix for : Azure data not getting populated for blobcontainer, securitypricings and subnets
> fix[MVP2023-591]

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/AssetGroupStatsCollector.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/EntityManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/es/ESManager.java
Fix for datashipper issues - 1. child relations records are not getting deleted.
> fix: move dummy indices creation to different method

- installer/resources/pacbot_app/files/DB.sql
> bug:admin plugin filter inserts [MVP2023-587]

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/iam/CheckIamPasswordPolicyRule.java
> Revert "fix: modified condition"

- installer/resources/pacbot_app/files/DB.sql
> bug:duplicate filters in table pac_v2_ui_options

- webapp/src/app/post-login-app/common/contextual-menu/contextual-menu.component.css
- webapp/src/app/post-login-app/post-login-app.component.css
> fix(contextual-menu): menu is clipped in mobile safari

- webapp/src/app/post-login-app/common/header/header.component.css
- webapp/src/app/post-login-app/common/header/header.component.html
- webapp/src/app/post-login-app/common/header/header.component.ts
https://github.com/PaladinCloud/CE/assets/4422785/f952c3c4-4017-4a7a-8d4f-fc7cbd8d12c9
Fixes #1227
> feat(header): navigate to dashboard upon company logo click

- webapp/src/app/app-routing.module.ts
https://github.com/PaladinCloud/CE/assets/4422785/50f6ae09-b788-40ba-a053-0110ce458a84
Fixes #1226
> fix(routing): handle unrecognized pl navigation redirect

- webapp/src/app/core/services/workflow.service.ts
- webapp/src/app/pacman-features/modules/omnisearch/omni-search-details/omni-search-details.component.html
- webapp/src/app/pacman-features/modules/omnisearch/omni-search-details/omni-search-details.component.ts
> feat: omnisearch breadcrumb

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/constants/PacmanRuleConstants.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/publisher/impl/AnnotationPublisher.java
[CUS-70] issue status update 
Post OpenSearch upgrade Issue status is not updating in elastic search. Once the issue is generated for a resource in the OpenSearch in the next scan If the resource got compliance with the policy then the issue status is not updating to close.  
[CUS-70]: https://paladincloud.atlassian.net/browse/CUS-70?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: [CUS-70] issue status update

- jobs/pacman-data-shipper/pom.xml
- jobs/pacman-data-shipper/src/main/resources/logback.xml
Update pom of data shipper to disable debug and info level logs.
> [CORE-285] disable info and debug logs

- installer/resources/pacbot_app/files/DB_Policy.sql
- lambda-functions/notification-template-formatter-service/src/main/java/com/paladincloud/CommonUtils.java
- lambda-functions/notification-template-formatter-service/src/main/java/com/paladincloud/FetchNotificationSettings.java
- lambda-functions/notification-template-formatter-service/src/main/resources/policyActionEmailTemplate.html
[CORE-567]
[CORE-567]: https://paladincloud.atlassian.net/browse/CORE-567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> changes for CORE-567

- installer/resources/pacbot_app/files/DB.sql
correcting inserts for plugin filter value 
> bug:correcting inserts for plugin filter value [CORE-689]

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/common/AdminConstants.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AssetGroupServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/EsCommonService.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/EsCommonServiceImpl.java
> Cherry_picked cloud Type Object asset creation

- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/PolicyExecutor.java
-Commented the dangling issue update
> fix:[CORE-492] Commented the dangling issue update

- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/PolicyExecutor.java
Modified Policy engine to update the category and severity of an existing non-compliance resource. 
Fixes # (issue) [CORE-483] Asset Details No Data problems
[CORE-483]: https://paladincloud.atlassian.net/browse/CORE-483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix:[CORE-483] Asset Details No Data problems

- installer/resources/pacbot_app/files/DB.sql
…screen [UIUX-60]
Enhanced Filter/Sort for Dashboard - Policy Compliance overview screen
[UIUX-60]: https://paladincloud.atlassian.net/browse/UIUX-60?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat:[UIUX-60] Enhanced Filter/Sort for Dashboard - Policy Compliance overview

- webapp/src/app/shared/table-filters/table-filter-chip/table-filter-chip.component.ts
- webapp/src/app/shared/table-filters/table-filters.component.css
- webapp/src/app/shared/table-filters/table-filters.component.html
Solves an issue on the following screenshot:
also fixes layout shift, when a new item is added to applied filters list
> fix: table filters error state options

- lambda-functions/notification-template-formatter-service/src/main/java/com/paladincloud/FetchNotificationSettings.java
> fix:[CORE-567]lambda_function_email_bug

- installer/resources/pacbot_app/files/DB_Policy.sql
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/azurerules/MySQLFlexibleServer/MinTLSVersionRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/constants/PacmanRuleConstants.java
Corrected Policy params to avoid policy failures
> fix:[CORE-711]Policy fix for violation mismatches

- webapp/angular.json
- webapp/package.json
- webapp/src/app/core/services/tour.service.ts
- webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase/policy-knowledgebase.component.ts
- webapp/src/app/pacman-features/secondary-components/compliance-overview-trend/compliance-overview-trend.component.ts
- webapp/src/app/post-login-app/asset-groups/asset-groups.component.ts
- webapp/src/app/post-login-app/common/contextual-menu/contextual-menu.component.html
- webapp/src/app/post-login-app/common/contextual-menu/contextual-menu.component.ts
- webapp/src/styles.css
https://github.com/PaladinCloud/CE/assets/4422785/06ba7fba-4ab6-4345-ab7d-2a4be7948158
Fixes #1274
> feat: tour upgrade

- webapp/src/app/shared/table-filters/table-filter-chip/table-filter-chip.component.ts
- webapp/src/app/shared/table-filters/table-filters.component.html
- webapp/src/app/shared/table-filters/table-filters.component.ts
prevent undefined from being passed to appliedFiltersDict' Object.entries function
> fix(table-filter-chip): handle possible undefined values

- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/commons/autofix/manager/IAutofixManger.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/publisher/impl/ElasticSearchDataPublisher.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/util/CommonUtils.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/util/ESUtils.java
> fix: fix for autofix util methods

- installer/resources/pacbot_app/files/DB.sql
Add column optionType to table to identify filter where options will be sent as range
> feat:[UIUX-60]Add column optionType to options table 

- installer/resources/pacbot_app/files/DB_Policy.sql
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/constants/PacmanRuleConstants.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/VPCNetwork/VPCFirewallUncommonports.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/VPCNetwork/VPCNetworkOutboundRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/VPCNetwork/VPCNetworkRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/utils/GCPFirewallUtils.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/gcprules/VPCFirewall/Utils/TestUtils.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/gcprules/VPCFirewall/VPCFireWallEgressTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/gcprules/VPCFirewall/VPCFirewallRuleTest.java
[CORE-772]
updated vpc firewall policies
[CORE-772]
updated vpc firewall policies
[CORE-772]
> fix:[CORE-772]update_vpc_firewall_policies

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/DiagnosticSettingsCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/PolicyStatesInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/SCRecommendationsCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/SubnetInventoryCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/FirewallInventoryCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/LoadBalancerCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/NetworkInventoryCollector.java
Region values are blank while creating asset group , to fix this we need to set region in collectors of azure and gcp
> fix:[CORE-697] Region values fixed for azure and gcp

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/constants/PacmanRuleConstants.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/ServerlessPolicyHandler.java
Modify the server less policy response object. 
Fixes # [CUS-76]
[CUS-76]: https://paladincloud.atlassian.net/browse/CUS-76?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix: [CUS-76] serverless policy fix

- installer/resources/pacbot_app/files/DB.sql
> fix:[CORE-781]Corrected filter attribute APIs

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/azurerules/NSGRule/PublicAccessforConfiguredPort.java
Ports aren't visible in UI due to conversion issue 
> fix:[CUS-86] convert array to string

- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/jobs/QualysDataImporter.java
- Handled Qualys API response to avoid long running process
> fix:[CORE-799]Corrected qualys job

- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/file/FileManager.java
Corrected VPC data files to separate out cidr-association in new data file
> fix:[CORE-753]Corrected VPC data files to avoid duplicate

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/NotificationServiceImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/NotificationServiceImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/Constants.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/utils/Constants.java
- installer/resources/pacbot_app/files/DB_Policy.sql
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/util/NotificationUtils.java
- lambda-functions/notification-template-formatter-service/src/main/java/com/paladincloud/CommonUtils.java
Rename ‘Policyaction’ to ‘Policy’
[CORE-769]
[CORE-769]
[CORE-769]: https://paladincloud.atlassian.net/browse/CORE-769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CORE-769]: https://paladincloud.atlassian.net/browse/CORE-769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix:[CORE-769]/rename_policyaction_to_policy_in_notification

- installer/resources/pacbot_app/files/DB.sql
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/es/ESManager.java
Fix datashipper issues in testdrive
> fix:[CORE-819] datashipper issues in testdrive

- installer/resources/pacbot_app/files/DB_Policy.sql
> fix:[CUS-71] Changed Policy DisplayName

- installer/resources/pacbot_app/files/DB_Policy.sql
- installer/settings/common.py
- lambda-functions/notification-template-formatter-service/src/main/java/com/paladincloud/CommonUtils.java
- lambda-functions/notification-template-formatter-service/src/main/java/com/paladincloud/Constants.java
- lambda-functions/notification-template-formatter-service/src/main/java/com/paladincloud/FetchNotificationSettings.java
- lambda-functions/notification-template-formatter-service/src/main/resources/closeViolationsJiraTemplate.html
- lambda-functions/notification-template-formatter-service/src/main/resources/openViolationsJiraTemplate.html
Configure jira in lambda for create violation.
> fix:[CORE-801] change subject for jira notifications in lambda functions

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/es/ESManager.java
Modified the index setting to avoid errors due to malformed data. Also increased the max fields per index.
> feat:[CORE-758] modified the index settings

- installer/resources/pacbot_app/files/DB.sql
- installer/resources/pacbot_app/import_db.py
- installer/settings/common.py
- installer/settings/default.local.py
- jobs/job-scheduler/src/main/java/com/paladincloud/jobscheduler/service/JobScheduler.java
> fix:[CORE-713]Added aws enabled flag

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/es/ESManager.java
Load Date update issue in data shipper. For all Asset Type have child data modified the error handler method .
modified the ES query to  update loaddate only to the child type 
Fixes # [CORE-828]
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
[CORE-828]: https://paladincloud.atlassian.net/browse/CORE-828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: [CORE-828] LoadDate update issue in datashipper.

- installer/resources/pacbot_app/files/DB.sql
> bug:[UIUX-60]metadata changes

- installer/resources/pacbot_app/files/DB_Policy.sql
> fix:[CUS-113] policy Description

- webapp/.gitignore
> Update gitignore for webapp

- installer/resources/lambda_submit/function.py
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/Main.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/jobs/TenableDataImporter.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/jobs/TenableVMVulnerabilityDataImporter.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/util/ElasticSearchManager.java
Change logic for calculate time range in tenable collector
> fix:[CORE-750]Logic change for tenable collector

- installer/resources/pacbot_app/files/DB.sql
Meta data for asset list filter along with stored procedure to add mandatory tags
> bug:[CORE-377]metadataforassetfilterwith mandatorytags stored procedure

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/cloudsql/DisableOrEnableDBFlagsRule.java
Reason for policy failure : policy keys needs to be consistent
> fix:[CORE-894]Failed policies fixed

- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/jobs/QualysDataImporter.java
> fix:CORE-895:Performance optimisation for Quays KB API

- webapp/angular.json
Importing ag-grid-community script into angular.json is not required per [installation instructions.](https://www.ag-grid.com/angular-data-grid/getting-started/) This reduces the bundle's transferred size by 200KB
before:
Initial Chunk Files           | Names         |  Raw Size | Estimated Transfer Size
---------------------------------|------------------|---------------|--------------------------------
main.2841ad557c6a264d.js      | main          |   6.20 MB |                 1.04 MB
scripts.07eb6a819c595eb6.js   | scripts       |   1.09 MB |               194.90 kB
styles.967286a2d7067b4c.css   | styles        | 320.84 kB |                36.16 kB
polyfills.05d2ceb1349061a4.js | polyfills     |  70.27 kB |                21.84 kB
runtime.cb357873e10fa083.js   | runtime       |   1.30 …
> fix(build): remove obsolete ag-grid-table script import

- installer/resources/lambda_rule_engine/files/rule_engine_cloudwatch_aws_rules.json
Duplicate policies removed from aws json
> fix:[CORE-906]Duplicate policies for plugin

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/TaggingRule.java
> fix:[CUS-47] AWS managed resource from validating the policy.

- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/policy/Annotation.java
- installer/resources/pacbot_app/files/DB.sql
- jobs/pacman-rule-engine-2.0/pom.xml
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/autofix/elasticip/UnusedElasticIPAutofix.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/autofix/s3/S3GlobalAccessAutoFix.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/autofix/sg/UnusedSgAutoFix.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/commons/autofix/manager/AutoFixManager.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/commons/autofix/manager/IAutofixManger.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/dto/AutoFixTransaction.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/dto/ESBulkApiResponse.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/dto/Index.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/dto/Item.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/dto/Shards.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/PolicyExecutor.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/publisher/impl/ElasticSearchDataPublisher.java
- jobs/pacman-rule-engine-2.0/src/test/java/com/tmobile/pacman/publisher/impl/ElasticSearchDataPublisherTest.java
AutoFix fixes post OpenSearch upgrade. 
Fixes # [CORE-884]
[CORE-884]: https://paladincloud.atlassian.net/browse/CORE-884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fixcore 884/notification fix

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/TaggingRule.java
> fix:[CUS-47] Updated condition for compliant of policy.

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/MainUtil.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/config/ConfigManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/EntityManager.java
> feat:[Core-673] Added TargetType DisplayName in entity data.

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/EntityManager.java
> fix [Core-673]:Added displayName in docs

- webapp/src/app/pacman-features/modules/admin/create-edit-policy/create-edit-policy.component.css
- webapp/src/app/pacman-features/modules/admin/create-edit-policy/create-edit-policy.component.html
- webapp/src/app/pacman-features/modules/admin/create-edit-policy/create-edit-policy.component.ts
- webapp/src/app/pacman-features/modules/admin/policies/policies.component.css
- webapp/src/app/pacman-features/modules/admin/policies/policies.component.html
- webapp/src/app/pacman-features/modules/admin/policies/policies.component.ts
> fix:[UIUX-240] Policy screen updates

- webapp/src/app/pacman-features/modules/assets/asset-dashboard/asset-dashboard.component.css
- webapp/src/app/pacman-features/modules/assets/asset-dashboard/asset-dashboard.component.html
- webapp/src/app/pacman-features/modules/assets/asset-dashboard/asset-dashboard.component.ts
- webapp/src/app/pacman-features/modules/assets/asset-details/asset-details.component.css
- webapp/src/app/pacman-features/modules/assets/asset-details/asset-details.component.html
- webapp/src/app/pacman-features/modules/assets/asset-details/asset-details.component.ts
- webapp/src/app/pacman-features/modules/assets/asset-distribution/asset-distribution.component.css
- webapp/src/app/pacman-features/modules/assets/asset-distribution/asset-distribution.component.html
- webapp/src/app/pacman-features/modules/assets/asset-distribution/asset-distribution.component.ts
- webapp/src/app/pacman-features/modules/assets/asset-list/asset-list.component.ts
- webapp/src/app/pacman-features/services/issue-filter.service.ts
- webapp/src/app/post-login-app/post-login-app.module.ts
- webapp/src/app/shared/components/molecules/overview-tile/overview-tile.component.css
- webapp/src/app/shared/components/molecules/overview-tile/overview-tile.component.html
- webapp/src/app/shared/components/molecules/overview-tile/overview-tile.component.ts
- webapp/src/app/shared/shared.module.ts
> fix:[UIUX-245] refactored asset screens in CE

- installer/resources/pacbot_app/files/DB.sql
- installer/resources/pacbot_app/import_db.py
> bug:[CORE-969]api updates for violations and assets

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/securitycenter/AzureSecurityCenterRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/azurerules/StorageAccount/StorageAccountCMKEncryptionRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/azurerules/VirtualMachine/EndpointProtectionRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/APIKeys/RotateAPIKeysRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/cloudDNS/EnableDNSSec.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/cloudkmskeys/KeyPublicAccessRule.java
> fix:[CORE-993]Policy key issue

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/controller/CloudNotificationsController.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/CloudNotificationsRepository.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/CloudNotificationsRepositoryImpl.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/CloudNotificationService.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/CloudNotificationServiceImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/repo/ElasticSearchRepository.java
Notifications sorting and filter sync
> [CORE-1002]Sorting and filter for notifications

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/controller/FilterController.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/FilterRepository.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/FilterRepositoryImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/FilterService.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/FilterServiceImpl.java
- api/pacman-api-compliance/src/test/java/com/tmobile/pacman/api/compliance/controller/FilterControllerTest.java
- api/pacman-api-compliance/src/test/java/com/tmobile/pacman/api/compliance/repository/FilterRepositoryImplTest.java
- api/pacman-api-compliance/src/test/java/com/tmobile/pacman/api/compliance/service/FilterServiceImplTest.java
- api/pacman-api-statistics/src/main/java/com/tmobile/pacman/api/statistics/repository/StatisticsRepositoryImpl.java
api changes for dashboard and filter and statistics api
> bug:[CORE-968]api changes for dashboard and filter and statistics api

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/RecommendationsRepository.java
OS upgrade for recommendations
> [CORE-1007]OS upgrade for recommendations

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/AssetConstants.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/client/ComplianceServiceClient.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/controller/AssetCountController.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/controller/AssetListController.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/domain/FilterRequest.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/domain/PolicyParamDto.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/domain/PolicyParamResponse.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepository.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepositoryImpl.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetService.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetServiceImpl.java
- api/pacman-api-statistics/src/main/java/com/tmobile/pacman/api/statistics/repository/StatisticsRepository.java
- api/pacman-api-statistics/src/main/java/com/tmobile/pacman/api/statistics/repository/StatisticsRepositoryImpl.java
- api/pacman-api-statistics/src/main/java/com/tmobile/pacman/api/statistics/service/StatisticsServiceImpl.java
- api/pacman-api-vulnerability/src/main/java/com/tmobile/pacman/api/vulnerability/repository/VulnerabilityRepository.java
- api/pacman-api-vulnerability/src/main/java/com/tmobile/pacman/api/vulnerability/repository/VulnerabilityTrendGenerator.java
- api/pacman-api-vulnerability/src/main/java/com/tmobile/pacman/api/vulnerability/repository/VulnerabilityTrendGenerator2.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/repo/ElasticSearchRepository.java
Api changes for policy and assets screen. 
> bug:[CORE-971]api changes for policy assets

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/AssetConstants.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepositoryImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/controller/PolicyAssetController.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/PolicyTableRepository.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/PolicyAssetService.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/PolicyAssetServiceImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/util/CommonUtil.java
Asset count is not correctly displayed in OSS dev
> [CORE-1016]Asset group selector asset count

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/RecommendationsRepository.java
Recommendations API need OS upgrade
> [CORE-1007]Recommendation OS upgrade

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/TaggingRepositoryImpl.java
api changes for vulnerability and statistics.
> bug:[CORE-971]api changes for vulnerability and statistics

- installer/resources/pacbot_app/files/DB.sql
> bug:[CORE-971]filter changes for violations

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/azurerules/NSGRule/PublicAccessforConfiguredPort.java
> fix:[CUS-154] Condition for validating the policy.

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepositoryImpl.java
> bug:[CORE-1004]Exempt Assets count is not populated

- installer/resources/pacbot_app/files/DB.sql
> feat:[CORE-960] inserted rows in pac_v2_ui_options

- installer/resources/pacbot_app/files/DB_Policy.sql
> fix:[CORE-1018]Changed Policy DisplayName.

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/azurerules/VirtualMachine/EndpointProtectionRule.java
> [CORE-993]Azure rule

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/controller/CloudNotificationsController.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepositoryImpl.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/CloudNotificationsRepositoryImpl.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/RecommendationsRepository.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetServiceImpl.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/SearchServiceImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/repo/PacmanRdsRepository.java
> bug:[CORE-969]asset module changes

- installer/resources/datastore/es.py
- installer/resources/lambda_rule_engine/function.py
- installer/resources/lambda_submit/function.py
- installer/resources/pacbot_app/ecs_task_defintions.py
- installer/settings/common.py
- installer/settings/default.local.py
Installer fix
eventbridge installer bug
os upgrade installer changes 
ECS configuration 
> chore: installer fix ecs cpu configuration

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AquaAccountServiceImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/Constants.java
> bug:[CORE-942] violation api failure

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/utils/GCPFirewallUtils.java
> [CORE-1028]ICMP policy

- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.ts
- webapp/src/app/shared/table-filters/table-filters.component.ts
Fixes breaking of filters when navigated from dashboard to violations list
Fixes display of wrong filter when asset switch with a selected filter
> fix: filters wrongly displaying value on asset switch

- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/publisher/impl/AnnotationPublisher.java
> fix:[Core-673] Added TargetTypeDisplayName parameter in violations.

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/controller/ComplianceController.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/PolicyTableService.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/PolicyTableServiceImpl.java
> bug:[CORE-942] policy param failure

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/file/AssetFileGenerator.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/file/AssetFileGenerator.java
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/file/AssetFileGenerator.java
1. Incase data collector is able to connect to cloud application, update account status as configured instead of online.
> fix:[CORE-965] update account status as 'configured' instead of 'online'

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepositoryImpl.java
- installer/resources/pacbot_app/files/DB.sql
Exempted assets response should be proper
> fix:[CORE-1072]Exempted filter

- installer/resources/pacbot_app/files/DB.sql
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/WebAppInventoryCollector.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/es/ESManager.java
> [Cus 144 ]Adding asset id display name

- installer/resources/pacbot_app/files/DB.sql
> bug:[CORE-1072]Asset tagged exempted filter metadata

- installer/resources/pacbot_app/files/DB.sql
- webapp/src/app/core/services/auth.service.ts
- webapp/src/app/pacman-features/modules/assets/asset-list/asset-list.component.ts
- webapp/src/app/shared/table-filters/table-filter-chip/table-filter-chip.component.ts
> fix: [UIUX-213] resourceType typo in DB

- installer/resources/pacbot_app/files/DB.sql
> fix:[CORE-600]Asset Grup CreateBy is wrong for Azure AG

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/EntityAssociationManager.java
Delete old documents for children
> fix:[CUS-162]Recommendation data fix

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/enums/PolicyComplianceFilter.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/FilterRepository.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/FilterRepositoryImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/ComplianceServiceImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/FilterServiceImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/Constants.java
> bug:[CORE-1072] filter api changes

- webapp/src/app/pacman-features/modules/assets/asset-details/asset-details.component.ts
- webapp/src/app/pacman-features/modules/assets/asset-list/asset-list.component.ts
1. Display assetIdDisplayName in asset id column in asset list.
2. Sort based on assetIdDisplayName for azure (doesn't work properly because of case sensitive sort is happening).
3. Display assetIdDisplayName in asset details.
> feat: asset id display name in asset list

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/ComplianceServiceImpl.java
Violation Audit Log - Column Source should be "System"
> bug:[CORE-1110] Violation Audit Log - Column Source should be "System"

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/ComplianceServiceImpl.java
Violations are not in sync between Violations screen and Policy Compliance overview
> bug:[CORE-1107] Violations are not in sync

- webapp/src/app/pacman-features/modules/statistics/statistics/statistics.component.ts
- webapp/src/app/shared/data-table/data-table.component.css
- webapp/src/app/shared/data-table/data-table.component.html
- webapp/src/app/shared/data-table/data-table.component.ts
fixed violation date format in audit log table
added paladin icon in statistics page
> fix:[CORE-1111] fixed violation date format in audit log table

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/controller/CloudNotificationsController.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/domain/Request.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/CloudNotificationsRepository.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/CloudNotificationsRepositoryImpl.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/CloudNotificationService.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/CloudNotificationServiceImpl.java
> feat:[CORE-959] Created Date filter in Notifications List View

- installer/resources/pacbot_app/files/DB.sql
> fix:[CORE-966]restricting plugin access other than "Technical Admin" role

- installer/resources/pacbot_app/files/DB.sql
excluding category filter update for policy.
> bug:[CORE-1072] category

- installer/resources/pacbot_app/files/DB.sql
- installer/resources/pacbot_app/files/DB_Cognito.sql
> bug:[CORE-1072] role permissions db change

- webapp/angular.json
- webapp/src/app/pacman-features/modules/assets/asset-details/asset-details.component.html
- webapp/src/app/pacman-features/modules/assets/asset-details/asset-details.component.ts
- webapp/src/app/pacman-features/modules/assets/asset-distribution/asset-distribution.component.ts
- webapp/src/app/pacman-features/modules/assets/asset-list/asset-list.component.ts
- webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.ts
- webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase-details/policy-knowledgebase-details.component.html
- webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase/policy-knowledgebase.component.ts
- webapp/src/app/pacman-features/secondary-components/attribute/attribute.component.ts
- webapp/src/app/shared/services/utils.service.ts
- webapp/src/app/shared/table/table.component.ts
- webapp/src/styles.css
> Fix UI/bugs

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/es/ESManager.java
> [Cus-144] asset id display name-Sort Fix

- installer/resources/pacbot_app/files/DB.sql
- webapp/src/app/pacman-features/modules/assets/asset-list/asset-list.component.ts
- webapp/src/app/pacman-features/secondary-components/tagging-across-target-type/tagging-across-target-type.component.ts
- webapp/src/app/pacman-features/secondary-components/tagging-summary/tagging-summary.component.ts
> fix:[UIUX-1102] fixed tagging summary

- README.md
Tweaked the intro and added in a banner and link to the TryNow environment
> Add TryNow banner to README.md

- installer/settings/default.local.py
> chore:updated local py

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/SCRecommendationsCollector.java
> fix:[CUS-144]Security Center resource Group Not found issue

- webapp/src/app/pacman-features/modules/assets/asset-details/asset-details.component.ts
- webapp/src/app/pacman-features/modules/assets/asset-list/asset-list.component.ts
- webapp/src/app/shared/breadcrumb/breadcrumb.component.css
- webapp/src/app/shared/breadcrumb/breadcrumb.component.html
> fix:[UIUX-1102] fixed naviagtion issue

- installer/resources/pacbot_app/files/DB.sql
> bug:[CORE-1060]resource type filter id

- webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase/policy-knowledgebase.component.ts
> fix: user policies - all policies tile click not applying correctly

- webapp/src/app/pacman-features/modules/admin/user-management/user-management.component.ts
- webapp/src/app/post-login-app/common/contextual-menu/contextual-menu.component.css
> fix: add user with role_user

- installer/resources/pacbot_app/files/DB.sql
> bug:[CORE-1060]filter options

- webapp/src/app/pacman-features/modules/assets/asset-dashboard/asset-dashboard.component.ts
- webapp/src/app/pacman-features/secondary-components/tagging-summary/tagging-summary.component.ts
- webapp/src/app/post-login-app/common/contextual-menu/contextual-menu-nodes.ts
> fix: tagging and asset summary tagging counts

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepository.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepositoryImpl.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetService.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetServiceImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/domain/ExemptionResponse.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/repo/ElasticSearchRepository.java
Dynamic filter support for tagged assets list.
> bug:[CORE-1060]dynamic filter support for asset list

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/FunctionAppInventoryCollector.java
> fix:[CORE-1137] Function App AssetIdDisplayName fix

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/TaggingServiceImpl.java
- webapp/src/app/pacman-features/modules/assets/asset-list/asset-list.component.ts
- webapp/src/app/pacman-features/secondary-components/list-table/list-table.component.html
- webapp/src/app/pacman-features/secondary-components/list-table/list-table.component.ts
- webapp/src/app/pacman-features/secondary-components/tagging-summary/tagging-summary.component.ts
- webapp/src/app/pacman-features/secondary-components/total-tag-compliance/total-tag-compliance.component.html
> fix: removed links from total tag compliance

- webapp/src/app/pacman-features/modules/assets/asset-list/asset-list.component.html
- webapp/src/app/pacman-features/modules/assets/asset-list/asset-list.component.ts
- webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.html
- webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.ts
- webapp/src/app/shared/table-filters/table-filter-chip/table-filter-chip.component.html
- webapp/src/app/shared/table-filters/table-filter-chip/table-filter-chip.component.ts
- webapp/src/app/shared/table-filters/table-filters.component.html
- webapp/src/app/shared/table-filters/table-filters.component.ts
- webapp/src/app/shared/table/table.component.html
- webapp/src/app/shared/table/table.component.ts
> fix: remove casing for mandatory tags

- webapp/src/app/post-login-app/common/contextual-menu/contextual-menu.component.ts
fixed contextual menu parent node expand bug
> fix:[CORE-1139] fixed contextual menu parent node expand bug

- jobs/job-scheduler/src/main/java/com/paladincloud/jobscheduler/service/JobScheduler.java
Fixed an issue with sending the event for the host asset data importer.
> fix: [CORE-1167] fixed bug in asset importer event

- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/service/SecurityService.java
Create revoke exemtion for user role.
> bug:[CORE-1148]create revoke exemption for user role

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
> bug:[CORE-1148]autofix schedule issue in violations

- webapp/src/app/pacman-features/modules/admin/account-management/account-management.component.ts
> fix: [UIUX-281] change status filter option from configured to online

- webapp/src/app/pacman-features/modules/admin/account-management/account-management.component.ts
- webapp/src/app/pacman-features/modules/assets/asset-list/asset-list.component.ts
- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.ts
- webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.ts
- webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase/policy-knowledgebase.component.ts
- webapp/src/app/pacman-features/modules/notifications/cloud-notifications/cloud-notifications.component.ts
1. Pre apply status filter
2. Refactored and optimised list view related methods in violations screen.
> feat: preapply status filter in violations screen

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/common/AdminConstants.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AbstractAccountServiceImpl.java
> bug:[CORE-1148]plugin status filter issue

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/controller/CloudNotificationsController.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/domain/Request.java
> fix:[Core-959] Set date according to the payload.

- README.md
> removed trynow from README.md

- installer/resources/pacbot_app/files/DB_Policy.sql
> fix:[CUS-180][CORE-1186][CORE-1097] update db enteries for policies.

- installer/resources/lambda_rule_engine/files/rule_engine_cloudwatch_plugin_rules.json
> fix:[CORE-1214]Fix policyUUID

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/FilterRepositoryImpl.java
> fix:[CORE-1069] CE sync

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/utils/PacmanUtils.java
> fix:[CORE-1230][CORE-1241][CORE-1242]Ops Alert

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/cloudfront/CloudfrontAuthorizedHTMLContentDistributionRule.java
> fix:[CORE-1231]Ops Alert

- webapp/src/app/pacman-features/modules/assets/asset-list/asset-list.component.ts
- webapp/src/app/pacman-features/modules/compliance/card/card.component.ts
- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.ts
- webapp/src/app/pacman-features/modules/compliance/issue-details/issue-details.component.ts
- webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.ts
- webapp/src/app/pacman-features/modules/compliance/policy-details/policy-details.component.css
- webapp/src/app/pacman-features/modules/compliance/policy-details/policy-details.component.html
- webapp/src/app/pacman-features/modules/compliance/policy-details/policy-details.component.ts
- webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase/policy-knowledgebase.component.ts
- webapp/src/app/pacman-features/modules/compliance/progress-bar-chart/progress-bar-chart.component.css
- webapp/src/app/pacman-features/modules/compliance/progress-bar-chart/progress-bar-chart.component.html
> refact: violations column names map code

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/domain/PolicyViolationDetails.java
- emailTemplates/pacman-v2-email-template/html.handlebars
> fix:[CORE-1227]Fix email values

- installer/resources/pacbot_app/files/DB_Policy.sql
> fix:[CORE-841]AWS resolutions links

- installer/resources/pacbot_app/files/DB_Policy.sql
Missing resolution links for GCP
> fix:[CORE-1135]GCP resolutions links

- installer/resources/pacbot_app/files/DB.sql
> bug:[CORE-1240]region filter url corrected

- installer/resources/pacbot_app/files/DB_Policy.sql
> fix:[CORE-1138]Azure Links

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/ComplianceServiceImpl.java
> bug:[CORE-1249]violation api failure

- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/file/AssetFileGenerator.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/ServerlessPolicyHandler.java
fix: gcp asset loadbalancer and cloudstorage mapping fix.
fix: handling serverless exception for non 200 response code.
> fix: gcp asset loadbalancer and cloudstorage mapping fix.

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/FilterRepositoryImpl.java
> bug:[CORE-1251]issues filter need to skip issues with unknown status.

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/repo/ElasticSearchRepository.java
region filter breaks due to no data present for some asset types.
> bug:[CORE-1257]region sort breaks

- installer/resources/pacbot_app/files/DB.sql
> bug:[CUS-183]correcting asset api download endpoint

- installer/resources/pacbot_app/files/DB.sql
> bug:[CORE-1265]severity fails when autofix is true

- installer/resources/pacbot_app/files/DB.sql
download api endpoint correcttion
> bug:[CUS-191]download api endoint

- installer/resources/pacbot_app/files/DB_Policy.sql
Missing resolution links for AWS,GCP and Azure
> fix:[CORE-1138][CORE-1135][CORE-841]Missing resolution Links

- installer/resources/pacbot_app/files/DB_Policy.sql
> fix:[CUS-179]Updated policy description

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/controller/DownloadController.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/domain/DownloadRequest.java
- api/pacman-api-compliance/src/test/java/com/tmobile/pacman/api/compliance/controller/DownloadControllerTest.java
- api/pacman-api-compliance/src/test/java/com/tmobile/pacman/api/compliance/util/CommonTestUtil.java
> bug:[CUS-192]download api failure

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepositoryImpl.java
> fix:Sorted TargetType List on DisplayName field

- installer/resources/pacbot_app/files/DB.sql
> fix:[Core-1015] Added cloud Type in Duplicate DisplayName.

- installer/resources/eventbus/custom_event_bus.py
- installer/resources/lambda_submit/function.py
- installer/resources/pacbot_app/files/DB.sql
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/error/DefaultErrorManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/error/ErrorManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/es/ESManager.java
Added RedHat Plugin Type in Shipper and added new target type "Deployment". 
modified installer to create RedHat Shipper job.
> feat:[PLG-150] RedHat Deployment asset 

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/FilterServiceImpl.java
> fix:[CORE-1263] CE Sync

- webapp/src/app/pacman-features/modules/admin/policies/policies.component.ts
> fix: sorted filter options irrespective of case

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/azurerules/KeyValts/AdministrativeLevelPermisionsRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/azurerules/KeyValts/KeyVaultsRule.java
> fix:[CORE-1274][CORE-1275][CORE-1277][CORE-1276]Ops alert

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/Constants.java
Issue audit log should capture request exemption and revoke request from user
> fix:[CORE-760]Issue audit log captures request and revoke request

- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/PacmanSdkConstants.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/policy/BasePolicy.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/iam/CheckIamPasswordPolicyRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/iam/IAMAccessGrantForNonAdminAccountRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/utils/IAMUtils.java
Retry thrice for a resource incase 'rate exceeded' error is thrown.
> fix:[CORE-1201] Fix for rate exceeded issue

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/Constants.java
Issue audit log captures grant and deny request exemption
> fix:[CORE-760]Issue audit log captures grant and deny request exemption

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/azurerules/DiskRule/DeleteUnusedDiskRule.java
> fix:[CORE-1288] fix for remove unused vm disk rule

- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/repo/ElasticSearchRepository.java
> fix:[CORE-1058] CE Sync

- installer/resources/lambda_rule_engine/files/rule_engine_cloudwatch_azure_rules.json
- installer/resources/lambda_rule_engine/files/rule_engine_cloudwatch_gcp_rules.json
> fix:Added Policy UUID in rule_engine_cloudwatch

- installer/resources/lambda_rule_engine/files/rule_engine_cloudwatch_azure_rules.json
- installer/resources/lambda_rule_engine/files/rule_engine_cloudwatch_gcp_rules.json
> fix:Added UUID in rulengine.json

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/VirtualMachineScaleSetCollector.java
> fix:VM_ScaleSet collector

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/VirtualMachineScaleSetCollector.java
> fix:VM ScaleSet collector.

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/KubernetesServicesCollector.java
> fix:[CORE-000] fix for NPE in azure kubernetes services collector

- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/DiskInventoryCollector.java
> fix:[CUS-217] Gcp Disks Collector.

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/controller/FilterController.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/domain/FilterRequest.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/FilterRepository.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/FilterRepositoryImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/FilterService.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/FilterServiceImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/repo/ElasticSearchRepository.java
> fix:[CORE-1239]Search in violation filter

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/enums/PolicyComplianceFilter.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/ComplianceServiceImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/FilterServiceImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/Constants.java
- installer/resources/pacbot_app/files/DB.sql
> bug:[CORE-978]autofix filter

- installer/resources/pacbot_app/files/DB.sql
feat: [PLG-174],[PLG-175] Added Node and Cluster asset
Fixes # [PLG-174],[PLG-175] 
[PLG-174]: https://paladincloud.atlassian.net/browse/PLG-174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PLG-175]: https://paladincloud.atlassian.net/browse/PLG-175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PLG-174]: https://paladincloud.atlassian.net/browse/PLG-174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ …
> feat: [PLG-174],[PLG-175] Added Node and Cluster asset

- installer/resources/iam/lambda_role.py
- installer/resources/lambda_plugins/function.py
- installer/resources/pacbot_app/files/DB.sql
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/Main.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/dao/RDSDBManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/dto/PolicyTable.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/EntityManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/ExternalPolicies.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/ViolationAssociationManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/es/ESManager.java
Feat: [PLG-63] [PLG-162] [PLG-152] Added Violation, Polices and Images assets in shipper
Fixes # ([PLG-63] [PLG-162] [PLG-152])
[PLG-63]: https://paladincloud.atlassian.net/browse/PLG-63?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PLG-162]: https://paladincloud.atlassian.net/browse/PLG-162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PLG-63]: https://paladincloud.atlassian.net/browse/PLG-63?atlOrigin=eyJpIjoiNWRkNTljNzYxN …
> Feat: [PLG-63] [PLG-162] [PLG-152] Added Violation, Polices and Images assets in shipper

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/VaultInventoryCollector.java
Violation should not be raised when permission not given for key vaults
> fix:[CORE-1290]Violation should not be raised when permission not given

- installer/resources/pacbot_app/files/DB_Policy.sql
> fix:[CORE-1298][CORE-1300] Policy Sort by fixing the displayName.

- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/ProjectInventoryCollector.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/file/AssetFileGenerator.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/projectRules/EnableOSLoginProjectLevelRule.java
1. Fix for cequence gcp data dog alerts.
> fix:[CORE-1348] fix for data ops alerts for cequence

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AbstractAccountServiceImpl.java
- installer/resources/pacbot_app/files/DB.sql
> fix:[CORE-1385] changed Platfrom and CloudType to Source.

- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/file/FileManager.java
> fix:[CUS-170] added region in keys.

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/iam/CustomerMangdPolicyWithAdminPrevilegeRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/iam/IAMRoleWithUnapprovedAccessRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/azurerules/Kubernetes/EnableClusterMonitoring.java
1. Fix for 5 data dog alerts of vertex.
> fix:[CORE-1391] Fix for data dog alert issues reported for vertex

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AssetGroupServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AssetGroupTargetDetailsService.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AssetGroupTargetDetailsServiceImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/repo/ElasticSearchRepository.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/repo/PacmanRdsRepository.java
[PLG-232]
[PLG-232]: https://paladincloud.atlassian.net/browse/PLG-232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat:[PLG-232] Changes for including redhat source in assetgroup creation

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/Main.java
> fix:[PLG-186]adding try catch block along with more log messages

- README.md
Updated release number
added a link to discord channel
> Update README.md with new release

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepositoryImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/ComplianceServiceImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/FilterServiceImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/Constants.java
> bug:[CORE-000]ce porting 981, 984, 990

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/s3/S3GlobalAccessRule.java
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/util/InventoryUtil.java
Policy is failing when region is not set
> fix:[CORE-1204]s3 policy fix

- installer/files/scripts/build_pacbot.py
- installer/resources/pacbot_app/build_ui_and_api.py
- installer/settings/common.py
- webapp/src/config/configurations.ts
> chore:[CORE-974]Notification Duration

- installer/resources/lambda_submit/function.py
- installer/settings/common.py
Target Id fix for longrunning job lambda
Release version Update v3.0.1
> Chore:Target Id fix for longruninng job lambda

- webapp/src/app/pacman-features/modules/compliance/card/card.component.ts
> fix: apply open violations on clicking category

- jobs/pacman-rule-engine-2.0/cloudresources/lambda/pac_submit_batch_job.py
> fix:[PLG-181]Lambda changes for Triggering GCP Shipper Job by SQS Event

- installer/resources/pacbot_app/files/DB_Policy.sql
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/autofix/gcp/vpcnetwork/VpcNetworkPortAutofix.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/commons/autofix/manager/AzureAutofixManager.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/commons/autofix/manager/GcpAutofixManager.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/util/CloudUtils.java
1. Fix issues related to autofix of gcp.
> fix:[CORE-901] resolve issues for autofix of gcp

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
> bug:[CORE-1171]exemption revoke flow

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/auth/AWSCredentialProvider.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/Main.java
Cleaned up some sensitive and useless logs in Data Shipper code
> Cleanup some sensitive logs in data shipper

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetServiceImpl.java
> bug:[CORE-1414]attributes for ec2

- webapp/src/app/pacman-features/modules/compliance/issue-details/issue-details.component.html
- webapp/src/app/pacman-features/modules/compliance/issue-details/issue-details.component.ts
> fixed grant and deny buttons for admin

- webapp/src/app/pacman-features/secondary-components/tagging-instances-table/tagging-instances-table.component.ts
> fix:[CORE-1150] untagged assets by app broken links

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/Main.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/EntityManager.java
> fix:[PLG-181] shipper override source changes review comments

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/NotificationServiceImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/NotificationServiceImpl.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/utils/IAMUtils.java
1. Added retry mechanism for a method which is throwing rate exceeded problem in IAMUtils.java
> fix:[CORE-1445] fix for rate exceeded problem in IAMUtils method

- jobs/job-scheduler/src/main/java/com/paladincloud/jobscheduler/service/DataCollectorSQSService.java
- jobs/job-scheduler/src/main/java/com/paladincloud/jobscheduler/util/Constants.java
Lambda environment field name changes  
> fix: [PLG-248] Modified installer environment field names

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/AzureFetchOrchestrator.java
- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/GCPFetchOrchestrator.java
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/InventoryFetchOrchestrator.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/Main.java
> fix:[PLG-181]revert shipper changes for overridesrcpaath/backup

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/cloudsql/DisableOrEnableDBFlagsRule.java
Database flags should be handled when its null
> fix:[CORE-1460]Database Flags handled

- jobs/job-scheduler/src/main/java/com/paladincloud/jobscheduler/service/DataCollectorSQSService.java
- jobs/job-scheduler/src/main/java/com/paladincloud/jobscheduler/util/Constants.java
> fix:[PLG-248] added tenant id from env

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/Main.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/EntityManager.java
> fix:[PLG-181]Shipper changes for Fetching s3.data from System env variable

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/cloudsql/DisableOrEnableDBFlagsRule.java
Ops alert issue for database flags
> fix:[CORE-1460]Database flags ops issue

- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/utils/NotificationPermissionUtils.java
After adding security to lambda function using cloud api gateway, need to add access token to resolve unauthorised exception
> fix:[CORE-1401]Access token added for notification

- jobs/pacman-data-shipper/pom.xml
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/AWSErrorManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/EntityAssociationManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/EntityManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/ExternalPolicies.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/ViolationAssociationManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/util/Util.java
> PLG-181-Violation Count fix -Shipper testing along with adding redhat shipper dependency

- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/utils/NotificationPermissionUtils.java
After adding security to lambda function using cloud api gateway, need to add access token to resolve unauthorised exception
> fix:[CORE-1401]Access token added

- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/InventoryFetchOrchestrator.java
> uncommenting backup codes

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/Main.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/dao/RDSDBManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/ViolationAssociationManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/util/Constants.java
[PLG-267] : Shipper changes
update log for error handling and fix Policy not displaying in audit log.
[PLG-267]: https://paladincloud.atlassian.net/browse/PLG-267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PLG-267] : Shipper changes

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/controller/ActivityLoggingController.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/domain/ActivityLogRequest.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetServiceImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/repo/ElasticSearchRepository.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/utils/CommonUtils.java
> bug:[CORE-1171]activity logging api changes

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/cloudstorage/DisableDBOwnerRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/cloudstorage/DisableExternalScriptsEnabledFlagRule.java
Database flags ops alert issue
> fix:[CORE-1468]Ops alert fix

- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/config/ConfigUtil.java
- jobs/job-scheduler/src/main/java/com/paladincloud/jobscheduler/config/ConfigUtil.java
- jobs/pacman-aqua-enricher/src/main/java/com/tmobile/cso/pacman/aqua/util/ConfigUtil.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/util/ConfigUtil.java
That config contains sensitive data such as password to DB. Why it's even been there?
> Removed printing whole config into logs

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/dto/PolicyTable.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/util/ConfigUtil.java
> adding URL to policy on shipment

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/dao/RDSDBManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/dto/PolicyTable.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/ExternalPolicies.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/util/Constants.java
> changing policy url to resolutionUrl

- installer/resources/pacbot_app/files/DB.sql
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/EntityManager.java
Making the attribute preserving from existing assets as a configurable parameter.
> fix: [CORE-1481] Preserving the attributes form current assets

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/ViolationAssociationManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/util/Util.java
fix:[PLG-272] Date issue in audit log.
[PLG-272]: https://paladincloud.atlassian.net/browse/PLG-272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix:[PLG-272] Date issue in audit log.

- installer/resources/pacbot_app/files/DB_Policy.sql
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/azurerules/SecurityPricing/SecurityPricingRule.java
> fix:[CORE-1403] fixed security Pricing Policies.

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/FilterServiceImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/Constants.java
> fix:[CORE-1455] Autofix filter in User Policies.

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/controller/TargetTypesController.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/domain/AttributeValuesRequest.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/enums/AssetGrpAttributeIndex.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/TargetTypesService.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/TargetTypesServiceImpl.java
> fix:[CORE-1448] Updated methods to get accounts data in Autofix.

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/enums/PolicyComplianceFilter.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/ComplianceServiceImpl.java
> fix:[CORE-1452] Removed NR data when Compliance is set to 100 %.

- installer/resources/pacbot_app/files/DB_Policy.sql
> fix:[CORE-1417] Updated Policy Link.

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/ErrorManageUtil.java
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/file/ErrorManageUtil.java
> fix:Comment notification for collectors

- installer/resources/pacbot_app/files/DB.sql
Ars is showing as 0 for gcp and azure after shipper ran.
> fix:[CORE-1504] fix for ars showing as 0 after shipper ran

- installer/resources/pacbot_app/files/DB.sql
> chore:SQL check fix

- installer/resources/pacbot_app/files/DB.sql
Duplicate entry is getting created for attributes.preserve attribute in pac_config_properties. Deleting and recreating the attribute.
> fix:[CORE-000] update attributes.preserve config variable in db script

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/AssetConstants.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetServiceImpl.java
> fix:[CORE-1520]-Source Display Name for Asset Group details -OSS release 

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/BlobContainerInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/BlobServiceInventoryCollector.java
Blob storage is not supported for File storage account
> fix:[CORE-1491]Feature not supported for file storage

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/LoadBalancerInventoryCollector.java
Fix for load balancer collector in azure for vertex
> fix:[CORE-1490]Load balancer fix for vertex azure collector

- webapp/src/app/pacman-features/modules/admin/account-management/add-account/add-account.component.html
- webapp/src/app/pacman-features/secondary-components/pacman-policy-violations/pacman-policy-violations.component.ts
- webapp/src/config/configurations.ts
> fix:sort in asset details associated policies

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/AssetConstants.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetServiceImpl.java
> fix:[CORE-1520]AssetGrp Display OSS fix

- installer/resources/lambda_submit/function.py
- installer/resources/lambda_submit/s3_upload.py
> chore:Lambda path fix for data colletor lambda

- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/jobs/TenableVMVulnerabilityDataImporter.java
Forgot to change it in the main PR
> Changing export status check from 20 sec to 120 sec.

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/config/ConfigManager.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/config/ConfigManager.java
- lambda-functions/notification-es-logging-service/src/main/java/com/paladincloud/notification_log/config/ConfigManager.java
> Remove sensitive data from logs

- installer/resources/pacbot_app/alb_https_listener.py
- installer/resources/pacbot_app/files/ui_docker/nginx.conf
1. Update SSL policy 
2. Added Missing headers
> Chore:[DEVOPS-117][DEVOPS-118]updated ssl policy and added missing Headers

- installer/resources/pacbot_app/files/DB.sql
Incorrect asset count due to launcTemplate assetType since it is a "finding", updating the status with the same in database.
> bug:[CORE-1442]update launchtemplate as finding in database

- installer/resources/pacbot_app/files/DB.sql
> chore:disabling-redhat assetgroup

- installer/resources/pacbot_app/files/DB.sql
> bug:[CORE-1442]update securitypricings as finding in database

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/es/ESManager.java
Add logger statements for new methods.
> fix:[CORE-1345] add logger statements

- installer/resources/lambda_rule_engine/files/rule_engine_cloudwatch_aws_rules.json
> fix:[CORE-1552] Added Policy UUID in rule Engine.json.

- installer/resources/pacbot_app/files/DB_Policy.sql
> fix:[CORE-1530][CORE-1553] Updated Policies Parameters.

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/es/ESManager.java
1. Add new asset types to relevant asset groups. This is the second commit related to ticket - 1345. Actual feature is committed in first commit. Identified and fixed a bug in this commit.
> fix:[CORE-1345] add new asset types to relevant asset groups

- jobs/pacman-aqua-enricher/src/main/java/com/tmobile/cso/pacman/aqua/Constants.java
- jobs/pacman-aqua-enricher/src/main/java/com/tmobile/cso/pacman/aqua/Main.java
- jobs/pacman-aqua-enricher/src/main/java/com/tmobile/cso/pacman/aqua/MainUtil.java
- jobs/pacman-aqua-enricher/src/main/java/com/tmobile/cso/pacman/aqua/auth/CredentialProvider.java
- jobs/pacman-aqua-enricher/src/main/java/com/tmobile/cso/pacman/aqua/dto/ImageVulnerabilityResponse.java
- jobs/pacman-aqua-enricher/src/main/java/com/tmobile/cso/pacman/aqua/dto/Result.java
- jobs/pacman-aqua-enricher/src/main/java/com/tmobile/cso/pacman/aqua/exception/AquaDataImportException.java
- jobs/pacman-aqua-enricher/src/main/java/com/tmobile/cso/pacman/aqua/exception/UnAuthorisedException.java
- jobs/pacman-aqua-enricher/src/main/java/com/tmobile/cso/pacman/aqua/jobs/AquaDataImporter.java
- jobs/pacman-aqua-enricher/src/main/java/com/tmobile/cso/pacman/aqua/jobs/AquaFunctionVulnerabilityDataImporter.java
- jobs/pacman-aqua-enricher/src/main/java/com/tmobile/cso/pacman/aqua/jobs/AquaImageVulnerabilityDataImporter.java
- jobs/pacman-aqua-enricher/src/main/java/com/tmobile/cso/pacman/aqua/jobs/AquaVMVulnerabilityDataImporter.java
- jobs/pacman-aqua-enricher/src/main/java/com/tmobile/cso/pacman/aqua/util/ElasticSearchManager.java
- jobs/pacman-aqua-enricher/src/main/java/com/tmobile/cso/pacman/aqua/util/ErrorManageUtil.java
- jobs/pacman-aqua-enricher/src/main/java/com/tmobile/cso/pacman/aqua/util/HttpUtil.java
- jobs/pacman-aqua-enricher/src/main/java/com/tmobile/cso/pacman/aqua/util/Util.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/Constants.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/Main.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/MainUtil.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/auth/CredentialProvider.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/dto/ExportStatus.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/exception/TenableDataImportException.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/exception/UnAuthorisedException.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/jobs/TenableDataImporter.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/jobs/TenableVMVulnerabilityDataImporter.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/util/ConfigUtil.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/util/ElasticSearchManager.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/util/ErrorManageUtil.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/util/HttpUtil.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/util/Util.java
Updated copyright for Aqua and tenable, Aqua cleaned up further
ONLY cosmetical changes!
No need to test
> Updated copyrights for Tenable and Aqua

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/Main.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/AssetGroupStatsCollector.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/AssetsCountManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/DatasourceDataFetcher.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/IssueCountManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/util/AssetGroupUtil.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/util/HttpUtil.java
- jobs/pacman-data-shipper/src/test/java/com/tmobile/cso/pacman/datashipper/entity/AssetGroupStatsCollectorTest.java
- jobs/pacman-data-shipper/src/test/java/com/tmobile/cso/pacman/datashipper/util/AssetGroupUtilTest.java
Implement Base URL Generation for Microservices in Shipper Service
[PLG-318] 
[PLG-318] 
in-order to test the changes, I've deleted the redhat related data from assetgroup_stats index and made count of assets and violations as 0
then ran shipper with latest changes, and the data got updated successfully 
[PLG-318]: https://paladincloud.atlassian.net/browse/PLG-318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PLG-318]: https://paladincloud.atlassian.net/browse/PLG-318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat:[PLG-318] Implement Base URL Generation for Microservices

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/es/ESManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/util/AssetGroupUtil.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/util/HttpUtil.java
- jobs/pacman-data-shipper/src/test/java/com/tmobile/cso/pacman/datashipper/entity/EntityAssociationManagerTest.java
- jobs/pacman-data-shipper/src/test/java/com/tmobile/cso/pacman/datashipper/es/ESManagerTest.java
- jobs/pacman-data-shipper/src/test/java/com/tmobile/cso/pacman/datashipper/util/AssetGroupUtilTest.java
> fixing shipper tests

- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/gcprules/cloudfunctions/HttpTriggersTest.java
Testing Sample Policy**(Enable-Https-For-Cloudfunc)** related to **gcp-Cloud Function assetType** using Mapper Generated data since legacy collector did not collect the data for Gcp-CloudFunction for long time. So we want to test the sample policy by mocking them.
- In Junit file Mocked data which we will get during policy Execution as part of _soruce attribute from Elastic Search. Shipper will upload Mapper generated json to Elastic Search in **gcp_cloudfunction** index. So same json will get fetched during policy eexution. So I am mocking the same.
List any …
> fix:[PLG-316]Testing Sample Policy for GCP-CloudFunction Using Mapper Generated Json

- installer/resources/pacbot_app/files/DB.sql
> fix:[CORE-1590] Updated Option Url .

- .github/workflows/SonarCodeAnalysis.yaml
- .github/workflows/codeQl.yaml
> chore:[DEVOPS-163]increased heap size

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/ErrorManageUtil.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/WebAppInventoryCollector.java
Ops alert should not be raised for webapp AuthorisationFailed error
> fix:[CORE-1495] Permission issue for webapp

- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/dto/PermissionVH.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/utils/NotificationPermissionUtils.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/ErrorManageUtil.java
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/file/ErrorManageUtil.java
- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/jobs/HostAssetDataImporter.java
- lambda-functions/notification-template-formatter-service/src/main/java/com/paladincloud/FetchNotificationSettings.java
- lambda-functions/notification-template-formatter-service/src/main/resources/permissionAlertEmailTemplate.html
Lesser notifications for AWS collector
Commented for qualys since more changes are required after merging optimised code
> [CORE-1515]:Less notifications to reduce CPU spike

- installer/resources/pacbot_app/files/DB_Policy.sql
> fix:[CORE-1588] changed severity to high.

- jobs/job-scheduler/src/main/java/com/paladincloud/jobscheduler/service/JobScheduler.java
To enable Scheduler to trigger GCP CQ Job (test-gcp-collection)
Tested by running JobScheduler through my local enviroment and checking gcp-data-collection job is getting triggered or not .
> Fix:[PLG-322]Enabling GCP-PluginScheduler Code changes

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/ErrorManageUtil.java
Forbidden by firewall error should be notified to user
> fix:[CORE-1494] Azure vaults firewall issue

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/VMsWithSeverityVulnerabilityRule.java
Fixed "Tenable Found xxxx Vulnerabilities On EC2 Instance" policies.
TBH, policy was completely broken and checking only "low" severity, when in reality expected to check all other except "low" and "info"
Now policies scan for all severities of vulns
This current list of issues with tested VM (severity has been adjusted in our OpenSearch in order to have vulns for every type of severity)
Example of critical:
Example of High:
Example of Medium:
Then I removed critical vuln and critical violation has gone:
> [PLG-325] Fixed "Tenable Found xxxx Vulnerabilities On EC2 Instance" policies

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/ActivityLogsCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/SubnetInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/VirtualMachineScaleSetCollector.java
1. Fixed NPE by adding null check in subnet collector of azure.
2. Incase azure.alertRules().activityLogAlerts().list() throw null pointer exception, let us return empty list. We need not publish data alert in this case because it is the internal method azure apis.
Tested locally.
> fix:[CORE-1489] fix for subnet collector of azure data collector

- installer/settings/common.py
Increment version of lambda function to see changes in formatter service
> fix:[CORE-1515] Increment lambda version

- installer/resources/pacbot_app/files/DB.sql
removing update query for redhat
> removing update query for redhat

- installer/resources/pacbot_app/files/DB.sql
remove update query for redhat assetgroup
[CORE-1609]
[CORE-1609]: https://paladincloud.atlassian.net/browse/CORE-1609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore:[CORE-1609] remove update query for redhat asset group

- api/pacman-api-compliance/pom.xml
- api/pacman-api-config/pom.xml
- api/pacman-api-notifications/pom.xml
- api/pacman-api-statistics/pom.xml
- api/pacman-api-vulnerability/pom.xml
- commons/pac-batch-commons/pom.xml
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/PacmanSdkConstants.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/aws/CredentialProvider.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/azure/clients/AzureCredentialProvider.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/config/ConfigUtil.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/config/Util.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/dao/RDSDBManager.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/dto/NotificationBaseRequest.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/dto/PaladinAccessToken.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/dto/PermissionNotificationRequest.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/dto/PermissionVH.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/gcp/clients/GCPCredentialsProvider.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/secrets/AwsSecretManagerUtil.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/utils/CommonUtils.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/utils/Constants.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/utils/NotificationPermissionUtils.java
- jobs/job-scheduler/pom.xml
- jobs/pacman-awsrules/pom.xml
- jobs/pacman-cloud-notifications/pom.xml
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/common/PacmanSdkConstants.java
- lambda-functions/notification-es-logging-service/pom.xml
Starting cleanup for common libs. Goal is to:
* reduce size of the compiled files
* number of unused libs
* reduce code duplication
Logic has not been changed. Some constants are moved.
Ran build for batch-commons specifically and for the whole project.
`mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V`
Results of the build:
> [Work in progress]Batch commons project cleanup (the beginning)

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/common/AdminConstants.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/config/AppConfig.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/controller/AccountsController.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/domain/DataCollectorSQSMessageBody.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/domain/GcpPluginRequest.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/domain/PluginParameters.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/domain/RedHatPluginRequest.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/exceptions/PluginServiceException.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AbstractPluginService.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/DataCollectorSQSService.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/GcpPluginServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/PluginsService.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/RedHatPluginServiceImpl.java
CQ GCP Plugin API changes
[PLG-317]
[PLG-317]: https://paladincloud.atlassian.net/browse/PLG-317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat:[PLG-317] CQ GCP Plugin API changes

- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/commons/autofix/manager/IAutofixManger.java
Remove unused imports from IAutofixManager.java file.
> fix:[CORE-000] remove unused imports from IAutofixManager.java

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/controller/AccountsController.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/exceptions/PluginNotFoundException.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/factory/PluginFactory.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AbstractPluginService.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/GcpPluginServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/RedHatPluginServiceImpl.java
Code refactoring
Implement Dynamic Service and Request Class Handling
Testing CE repo with saasdev env
1. Validate API
2. Delete API
3. Create API
> feat:[PLG-329] Implement Dynamic Service and Request Class Handling

- installer/resources/pacbot_app/files/DB_Policy.sql
> fix:[CORE-1630] Update severity to high.

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/ErrorManageUtil.java
Send only 1 notification email for insufficient permission for Azure
[AzureMail - Insufficient permissions.pdf](https://github.com/PaladinCloud/CE/files/13164500/AzureMail.-.Insufficient.permissions.pdf)
> fix:[CORE-1494] Get notification email for Azure

- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/utils/NotificationPermissionUtils.java
- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/jobs/HostAssetDataImporter.java
- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/util/ErrorManageUtil.java
Notification email for qualys authorization
> fix:[CORE-1389] Get notification email for Qualys

- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/Main.java
- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/util/ErrorManageUtil.java
Added logger statements in qualys to debug the data alert issue.
> fix:[CORE-000] add logger statements to qualys-kb collector

- webapp/src/app/pacman-features/modules/admin/account-management-details/account-management-details.component.ts
- webapp/src/app/pacman-features/modules/admin/account-management/add-account/add-account.component.ts
1. Updated end point and payload for gcp plugin.
> fix:[PLG-236] updated end point for gcp plugin

- webapp/src/app/pacman-features/modules/assets/asset-dashboard/asset-dashboard.component.ts
- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.ts
- webapp/src/app/shared/services/utils.service.ts
1. Fixed error messages in asset summary and compliance dashboard trend graphs.
> fix:[CORE-1294] fixed error messages in asset summary, dashboard trendgraphs

- jobs/pacman-data-shipper/pom.xml
This changes are already in place in saasdev and already working as part of PLG-287. Moving same PR to release branch
Changes are already working at SAASDEV. Releasing this to release branch
> fix:[PLG-287]Move PR to release BR 

- installer/settings/common.py
> release update 3.0.2

- installer/resources/cognito/function.py
- installer/resources/lambda_plugins/function.py
- installer/resources/lambda_rule_engine/function.py
- installer/resources/lambda_submit/function.py
- installer/resources/notification/function.py
Updated lambda runtime
from python3.8 ---> python3.11
from java8 and java11 -- > java17
> chore:[DEVOPS-166][DEVOPS-160]lambda runtime update

- webapp/src/app/pacman-features/modules/assets/asset-distribution/asset-distribution.component.ts
Fixed hover issue in asset distribution
> fix:[CORE-1608]fixed asset distribution hover issue

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/azurerules/DiskRule/CheckDiskEncryption.java
Null pointer exception fix for Azure policy--> Encrypt Unattached Disk Volumes
> fix:[CORE-1613] Null pointer exception fix

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/AzureFetchOrchestrator.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/ErrorManageUtil.java
Notify when azure collector is unable to collect data due to the below error
com.microsoft.aad.adal4j.AuthenticationException: {"error":"unauthorized_client","error_uri":"https:\/\/login.microsoftonline.com\/error?code=700016"}
> fix:[CORE-1412] Notification for cequence azure collector

- webapp/src/app/pacman-features/modules/admin/policies/policies.component.html
- webapp/src/app/pacman-features/modules/admin/policies/policies.component.ts
- webapp/src/app/shared/constants/data-mapping.ts
- webapp/src/app/shared/services/filter-management.service.ts
- webapp/src/app/shared/services/utils.service.ts
- webapp/src/app/shared/table/interfaces/table-filters.interface.ts
- webapp/src/environments/environment.prod.ts
- webapp/src/environments/environment.stg.ts
- webapp/src/environments/environment.ts
Made list view and filters related methods generic and applied those methods in admin policies.
And added following:
1. Dynamic filters
2. Enhanced Filters (Multiple Filters selection)
3. Lazy loading of data
4. Server side sort
> feat:[UIUX-261]integrated enhanced filters, lazy loading, server side sort in admin policies

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/azurerules/DiskRule/CheckDiskEncryption.java
Vertex policy fix for null pointer exception
> fix:[CORE-1613] Release branch

- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/Main.java
- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/jobs/Util.java
- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/util/ErrorManageUtil.java
Qualys asset data importer is throwing data alert because of issue in scroll api. Resolved issue with necessary changes.
> fix:[CORE-1546] fix for scroll api in qualys asset data importer job

- installer/resources/pacbot_app/files/DB.sql
Commented out filter inserts for plugin screen to fix ui break due to enhanced filter changes.
> bug:[CORE-1334] quick fix for plugin filter break.

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/EntityManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/util/Constants.java
This is nothing but replica of https://github.com/PaladinCloud/CE/pull/1782 
> fix:[PLG-352]AccName fix for relase branch

- installer/settings/common.py
> Release v3.0.3

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/AccountsRepository.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AbstractAccountServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/TenableAccountServiceImpl.java
[PLG-346] Tenable API fix/feature, related services moved into separate folder
* Very light refactoring for Abstract account service implementation
Also moved all related code into separate folder for convenience
* Starting fixing
* Small fixes
* Continue with account service refactoring
* Extracted secretId method.
* Fix
* Check if similar account is being deleted. Fail in such cases
* Message changed
list any relevant details for your test …
> [PLG-346] Tenable API fix/feature, related services moved into separate folder

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/es/ESManager.java
Implement Dynamic Shipper Handler to accommodate future plugins
Removed hardcoded values
Only updates the affected asset groups
updates user asset groups if alias query is null
> feat:[PLG-337] Implement Dynamic Shipper Handler to accommodate future plugins

- installer/resources/pacbot_app/files/DB.sql
> fix:Revert db changes.

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/EntityManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/util/Constants.java
This is nothing but releasing same **PR to v1.2.1 release branch**
> fix:[PLG-352]AccName release branch PR

- installer/resources/pacbot_app/files/DB.sql
Database inserts for filters in plugin, asset groups and policy offer
> bug:[CORE-1334] database inserts for filters

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/APIKeys/ConfigureApiRestriction.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/APIKeys/EnableAPIApplicationRestriction.java
This is nothing but same PR for release branch
> fix:[PLG-358]PR for release Branch V1.2.2

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/cloudstorage/CloudStorageWithPublicAccessRule.java
This is replica PR of PLG-367 to release branch
> [PLG-367]PR to Release branch v1.2.2

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/cloudfunctions/IngressSettingRule.java
This is replica PR for https://github.com/PaladinCloud/CE/pull/1811
All test results please refer original PR
> fix:[PLG-370]PR to Release Branch

- installer/resources/pacbot_app/files/ui_docker/dockerfile
updated GPG_KEYS where the old gcp_key got expired and was unable to build docker image
This is impacting while we are onboarding new Tenant's
> chore:[Devops-191] gpg key updated

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/s3/CheckMFADeleteEnabledRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/s3/S3GlobalAccessRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/utils/S3PacbotUtils.java
No such bucket found exception occurs when s3 bucket is deleted but policy is trying to access the bucket using AWS client. In this case, exception should be handled and status is unknown
Steps to test :
1. Create a s3 bucket in saasdemo account with any  name like "testnosuchbucket"
2. Run AWS data collector and shipper to get the latest s3 bucket data
3. Delete the bucket ("testnosuchbucket")
4. Run policies where AWS client is used to get details of S3 bucket. Policy uuid are : 
-   aws_s3_should_not_be_publicly_accessible
-   s3_mfa_delete_enabled
> fix:[CORE-1662] s3 bucket deleted while running policy

- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/file/ErrorManageUtil.java
Send notification when role is not given to collector for AWS
1. Remove sts role from IAM Roles. Remove highlighted section in screenshot
2. Run AWS collector from local
> fix:[CORE-1635] Notification for spectro cloud aws collector

- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.ts
- webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase/policy-knowledgebase.component.ts
- webapp/src/app/post-login-app/default-asset-group/default-asset-group.component.ts
Going from dashboard to user policies and then switching asset group leads to dashboard APIs getting called.
This issue occured because of not unsubscribing the agDomainSubscription in Dashboard and Policies. 
> fix: fixed memory leak in user policies and dashboard

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetServiceImpl.java
> fix:[CORE-1687] asset details api fix

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/s3/CheckMFADeleteEnabledRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/s3/S3GlobalAccessRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/utils/S3PacbotUtils.java
S3 bucket does not exist exception handled
> fix:[CORE-1662] Bucket does not exist exception handled

- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/file/ErrorManageUtil.java
Send notification when role is not given to collector for AWS
> fix:[CORE-1635] Notification when AWS not given role

- installer/resources/pacbot_app/files/DB.sql
Database inserts for admin policy filters. 
> bug:[CORE-1689] database inserts for admin policy

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/controller/AccountsController.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/domain/CreateAccountRequest.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AbstractAccountServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/ContrastAccountServiceImpl.java
- installer/resources/pacbot_app/files/DB.sql
[PLG-308] contrast API changes
[PLG-308]: https://paladincloud.atlassian.net/browse/PLG-308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat:[PLG-308] contrast API changes

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/cloudstorage/CloudStorageWithPublicAccessRule.java
This is nothing replica of original PR 
https://github.com/PaladinCloud/CE/pull/1842/files
> fix:[PLG-374]Release Branch PR

- installer/resources/pacbot_app/files/DB.sql
Database inserts for plugin screen, ui andbackend changes have been deployed
> bug:[CORE-1689] database inserts for plugin

- installer/resources/pacbot_app/files/DB.sql
Database inserts for asset-group.
> bug:[CORE-1333] database inserts for asset-group

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/misc/CheckAWSConfigEnabled.java
OpsAlert -Null pointer exception fix
1.Enable AWS Config service
> Fix:[CORE-1670] Null pointer exception in policy

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/cloudfunctions/IngressSettingRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/cloudfunctions/VpnConnectorRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/utils/GCPUtils.java
GCP Cloud Function policies were throwing index out of bound exception. This was due to missing ES index which should be present in either as part of RuleParams(cf_PolicyParams table) or should be handled in Java Policy code as we do for other assetType. But this has been missed out. **As as result of that we were getting malformed ES url with null attached as suffix string at the end of ES URL**. I have handled this issue to produce proper ES url for cloud function assetType
**Step 1:Reproducing the Issue at my local**
Reproduced the issue at my local before fixes gets applied.Below are screenshots for the same.
**Step 2 : After fixing executing the policies and check ES Url is formed properly**
List any documentation updates …
> fix:[PLG-378]CloudFunction Policy Fix

- installer/resources/batch/job.py
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/file/ErrorManageUtil.java
This change is approved and merged to master via #1829. Raising to release branch.
> fix: [CORE-1303] Using regional endpoints for STS

- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/vo/SQS.java
The fields which are part of response and not present in the POJO resulted in unrecognised field error for SQS
1. Run AWS collector 
2. The below error should NOT occur
> fix:[CORE-1686] Unrecognized field error resolved

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/cloudfunctions/IngressSettingRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/cloudfunctions/VpnConnectorRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/utils/GCPUtils.java
This is nothing but replica PR of original PR associated with PLG-378 https://github.com/PaladinCloud/CE/pull/1854
> fix:[PLG-378]ReleaseBR PRs

- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/SingleThreadPolicyRunner.java
null Region issue after annotation is build as resource didn't have region param so usinf defaultRegion fro PolicyParams.
> Fix:[CORE-1670] null Region issue after annotation is build.

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/cloudfunctions/IngressSettingRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/cloudfunctions/VpnConnectorRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/utils/GCPUtils.java
This is nothing but release branch PR of  original PR of PLG-378
> fix:[PLG-378]Releasebranch v1.2.5

- installer/resources/pacbot_app/files/DB.sql
db insert correction for asset group column.
**BEFORE**
**AFTER**
Locally on ui.
> bug:[CORE-1333] database inserts for asset groups

- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/util/InventoryUtil.java
AWS is sharing their API with docdb and RDS services. Though we have separate clients for each of them, Aurora clusters are being returned with docdb client SDK.
Added an appropriate filter to return the correct docdb clusters.
> fix:[CUS-262] Added filter to fetch docdb clusters correctly

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/AssetGroupManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/es/ESManager.java
Checks every time for all-resources asset group if its created or not
if not created then it will create new asset group
> feat:[PLG-360] Checks every time for all-resources asset group if its created or not

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/vminstance/EnableConfidentialInstanceRule.java
**Enable_Confidential_Computing_for_Compute_Instance policy** thrown Null pointer exception(json null) due to confidentialComputing attribute being  null. This is for **cquence**
**Step 1: Reproducing the issue at my local before fix**
**Step 2 : After Fix**
> fix:[PLG-382]ConfidentialComputingJson Null fix

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/vminstance/EnableConfidentialInstanceRule.java
This is nothing but formatting the code fix done for PLG-382 https://github.com/PaladinCloud/CE/pull/1866/files
-
Already covered as part of original PR
> fix:[PLG-382]Formatting fix

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/vminstance/EnableConfidentialInstanceRule.java
This is replica PR of original PR https://github.com/PaladinCloud/CE/pull/1870/files
Already covered as part of original PR
https://github.com/PaladinCloud/CE/pull/1871
> fix:[PLG-382]Release Branch PR

- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/util/InventoryUtil.java
This is the release PR for #1874. This ignores the TA refresh check errors.
> fix:[CORE-1703] ignoring the TA refresh errors

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/AssetGroupManager.java
renaming display name and description
> feat:[PLG-360] renaming display name and description

- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/file/ErrorManageUtil.java
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/util/InventoryUtil.java
Some of the Trusted Advisor checks are not refreshable. AWS raising errors in such cases. We can ignore them as they are mostly for informational purposes.
Also, ignoring the DocDB error in regions where the DocDB service is unavailable.
Tested in SaaSDev by uploading the debug jar. Able to ignore TA and DocDB errors.
> Fix: [core-1703] TA check issues

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/AssetGroupManager.java
> feat:[PLG-360] renaming display name and description (#1886)

- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/file/ErrorManageUtil.java
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/util/InventoryUtil.java
This is the release PR for #1874.
> Fix/core 1703/ignoring check errors

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AssetGroupServiceImpl.java
> fix:[PLG-311] removed alias creation

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/APIKeys/RotateAPIKeysRule.java
This is replica PR of https://github.com/PaladinCloud/CE/pull/1796/files.
Already covered in Original PR.Also validated at SAASDEV post deployement at saasdev
1)Cloned the job Rotate_Google_Cloud_API_Keys-job-test-anand-nov28 
2)Verified for Unparseable Date exception
3) No exception is thrown
(https://github.com/PaladinCloud/CE/assets/138756904/b86956ab-dc25-4c51-ac0e-1189a8eab381)
> fix:[PLG-359]ReleaseBranch_V1.2.8 PR

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/AssetGroupManager.java
> feat:[PLG-360] SQL query updated for all-sources (#1876)

- webapp/src/app/pacman-features/modules/admin/user-management/user-management.component.ts
modified payload for roles API
> fix:[UIUX-488] modified payload for roles API

- installer/resources/pacbot_app/files/DB.sql
Feat: [PLG-385] Adding contrast library asset
[PLG-385]: https://paladincloud.atlassian.net/browse/PLG-385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feat: [PLG-385] Adding contrast library asset

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AbstractAccountServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AssetGroupService.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AssetGroupServiceImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/Constants.java
* feat:[PLG-362] Deletion of a plugin should be self contained
* changes related review comments
* changes related to review comments
cherry picked changes for release
[PLG-362]: https://paladincloud.atlassian.net/browse/PLG-362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat:[PLG-362] Deletion of a plugin should be self contained (#1885)

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/ErrorManageUtil.java
Remove asset type for checking ops alert
1. Run azure discovery job from local
2. Below email should be generated
[azureMail.pdf](https://github.com/PaladinCloud/CE/files/13558184/azureMail.pdf)
> fix:[CORE-1674] Remove asset type in azure notification

- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.ts
UIUX-523
When Violations by Severity + Top 10 Risks section is collapsed, the title is shown as "Category Compliance & Violations by Severity
https://paladincloud.atlassian.net/browse/UIUX-523
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] Unit testing
- [x ] My code follows the style guidelines of this project
- [x ] My commit message/PR follows the contribution guidelines of this project
- [x ] I have performed a self-review of my code
Bug : 
Fix: 
> fix: [UI/UX-523] [Dashboard] When Violations by Severity + Top 10 Risks section is collapsed

- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.ts
> Revert "fix: [UI/UX-523] [Dashboard] When Violations by Severity + Top 10 Risks section is collapsed"

- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/file/ErrorManageUtil.java
Omit Ops alert for Listener not found
Send email notification for : Access Denied and Authorization error
> fix:[CORE-1754] Omit ops and permission issue

- installer/resources/lambda_rule_engine/utils.py
- jobs/job-scheduler/src/main/java/com/paladincloud/jobscheduler/service/JobScheduler.java
Job scheduler changes for contrast policy
> feat:[PLG-392] Job scheduler changes for contrast policy (#1936)

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/controller/PolicyController.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/PolicyService.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/PolicyServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/accounts/AbstractAccountServiceImpl.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetServiceImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/controller/ComplianceController.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepository.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/ComplianceService.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/ComplianceServiceImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/PolicyTableServiceImpl.java
- api/pacman-api-config/src/main/resources/application.yml
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/repo/ElasticSearchRepository.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/utils/ListRequest.java
- installer/resources/pacbot_app/files/DB.sql
CE porting for changes done at EE api layer. These changes are mainly related to performance enhancements done for following apis.
/noncompliancepolicy
/overallcompliance
/admin/policy/list
> fix:[CORE-1660] ce porting for performance related changes of api 

- webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase/policy-knowledgebase.component.ts
1. Fixed user policies showing all policies as autofix enabled.
Before:
After:
User Policies
> fix: fixed user policies showing all autofix enabled

- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/file/ErrorManageUtil.java
The below issues should be included for permission : 
- UnauthorizedOperation
The below issues should be omitted : 
- InvalidSnapshot.NotFound
- TrailNotFoundException
- Run aws collector
- Email should be generated
> fix:[CORE-1780] Vertex and spectro cloud ops

- installer/resources/pacbot_app/files/DB_Policy.sql
- updated policy category to security for those mentioned in ticket.
policy category in cf_PolictTable
> fix:[CORE-1782] Change policy category to security

- installer/resources/pacbot_app/files/ui_docker/dockerfile
Updated web app docker with  nginx:1.21.6 image
Tested Via Fresh installation in OssDev
> chore:[Devops-221]Updated niginxDocker image

- installer/resources/pacbot_app/files/DB_Policy.sql
- updated policy name, severity and category as per tickets
policy name, severity and category in cf_PolicyTable
> fix:[CORE-1789][CORE-1787] Update severity category and displayName for Policies

- installer/resources/lambda_rule_engine/files/rule_engine_cloudwatch_aws_rules.json
https://github.com/PaladinCloud/CE/pull/1954
Removed unsued policy 
> chore:Removed Policy(ec2 shouldn't access 3306) (#1954)

- webapp/src/app/shared/table-filters/table-filter-chip/table-filter-chip.component.css
- webapp/src/app/shared/table-filters/table-filter-chip/table-filter-chip.component.html
- webapp/src/app/shared/table-filters/table-filters.component.css
- webapp/src/app/shared/table-filters/table-filters.component.html
- webapp/src/styles.css
Changed styles of disabled filters to differentiate it from enabled filter.
Please describe the tests that you ran to verify your changes. Could you provide instructions so we can reproduce them? Please also
Before:
After:
> Style:[UIUX-497]disabled filter chips

- installer/resources/lambda_rule_engine/files/rule_engine_cloudwatch_aws_rules.json
Removed Policy(ec2 shouldn't access 3306)
Need to be merged missing in release branch
> chore:Removed Policy(ec2 shouldn't access 3306)

- installer/resources/pacbot_app/files/ui_docker/dockerfile
https://github.com/PaladinCloud/CE/pull/1967
for relase branch
> chore:removed vulenrablity issue from webapp image

- webapp/src/app/pacman-features/modules/admin/policies/policies.component.ts
- webapp/src/app/pacman-features/modules/notifications/cloud-notifications/cloud-notifications.component.html
- webapp/src/app/pacman-features/modules/notifications/cloud-notifications/cloud-notifications.component.ts
- webapp/src/app/shared/date-selection/date-selection.component.html
- webapp/src/app/shared/date-selection/date-selection.component.ts
- webapp/src/app/shared/services/filter-management.service.ts
- webapp/src/app/shared/services/utils.service.ts
- webapp/src/app/shared/shared.module.ts
- webapp/src/app/shared/table-filters/pipes/date-range-formatter.pipe.spec.ts
- webapp/src/app/shared/table-filters/pipes/date-range-formatter.pipe.ts
- webapp/src/app/shared/table-filters/table-filter-chip/table-filter-chip.component.html
- webapp/src/app/shared/table-filters/table-filter-chip/table-filter-chip.component.ts
- webapp/src/app/shared/table-filters/table-filters.component.html
- webapp/src/app/shared/table-filters/table-filters.component.ts
- webapp/src/app/shared/table/table.component.html
- webapp/src/app/shared/table/table.component.ts
1. Integrated Dynamic and enhanced filters in notifications
2. Modified logic to add calendar as filter
3. Clear sort when screen breaks because of sort.
4. Corrected date format in filter chip
Corrected date shown in filter chip (earlier it was showing according to UTC):
Multivalue filters:
Dynamic filters:
Dynamic Calendar:
Corrected date format in filter chip:
> Feat:[UIUX-45]notfications enhanced filters

- webapp/src/app/shared/table-filters/table-filter-search/table-filter-search.component.html
- webapp/src/app/shared/table-filters/table-filter-search/table-filter-search.component.ts
Auto-focus on table filter search inputs for an enhanced user experience. Implement auto-focus on the input field in the TableFilterSearchComponent during component initialization.
https://paladincloud.atlassian.net/browse/UIUX-569
https://github.com/PaladinCloud/CE/assets/152586069/522201e8-3caf-4cb6-a03d-16b1f2154c05
> feat:[UIUX-569] table search filter autofocus

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/PolicyStatesInventoryCollector.java
Added null check in PolicyStatesInventoryCollector to avoid exception and data alert.
> fix:[CORE-1817] azure policy collector fix for data alert

- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/file/AssetFileGenerator.java
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/file/ErrorManageUtil.java
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/util/InventoryUtil.java
> fix:[CORE-1830] Added null check while collecting cloudtrails.

- webapp/src/app/pacman-features/modules/compliance/issue-details/issue-details.component.html
[UI][Violations] Incorrect expiry date is displayed at the top after request exemption.
https://paladincloud.atlassian.net/browse/UIUX-547
Changed the date pipe parameter from 'medium' to 'mediumDate'.
Bug: 
Fix:
> fix:[UIUX-547] request exemption incorrect expiry date

- installer/resources/pacbot_app/files/DB_Policy.sql
Updated policy names as per jira tickets
Policy names
> fix:[CORE-1820][CORE-1821][CORE-1822][CORE-1828] Updates to policy names

- webapp/src/app/pacman-features/modules/admin/account-management/account-management.component.html
- webapp/src/app/pacman-features/modules/admin/asset-groups/asset-groups.component.css
- webapp/src/app/pacman-features/modules/admin/asset-groups/asset-groups.component.html
- webapp/src/app/pacman-features/modules/admin/policies/policies.component.css
- webapp/src/app/pacman-features/modules/admin/policies/policies.component.html
- webapp/src/app/pacman-features/modules/admin/user-management/user-management.component.html
- webapp/src/app/pacman-features/modules/assets/asset-details/asset-details.component.html
- webapp/src/app/pacman-features/modules/assets/asset-list/asset-list.component.css
- webapp/src/app/pacman-features/modules/assets/asset-list/asset-list.component.html
- webapp/src/app/pacman-features/modules/assets/asset-list/asset-list.component.ts
- webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.css
- webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.html
- webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase/policy-knowledgebase.component.css
- webapp/src/app/pacman-features/modules/notifications/cloud-notifications/cloud-notifications.component.css
- webapp/src/app/pacman-features/modules/notifications/cloud-notifications/cloud-notifications.component.html
- webapp/src/app/pacman-features/secondary-components/pacman-policy-violations/pacman-policy-violations.component.html
- webapp/src/styles.css
Refactored the styles.
Removed redundant and no more used styles.
Removed inline styles.
> refact: refactored table styles

- webapp/src/app/pacman-features/modules/admin/asset-groups/create-asset-groups/create-asset-groups.component.ts
1. removed hard coded source map. used display name method from asset tiles service instead.
> fix:[PLG-399] removed hard coded source map

- webapp/src/app/core/store/states/config/config.state.ts
- webapp/src/app/pacman-features/modules/compliance/issue-details/issue-details.component.css
- webapp/src/app/pacman-features/modules/compliance/issue-details/issue-details.component.html
- webapp/src/app/pacman-features/modules/compliance/issue-details/issue-details.component.ts
- webapp/src/config/configurations.ts
- webapp/src/environments/environment.prod.ts
- webapp/src/environments/environment.stg.ts
- webapp/src/environments/environment.ts
Removed all jira related reference, find and create jira api removed  
https://paladincloud.atlassian.net/browse/UIUX-556
Code removal
> fix:[UIUX-556] find and create jira api removed

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/config/InterceptorConfig.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/controller/AccountsController.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/controller/PolicyController.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/dto/PluginNotificationDto.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/interceptor/TokenInterceptor.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AbstractPluginService.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/GcpPluginServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/NotificationService.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/NotificationServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/RedHatPluginServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/accounts/AbstractAccountServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/accounts/AccountsService.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/accounts/AquaAccountServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/accounts/AwsAccountServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/accounts/AzureAccountServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/accounts/ContrastAccountServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/accounts/GcpAccountServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/accounts/QualysAccountServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/accounts/TenableAccountServiceImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/Constants.java
- installer/resources/pacbot_app/files/DB_Policy.sql
- lambda-functions/notification-template-formatter-service/src/main/java/com/paladincloud/CommonUtils.java
- lambda-functions/notification-template-formatter-service/src/main/resources/pluginEmailTemplate.html
[Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List
any dependencies that are required for this change.](feat:[PLG-290] plugin notification)
[PLG-290]: https://paladincloud.atlassian.net/browse/PLG-290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat:[PLG-290] plugin notification

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/VMsWithSeverityVulnerabilityRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/model/VulnerabilityInfo.java
[PLG-422] policy changes for missing vulnerability
got the missing vul for asset id i-068fb06444da38265
[PLG-422]: https://paladincloud.atlassian.net/browse/PLG-422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix:[PLG-422] policy changes for missing vulnerability

- installer/resources/pacbot_app/files/DB_Policy.sql
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/cloudtrail/DenyPublicAccessS3BucketStoresCloudTrailLogs.java
Violation should be raised in case of overly permissive bucket policy and policy description needs to be better
Run rule engine to raise violation
Run SQL query to check policy description
> fix:[CORE-1776]Violation should be raised and description change

- webapp/src/app/pacman-features/modules/admin/account-management/account-management.component.html
- webapp/src/app/pacman-features/modules/admin/account-management/account-management.component.ts
- webapp/src/app/pacman-features/modules/admin/asset-groups/asset-groups.component.html
- webapp/src/app/pacman-features/modules/admin/asset-groups/asset-groups.component.ts
- webapp/src/app/shared/services/filter-management.service.ts
1. Enhanced and dynamic filters in admin asset groups.
> feat:[UIUX-64] enhanced filters integration admin asset groups

- installer/settings/common.py
> fix[PLG-290] lambda version change

- installer/settings/common.py
> fix:[PLG-290] lambda version change

- installer/resources/pacbot_app/files/DB.sql
CORRESPONDING UI PR :  https://github.com/PaladinCloud/EE/pull/1592
> bug:[CORE-1732]add source in violations filter

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/VMsWithSeverityVulnerabilityRule.java
- Give a standard name for tenable violation reason similar to qualys violation reason
violation reason  text
> fix:[CORE-1862] Give standard name for tenable violation reason

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/ResourceWithSeverityVulnerabilityRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/VMsWithSeverityVulnerabilityRule.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/JobExecutor.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/MultiThreadedPolicyRunner.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/PolicyExecutor.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/SingleThreadPolicyRunner.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/publisher/impl/AnnotationPublisher.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/util/ESUtils.java
Updated direct link to violations on Tenable side
Update message - made it like for Qualys
All changes except Tenable policy are cosmetical and have no logic changes
Description updated
Links lead to page with applied filters
> fix:[PLG-460] Updated Tenable violations

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/ResourceWithSeverityVulnerabilityRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/VMsWithSeverityVulnerabilityRule.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/JobExecutor.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/MultiThreadedPolicyRunner.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/PolicyExecutor.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/SingleThreadPolicyRunner.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/publisher/impl/AnnotationPublisher.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/util/ESUtils.java
This is the release PR for #2021
> Fix/plg 460/release pr

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/domain/CreateAccountRequest.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/accounts/CheckmarxAccountServiceImpl.java
> feat:[PLG-413] Checkmarx integration API changes

- .github/workflows/SonarCodeAnalysis.yaml
Java 11 is deprecated for sonar scan, 
Updated to java17 
> chore:updated java version for sonar scan

- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/utils/NotificationPermissionUtils.java
- installer/settings/common.py
- lambda-functions/notification-template-formatter-service/src/main/java/com/paladincloud/FetchNotificationSettings.java
- lambda-functions/notification-template-formatter-service/src/main/resources/permissionAlertEmailTemplate.html
Spectro cloud couldnt send email because payload was too large. To resolve this issue we are sending max 40 permission issues in one email to decrease the size of payload. (Max payload size 256KB)
1. Add region issues to permission issues to increase the payload size
2. Run AWS collector. 5 issues in one email (for testing)
Expected : 5 permission issues in email and 2 notifications
Email: 
Notifications:
3. Run Azure collector (Regression Testing)
Expected: 1 email and 1 notification
Email:
[Azure.pdf](https://github.com/PaladinCloud/CE/files/13877225/Azure.pdf)
Notification:
https://saasdev.paladincloud.io/pl/notifications/notification-details?ag=aws&domain=Infra%20%26%20Platforms&eventId=f8687c32-e9c9-44f7-ac54-dc953df9adaf …
> fix:[CORE-1791] Send 30 permission issues per email

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/config/InterceptorConfig.java
> fix:[PLG-461] intercetor changes

- pull_request_template.md
Updates pull request template.
> chore: Minor changes to pull request template.

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ebs/EbsSnapshotShouldBeEncrypted.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/UnrestrictedNACLRuleForConfiguredPort.java
Policy descriptions are corrected, no spelling/grammar mistake, correct spacing, remove extra special characters like “!”
Run policy engine in local
**Note : For status = open these changes in description will be reflected. However, for status = closed, we need to run open search scripts in every client**
> fix:[CORE-1846] Rectifying descriptions

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/common/AdminConstants.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/NotificationServiceImpl.java
Event should be named - Policy (insert display name) has been (insert action)
Enable policy and check notification
Before :
After: 
> fix:[CORE-1852] Format

- installer/resources/pacbot_app/files/DB_Policy.sql
Delete policy
Before running delete query
After running delete query
> fix:[CORE-1658] Delete policy

- jobs/pacman-data-shipper/pom.xml
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/Main.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/dto/JobSchedulerSQSMessageBody.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/SQSManager.java
Message was received by lambda
https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fsaasdev-rule-engine-test-new/log-events/2024$252F01$252F16$252F$255B$2524LATEST$255D6f9bf6a605754612b55871f317772923$3Fstart$3D1705310033401
> [PLG-425] changes for sending SQS message from shipper for policy

- installer/resources/lambda_rule_engine/files/rule_engine_cloudwatch_plugin_rules.json
feat[PLG-312] release branch changes
> feat[PLG-312] release branch changes

- installer/resources/lambda_rule_engine/files/rule_engine_cloudwatch_plugin_rules.json
feat:[PLG-312] rule added to json
[PLG-312]: https://paladincloud.atlassian.net/browse/PLG-312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat:[PLG-312] rule added to json

- installer/resources/lambda_rule_engine/files/rule_engine_cloudwatch_gcp_rules.json
- installer/resources/lambda_rule_engine/files/rule_engine_cloudwatch_plugin_rules.json
> feat:[PLG-312] redhat rule json changes

- installer/resources/lambda_rule_engine/files/rule_engine_cloudwatch_gcp_rules.json
- installer/resources/lambda_rule_engine/files/rule_engine_cloudwatch_plugin_rules.json
> feat:[PLG-312] release changes

- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/PolicyExecutor.java
fix:[PLG-428] sns fix.
[PLG-428]: https://paladincloud.atlassian.net/browse/PLG-428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix:[PLG-428] sns fix.

- installer/resources/lambda_rule_engine/files/rule_engine_cloudwatch_aws_rules.json
Removed cloud_watch_event_policy
> Refactor:Removed cloud_watch_event_policy

- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/PolicyExecutor.java
Fix: Batch getting failed even if one policy got failed. 
> feat:[PLG-428] Policy Engine changes.

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/SQSManager.java
> feat:[PLG-477] update sqs message group id

- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/PolicyExecutor.java
feat:[PLG-428] Replaced Standard sns to Fifo sns.
[PLG-428]: https://paladincloud.atlassian.net/browse/PLG-428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat:[PLG-428] Replaced Standard sns to Fifo sns.

- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/dto/CollectorIssuesVH.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/utils/Constants.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/utils/NotificationPermissionUtils.java
- installer/resources/pacbot_app/files/DB_Policy.sql
- installer/settings/common.py
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/util/ErrorManageUtil.java
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/file/ErrorManageUtil.java
- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/jobs/HostAssetDataImporter.java
- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/util/ErrorManageUtil.java
- lambda-functions/notification-template-formatter-service/src/main/java/com/paladincloud/CommonUtils.java
- lambda-functions/notification-template-formatter-service/src/main/java/com/paladincloud/FetchNotificationSettings.java
Included misconfigurations in insufficient permissions email
Cequence has Authentication exception in azure collector due to misconfigurations
Send email stating its a misconfiguration
Run AWS collector
Run Azure collector
Changed "permission" to "plugin"
> fix:[CORE-1872] Permission and misconfigured

- .github/workflows/jobs-build.yaml
- .github/workflows/proddeploy.yml
- commons/pom.xml
- jobs/pom.xml
- pom.xml
chore:[Devops-231]Build and push jobs jar to s3
Problem
Copying job folder during runtime
Solution
Copying build jar into S3 bucket
> chore:[Devops-231] push jar to s3 from CE

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/Utils/AssetUtils.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/controller/AssetListController.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepository.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepositoryImpl.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetService.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetServiceImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/utils/CommonUtils.java
- installer/resources/pacbot_app/files/DB.sql
Integrating the assets scanned by a policy with assets api. Putiing the repo in sync.
> bug:[CORE-990] scanned assets integration

- .github/workflows/jobs-build.yaml
Workflow fix not to trigger on create branch expect release-v.*.*.*
> chore:[DEVOPS-231]Workflow-fix

- .github/workflows/jobs-build.yaml
> refactor:removed on create

- .github/workflows/jobs-build.yaml
- .github/workflows/proddeploy.yml
> chore:workflow filter fix

- webapp/src/app/pacman-features/modules/admin/asset-groups/create-asset-groups/create-asset-groups.component.ts
- webapp/src/app/pacman-features/modules/admin/create-edit-policy/create-edit-policy.component.ts
- webapp/src/app/pacman-features/modules/admin/user-management/user-management.component.ts
- webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase/policy-knowledgebase.component.ts
- webapp/src/app/shared/input-field/input-field.component.ts
- webapp/src/app/shared/services/error-handling.service.ts
- webapp/src/app/shared/services/filter-management.service.ts
- webapp/src/app/shared/services/form.service.ts
- webapp/src/app/shared/table/interfaces/table-props.interface.ts
1. Fixed breaking of users list on scrolling to end when UI made a request for more data crossing the index of total records present. Added missing types in user management.
2. Fixed policies not refreshed on disabling/enabling a policy
3. Fixed the user policies button getting disabled. Updated few methods and used the generic methods from utils service and filterManagement Service.
4.  Added form validation in create asset group.
5. Fixed dynamic filter related bugs in admin asset groups.
Please describe the tests that you ran to verify your changes. …
> fix:[UIUX-500][UIUX-558][UIUX-562][UIUX-564] fixed ui bugs

- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/utils/NotificationPermissionUtils.java
Reducing the payload for email to resolve notification APi issue
Reduce payload size
Run AWS collector
> fix:[CORE-1913] Reduce payload

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/APIKeys/RotateAPIKeysRule.java
renamed `createdDate` to `createdTime` for GCP API Keys
PLG PR https://github.com/PaladinCloud/Plugins/pull/151
That's how it looks in AWS right now:
```
2024-02-07 18:01:40 b5964e65-cd30-4475-9487-96ab2a9ec92a [main] ERROR c.t.p.e.SingleThreadPolicyRunner - unable to evaluate for this resource {discoverydate=2024-02-07 17:23:00+0000, _docid=0642b39d-6516-4125-9a91-f4d0c3d69239, displayName=API key 3, _cloudType=gcp, assetRiskScore=0, _entity=true, accountid=central-run-349616, accountname=Paladin Cloud, targettypedisplayname=Api Keys, restrictions.serverKeyRestrictions.allowed_ips=["172.16.0.0/12"], apikeys_relations=apikeys, id=0642b39d-6516-4125-9a91-f4d0c3d69239, _loaddate=2024-02-07 17:24:00+0000, latest=true, …
```
> Renamed createData to created filed for GCP API Keys

- .github/workflows/mysql-check.yaml
- .github/workflows/mysql-delete-check.yml
Notify Reviewer that this Pr has delete statement In SQL files
[ ] Bug fix (non-breaking change which fixes an issue)
[ ] New feature (non-breaking change which adds functionality)
[ ] Chore (no code changes)
[ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
Yes,
https://github.com/PaladinCloud/CE/pull/2088
please review above Pr
[ ] Test B
I have added tests that prove my fix is effective or that my feature works
[ ] New and existing unit tests pass locally with my changes
> chore:[devops-242]Notifiy reviewer check for delete statement

- .github/workflows/jobs-build.yaml
- .github/workflows/proddeploy.yml
Updated Prod and qa workflow fix
> chore:[DEVOPS-231]fixed prod and qa workflow

- .github/workflows/jobs-build.yaml
- .github/workflows/mysql-check.yaml
- .github/workflows/proddeploy.yml
> chore:[DEVOPS-231]QA-workflow-fix

- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/file/FileManager.java
Renaming attribubte createdDate of aws api to createdTime.
Testing :
Ran shipper at local.
Copied the genertated file to s3 bucktes.
Ran shipper.
Cross checked data at es.
RErun the policy
> bug:[CORE-1819]renaming attribute createdDate to createTime

- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/aws/sqs/SQSManager.java
- installer/resources/batch/job.py
- installer/resources/lambda_rule_engine/function.py
- jobs/pacman-aqua-enricher/src/main/java/com/tmobile/cso/pacman/aqua/Main.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/Main.java
- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/Main.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/common/PacmanSdkConstants.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/Main.java
End to End testing and modified code as per review comments. 
> fix:[PLG-473] Policy Engine review changes.

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/SecurityPricingsInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/util/ErrorManageUtil.java
Ops alert for vertex azure collector
Ops alert generated because Subscription Not Registered to Microsoft.Security in order to view your security status
Send misconfiguration email
Throw exception in azure collector
Check email
> fix:[CORE-1923] Subscribe to Microsoft.Security issue

- .github/workflows/proddeploy.yml
Fixed prod workflow for sql file path
> chore:workflow fix prod

- .github/workflows/proddeploy.yml
> chore:Prod workflow shipper jar push fix

- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/dto/AutofixNotificationRequest.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/dto/PolicyViolationNotificationRequest.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/util/NotificationUtils.java
Add 'accountId' field to notification request payload.
Sample payload now will be 
{
"Records": [
{
"EventSource": "aws:sns",
"EventVersion": "1.0",
"EventSubscriptionArn": "arn:aws:sns:us-east-1:194626369622:saasdev-notification-event:2a4ebece-b454-4402-845e-160fbc6f0d3b",
"Sns": {
"Type": "Notification",
"MessageId": "cf10a498-737b-5d40-9933-fadbc0365b85",
"TopicArn": "arn:aws:sns:us-east-1:194626369622:saasdev-notification-event",
"Message": "{\n  \"eventId\": \"3be0ba15-7c7c-4bdc-876f-155df8995ffc\",\n  \"eventName\": \"Violation for policy - Encrypt EBS Volume\",\n  \"eventCategory\": \"violation\",\n …
> feat:[CORE-1890] add account id field to notification request payload

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/PolicyService.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/PolicyServiceImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/controller/ComplianceController.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/domain/PolicyRequestPrams.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/PolicyTableRepository.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/model/PolicyTable.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/PolicyTableService.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/PolicyTableServiceImpl.java
[PLG-473]
[PLG-473]: https://paladincloud.atlassian.net/browse/PLG-473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat:[PLG-473] adding APIs to CE

- installer/resources/pacbot_app/files/DB.sql
- installer/resources/pacbot_app/files/DB_Policy.sql
> feat:[PLG-470] adding updatedBy and updatedTime to Accounts table

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/AzureFetchOrchestrator.java
Azure collector is generating ops alert in cequence
Logger is generated ops alert
Remove logger
Need to test in cequence
> fix:[CORE-1948] Collector issue

- jobs/pacman-data-shipper/pom.xml
> fix: added back the mysql connector dependency.

- webapp/src/app/pacman-features/modules/admin/asset-groups/asset-groups.component.ts
- webapp/src/app/pacman-features/modules/admin/policies/policies.component.ts
- webapp/src/app/pacman-features/modules/admin/user-management/user-management.component.ts
- webapp/src/app/pacman-features/modules/assets/asset-list/asset-list.component.ts
- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.html
- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.ts
- webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.ts
- webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase/policy-knowledgebase.component.html
- webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase/policy-knowledgebase.component.ts
- webapp/src/app/pacman-features/secondary-components/policy-summary/policy-summary.component.ts
- webapp/src/app/shared/constants/global.ts
- webapp/src/app/shared/services/utils.service.ts
- webapp/src/app/shared/table/table.component.html
- webapp/src/app/shared/table/table.component.ts
This is a ported PR and is rebased on other PR's which are yet to be merged.
1. Added sort and pagination in compliance overview table
2. Added sort and pagination in user policies
https://github.com/PaladinCloud/EE/pull/1647
https://github.com/PaladinCloud/EE/pull/1685
1. Verified if sort and pagination is working as expected in policy compliance overview and user policies.
> Feat: [UIUX-52][UIUX-53]user policies server sort

- webapp/package.json
- webapp/src/app/core/services/image-cache.service.ts
- webapp/src/app/post-login-app/post-login-app.component.ts
- webapp/src/app/shared/services/utils.service.ts
- webapp/src/app/shared/shared.module.ts
- webapp/src/app/shared/table/images-to-preload.ts
- webapp/src/app/shared/table/interfaces/table-props.interface.ts
- webapp/src/app/shared/table/pipes/is-image-present.pipe.spec.ts
- webapp/src/app/shared/table/pipes/is-image-present.pipe.ts
- webapp/src/app/shared/table/table-data-source.ts
- webapp/src/app/shared/table/table.component.css
- webapp/src/app/shared/table/table.component.html
- webapp/src/app/shared/table/table.component.ts
1. After adding virtual scroll, the icons were being fetched on each scroll in the list. This was causing icons to load slowly than data.
2. To fix it, we are now caching icons by registering them as svg icons.
https://github.com/PaladinCloud/EE/pull/1711
> fix:[UIUX-587] fixed icons loading slowly on scroll in lists

- webapp/src/app/pacman-features/modules/compliance/issue-details/issue-details.component.html
- webapp/src/app/pacman-features/modules/compliance/issue-details/issue-details.component.ts
https://paladincloud.atlassian.net/browse/UIUX-612
Disable add / request exemption for closed violation
> fix:[UIUX-612] disable exemption for closed violation

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/PolicyServiceImpl.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/PolicyTableRepository.java
[PLG-488] 
[PLG-488]: https://paladincloud.atlassian.net/browse/PLG-488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix:[PLG-488] fixing update and details api for policy

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/PolicyServiceImpl.java
> fix:[PLG-487] fix for admin details api

- installer/resources/pacbot_app/files/DB.sql
Updated SQL query to use the NOW() function
> fix:[Core-1955] Updated SQL query to use the NOW() function

- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/PolicyExecutor.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/util/CommonUtils.java
- jobs/pacman-rule-engine-2.0/src/main/resources/logback.xml
> fix:[PLG-486] updating error logs

- webapp/src/app/pacman-features/modules/admin/account-management/account-management.component.html
- webapp/src/app/pacman-features/modules/admin/account-management/account-management.component.ts
- webapp/src/app/pacman-features/modules/admin/asset-groups/asset-groups.component.ts
- webapp/src/app/pacman-features/modules/admin/user-management/user-management.component.ts
- webapp/src/app/pacman-features/modules/assets/asset-distribution/asset-distribution.component.html
- webapp/src/app/pacman-features/modules/assets/asset-distribution/asset-distribution.component.ts
- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.ts
- webapp/src/app/pacman-features/modules/notifications/cloud-notifications/cloud-notifications.component.ts
- webapp/src/app/shared/doughnut-chart/doughnut-chart.component.css
- webapp/src/app/shared/services/filter-management.service.ts
- webapp/src/app/shared/services/utils.service.ts
- webapp/src/app/shared/table/table.component.html
1. Added NR in compliance filter options
2. Added created date and source filters in plugins
3. Fixed pagination not working as expected in admin asset groups.
> fix:[UIUX-613][UIUX-600][UIUX-603] compliance filter option

- .gitignore
- jobs/pacman-rule-engine-2.0/pom.xml
- Issue: After major refactoring done in https://github.com/PaladinCloud/CE/pull/2123 for reducing the jar file size, few dependencies were missed out which caused issues in running policy engine
- fix: added the missing dependencies
dependencies missing after maven pom refactor
added the missing dependencies
dependency issue
> fix:[CORE-1967] Fix dependency issue for policy engine

- jobs/pacman-rule-engine-2.0/pom.xml
- collector was failing due to missing sql driver dependency(due to refactoring done in https://github.com/PaladinCloud/CE/pull/2123)
- added the missing mysql driver
missing mysql driver
added the missing mysql driver
missing dependency
> fix:[CORE-1967] Add missing dependency for collector

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/dao/RDSDBManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/ExternalPolicies.java
Please check original PR https://github.com/PaladinCloud/CE/pull/2144/files
https://paladincloudworkspace.slack.com/archives/C061URNQ58D/p1710736062010129)
https://github.com/PaladinCloud/Plugins/pull/176/files for detailed description and testing
> fix:[CORE-1976]Release Branch PRs

- installer/resources/pacbot_app/files/DB.sql
Please refer original PR https://github.com/PaladinCloud/CE/pull/2149/files
> fix:[PLG-410]Scheduler fix for checkmarx

- installer/resources/pacbot_app/files/DB.sql
Please review original PR https://github.com/PaladinCloud/CE/pull/2149#pullrequestreview-1948052478
> fix:[PLG-410]SchedulderBugFix -ReleaseBranch V1.7 

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/dao/RDSDBManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/ExternalPolicies.java
Please refer original /v1.6.0 release pr https://github.com/PaladinCloud/CE/pull/2147#pullrequestreview-1945440705
> fix:[CORE-1976]ReleaseBranch PR 

- jobs/pacman-rule-engine-2.0/pom.xml
- jobs/pacman-tenable-enricher/pom.xml
- aws collector issue: after the major maven dependency refactor, old version of aws-sdk bom was being referenced in policy-engine. Previously before this maven dependency refactor, the aws-sdk bom was upgraded in https://github.com/PaladinCloud/CE/pull/1979, which was missed to be upgraded in the policy-engine
- tenable collector issue: dependencies missing for AWSSecretsManager and sqs
aws-sdk bom is having older version.
missing dependencies
upgrade aws-sdk bom to correct version as it was before the maven dependency refactor
add missing dependencies
dependencies
> fix:[CORE-1984][CORE-1986] Fix IAM access analyser collection for aws, Fix tenable collector dependency issue

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/Constants.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/common/PacmanSdkConstants.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/PolicyExecutor.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/publisher/impl/AnnotationPublisher.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/util/AuditUtils.java
- issue1: exemption requests done by user, which are expired, are still showing up for admins
- issue2: when an issue is evaluated in exempted state, and the policy rule runs, the audit log status shows 'Open' but the issue is actually in exempted state
- issue3: when an issue is auto-opened by the system due to expiry of exemption, the audit log shows status 'Open' without saying due to which action the issue was opened
- solution for issue1: close the exemption requests done by user once the request crosses the expiration date 
- solution for issue2: when an issue is evaluated in exempted state, set the audit status as exempted and not Open
- solution for issue3:  for an issue, when the exemption is expired by the system, set an audit status 'Exemption Expired' before adding an open …
> fix:[CORE-1945] Fix violation exemption audit status

- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.ts
[Dashboard] Donut Chart Flickers when there is no Violations, Relevant message to be displayed in donut chart when there is no violation
https://paladincloud.atlassian.net/browse/UIUX-631
> fix:[UIUX-631] donut chart flickers when no violations

- jobs/pacman-qualys-enricher/pom.xml
- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/util/ErrorManageUtil.java
- added missing dependencies for qualys
- fixed an NPE
missing dependency
add missing dependency
dependency issue
> fix:[CORE-1994] Fix dependency issues in qualys

- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/util/InventoryUtil.java
- issue: the issue is in the way we collect and describe snapshots in the collector. The collector seems to skip collecting if its not able to find and describe a snapshot id that it had listed
- in this case, the snapshot could not be found using snapshotID
- fix: handle exception during describing individual snapshots, so that it doesn't stop describing other listed snapshots
- handled the case when snapshot could not be found using snapshotID
collector skips collecting snapshot if there is an issue describing a single snapshot
handle exception for individual snapshots
> fix:[CUS-286] Fix dips is collected snapshot assets for vertex

- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/PolicyExecutor.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/util/AuditUtils.java
- some policy jobs were failing due to NPE which is fixed now
NPE
add NPE checks
NPE
> fix:[CORE-1945] Fix for NPE

- webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.ts
- webapp/src/app/pacman-features/secondary-components/asset-trend-graph/asset-trend-graph.component.ts
- webapp/src/app/pacman-features/secondary-components/issues-trend-history/issues-trend-history.component.ts
- webapp/src/app/post-login-app/asset-groups/asset-groups.component.html
- webapp/src/app/post-login-app/asset-groups/asset-groups.component.ts
- webapp/src/app/post-login-app/common/services/selective-preloading-strategy.service.ts
- webapp/src/app/post-login-app/post-login-app-routing.module.ts
- webapp/src/app/post-login-app/post-login-app.component.ts
- webapp/src/app/post-login-app/post-login-app.module.ts
Fixed few bugs.
Preloaded lazy loaded modules.
> feat: [UIUX-666][UIUX-668][UIUX-522][UIUX-669]performance optimization and bug fixes

- jobs/job-scheduler/src/main/java/com/paladincloud/jobscheduler/service/JobScheduler.java
> feat:[PLG-520] scheduler changes

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/Main.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/config/S3ClientConfig.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/AWSErrorManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/EntityAssociationManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/EntityManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/ExternalPolicies.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/TargetTypeService.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/ViolationAssociationManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/error/ErrorManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/util/Util.java
[PLG-441]
[PLG-441]: https://paladincloud.atlassian.net/browse/PLG-441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat:[PLG-441] shipper changes

- installer/resources/pacbot_app/files/DB.sql
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/EntityManager.java
- added crowstrike plugin in pac_config_properties key plugins.in.v1, so that its picked up by scheduler
- handled NPE when cloudType is null (for workstation, cloudType is null)
crowstrike collector must be triggered by job scheduler
add entry in pac_config_properties key plugins.in.v1
> feat:[PLG-505] Job scheduler changes for new plugin crowdstrike

- installer/resources/pacbot_app/files/DB.sql
- jobs/job-scheduler/src/main/java/com/paladincloud/jobscheduler/service/JobScheduler.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/Main.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/config/S3ClientConfig.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/AWSErrorManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/EntityAssociationManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/EntityManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/ExternalPolicies.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/TargetTypeService.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/ViolationAssociationManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/error/ErrorManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/util/Util.java
[PLG-441]
[PLG-520]
[PLG-441]: https://paladincloud.atlassian.net/browse/PLG-441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat:[PLG-520] scheduler changes feat:[PLG-441] shipper changes

- installer/resources/pacbot_app/files/DB.sql
> feat:[PLG-520] config changes

- installer/resources/pacbot_app/files/DB_Policy.sql
Policy Display name fixes
Tested locally by updating the sqls in dev
> fix:[CORE-2015] Policy name issues

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/controller/AssetGroupController.java
Admin API is not starting due to a duplicate API path.
Removed the same.
Able to run the Admin in local post changes.
> fix:[CORE-2017] Admin resolved duplicate api path

- installer/resources/pacbot_app/files/DB_Policy.sql
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/iam/IAMUserWithMultipleAccessKeyRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/utils/PacmanUtils.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/constants/PacmanRuleConstants.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/iam/IAMUserWithMultipleAccessKeyRuleTest.java
This is nothing but release branch PR of https://github.com/PaladinCloud/CE/pull/2183 .Please refer original PR for more details
> fix:[CUS-295/296]ReleaseBranch PR

- installer/resources/pacbot_app/files/DB.sql
> fix:[PLG-520] updating the value of cq configs without loosing state

- installer/resources/pacbot_app/files/DB.sql
> fix:[PLG-520] updating remaining configs of plugins

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/EntityManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/VulnerabilityAssociationManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/es/ESManager.java
- created a Vulnerability association manager which will upload all vulnerabilities collected from crowdstrike to opensearch
- Thus, introducing a new feature, when shipper detects datasource-vulnerabilities.data in mapped results, it will upload all the vulnerabilities from the file to opensearch index datasource_vulnerability.
- when each time vulnerabilities are shipped to opensearch, it will also delete the vulnerabilities that are closed on crowdstrike, using load date
need to Ship vulnerabilties 
created Vulnerability association manager 
> feat:[PLG-512] Ship crowdstrike vulnerability info to opensearch

- installer/resources/pacbot_app/files/DB.sql
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/AssetGroupManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/TargetTypeService.java
> fix:[PLG-520] wiz shipper fix

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/TargetTypeService.java
[CORE-2023]
[CORE-2023]: https://paladincloud.atlassian.net/browse/CORE-2023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix:[CORE-2023] JsonNode.isEmpty is not available

- jobs/job-scheduler/src/main/java/com/paladincloud/jobscheduler/service/JobScheduler.java
[CORE-2024]
[CORE-2024]: https://paladincloud.atlassian.net/browse/CORE-2024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix:[CORE-2024] scheduler fix

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/EntityManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/TargetTypeService.java
> fix:[PLG-520] populate docid and resouce id from wiz

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/ViolationAssociationManager.java
> fix:[PLG-520] do not replace docid for violations if present

- installer/resources/pacbot_app/files/DB.sql
[PLG-441]
[PLG-441]: https://paladincloud.atlassian.net/browse/PLG-441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix:[PLG-441] updating plugins v1 config with wiz

- installer/resources/pacbot_app/files/DB.sql
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/AssetGroupManager.java
[PLG-561]
[PLG-561]: https://paladincloud.atlassian.net/browse/PLG-561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat:[PLG-561] Only show one System assetgroup and do not create rapid7 assetgroup

- jobs/job-scheduler/src/main/java/com/paladincloud/jobscheduler/repository/AccountsRepository.java
[PLG-573]
[PLG-573]: https://paladincloud.atlassian.net/browse/PLG-573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix:[PLG-573] Scheduler failed to trigger collector jobs

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/azurerules/VirtualMachine/BYOKDiskVolumeRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/azurerules/VirtualMachine/EncryptionAppTierRule.java
replica PR of https://github.com/PaladinCloud/CE/pull/2247
> fix:[CORE-2047]Policy Failure Fix for release branch PR

- installer/resources/pacbot_app/files/DB.sql
[PLG-576]
release branch changes
> fix:[PLG-576] Wiz collector failed to trigger as a part of scheduler

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AssetGroupServiceImpl.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/AssetGroupManager.java
[PLG-586]
release branch changes
[PLG-586]: https://paladincloud.atlassian.net/browse/PLG-586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix:[PLG-586] fix system assetgroup

- jobs/job-scheduler/src/main/java/com/paladincloud/jobscheduler/service/JobScheduler.java
Removed no of batch and vulnerablity shipper
> chore:Removed no of batch and vulnerablity shipper

- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/PacmanSdkConstants.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/ViolationAssociationManager.java
[PLG-585]
[PLG-585]: https://paladincloud.atlassian.net/browse/PLG-585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat:[PLG-585] Policy reason changes for shipper

- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/common/PacmanSdkConstants.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/util/AuditUtils.java
For System Audit trail, we are showing "exempted" status instead of "exempt". It needs to be "Exempt" for UI consistency
This is due to Violation status gets stored at ES as " Exempted"
For Audit log we need to add condition 
> fix:[CORE-2045]System status showing exempted instead of "Exempt"

- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/PolicyExecutor.java
This has to be reverted since it has impact on others. We will address this as part of tech debt by finding suitable approach to address this
> revertfix:[CORE-2068] CE revert fix

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/azurerules/VirtualMachine/EncryptionAppTierRule.java
[NEXT-114]making App-Tire tag is optional
[NEXT-114]: https://paladincloud.atlassian.net/browse/NEXT-114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NEXT-114]making App-Tire tag is optional

- .github/workflows/jobs-build.yaml
- subsystem/auth/services/svc-api-authorizer/README.md
> fix:s3 path

- jobs/job-scheduler/src/main/java/com/paladincloud/jobscheduler/model/DataCollectorSQSMessageBody.java
- jobs/job-scheduler/src/main/java/com/paladincloud/jobscheduler/service/DataCollectorSQSService.java
- jobs/job-scheduler/src/main/java/com/paladincloud/jobscheduler/util/Constants.java
feat:[NEXT-236] Added tenant_id and tenant_name to scheduler
[NEXT-236]: https://paladincloud.atlassian.net/browse/NEXT-236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat:[NEXT-236] Added tenant_id and tenant_name to scheduler

- installer/resources/pacbot_app/files/DB.sql
- display the correct asset state data in asset list view
> fix:[NEXT-296] Fix column data for Asset state in asset list view

- .github/workflows/jobs-build.yaml
> chore: depreacted version udpate

- .github/workflows/jobs-build.yaml
> chore:download artifact version update

- .github/workflows/SonarCodeAnalysis.yaml
> chore:Sonar workflow fix

- .github/workflows/jobs-build.yaml
> chore:maven workflow fix
