PaladinCloud/CE

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/elasticsearch/ESEncryptionAtRestRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/elasticsearch/ESEncryptionUsingKMSCMKsRule.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/elasticsearch/ESNodetoNodeEncryptionRule.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/elasticsearch/ESEncryptionAtRestRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/elasticsearch/ESEncryptionUsingKMSCMKsRuleTest.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/elasticsearch/ESNodetoNodeEncryptionRuleTest.java
Updating opensearch encryption policies to check the version. To enable node to node encryption , the version should be greater than 6.0 and for at rest encryption, it should be greater than 5.1.
> fix:updating opensearch policy to check the version for encryption

- installer/resources/lambda_rule_engine/function.py
- installer/resources/lambda_submit/function.py
lambda runtime python 3.6 is deprecated so updated to python 3.8
> chore: updated lambda run time to 3.8

- commons/pac-batch-commons/pom.xml
Upgraded the version of aws-java-sdk-bom to 1.12.234 from 1.11.636 in commons to resolve the version conflict. The older version was missing some features for some of the aws resources like auto scaling group.
> chore:Upgraded aws-java-sdk version in commons

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/controller/AssetTrendController.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepositoryImpl.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/AssetGroupStatsCollector.java
- Changed the default behaviour of asset count trend API
- Removed the unwanted asset type distribution
> fix: Corrected asset count trend API to return all-time data by default

- installer/settings/default.local.py
Added RESOURCE_NAME_PREFIX to the default local options and cleaned up some comment language in the file.
RESOURCE_NAME_PREFIX should be added to default.local.py so users can change it there instead of directly in common.py which could create conflicts with future versions.
Docs: Updates the language for some of the comments in default.local.py since those are the ones most likely to be read by developers
If this is added our troubleshooting documentation should point users to modify local.py instead of common.py
> Added RESOURCE_NAME_PREFIX

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AssetGroupExceptionServiceImpl.java
- api/pacman-api-vulnerability/src/main/java/com/tmobile/pacman/api/vulnerability/repository/VulnerabilityRepository.java
- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/utils/ESUtils.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/es/ESManager.java
- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/util/ElasticSearchManager.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/util/ESUtils.java
- jobs/recommendation-enricher/src/main/java/com/tmobile/cso/pacbot/recommendation/es/ESManager.java
3 shards in ES are causing a lot of unnecessary reads on the cluster. Reduced the no of shards to 1. We will need to roll over once each index reaches a certain size. That will be handled later.
> fix: Updated no of shards in ES to 1

- jobs/gcp-discovery/src/main/java/com/tmobile/pacbot/gcp/inventory/collector/VMInventoryCollector.java
- Corrected the incorrect count for GCP application tag
Fixes # (issue)- Incorrect application count in the recently viewed asset group screen
> fix: Incorrect gcp application count

- webapp/src/app/pacman-features/modules/admin/create-edit-policy/create-edit-policy.component.html
- webapp/src/app/pacman-features/modules/admin/create-edit-policy/create-edit-policy.component.ts
removed duplicate params for category and severity by not passing in paramsList while updating
> Fix: Removed duplicate params for category and severity

- webapp/src/app/pacman-features/secondary-components/policy-violation-desc/policy-violation-desc.component.html
- webapp/src/app/pacman-features/secondary-components/policy-violation-desc/policy-violation-desc.component.ts
Display ViolationID in the Details UI
Fixes #884 
> Added: violationID in details UI

- webapp/src/app/shared/pipes/order-by.pipe.ts
In Fix-central -> Health Notifications -> sorting dates are not working properly.
Fixes #861
> bug:sorting dates in fix-central

- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.css
- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.html
- webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.ts
- webapp/src/app/pacman-features/modules/compliance/services/dashboard-arrangement.service.ts
https://user-images.githubusercontent.com/4422785/234813443-3fb15547-f8bd-4c18-9a80-28aa612f86bc.mp4
- [x ] I have performed a self-review of my code
> feat: dashboard container collapse

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/iam/CheckIamPasswordPolicyRule.java
Modified password policy condition check
Fixes # (issue) [MVP2023-509] modified boolean conditions
[MVP2023-509]: https://paladincloud.atlassian.net/browse/MVP2023-509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: modified condition

- webapp/src/app/pacman-features/modules/notifications/prop-value-link.directive.ts
If an input value in key-value view is not a string, `match is not a function` error was thrown
> feat(notifications): filter only string values

- webapp/src/app/post-login-app/post-login-app.component.html
Pressing the Esc key will normally close an open sidenav. This behavior was disabled.
> feat(contextual-menu): disabled auto close

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/EntityAssociationManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/EntityManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/es/ESManager.java
- jobs/pacman-data-shipper/src/test/java/com/tmobile/cso/pacman/datashipper/es/ESManagerTest.java
ALL AWS resource  which not configured with ARN  are now using the created with combination of cloud type, asset type, account id, region, resource id , 
Fixes # [CORE-828] [CORE-835]
[CORE-828]: https://paladincloud.atlassian.net/browse/CORE-828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CORE-835]: https://paladincloud.atlassian.net/browse/CORE-835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix: [CORE-828] [CORE-835] AWS resource unique id issue

- webapp/src/app/post-login-app/post-login-app.component.html
- webapp/src/app/post-login-app/post-login-app.component.ts
Hovering on a collapsed menu pushes the main content
before:
https://github.com/PaladinCloud/CE/assets/4422785/da37adaa-a6d4-44e6-95fd-d4a38ceb3052
after:
https://github.com/PaladinCloud/CE/assets/4422785/f0cd6b18-c649-4c2b-9471-c35a9b187d37
> fix(sidenav-content): pushed when drawer mode change to over

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/config/ConfigManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/EntityManager.java
Added new field "_resourcename" for ever parent document in OpenSearch.
This will be used in asset list page in resourceid column. 
Fixes # [CORE-904] Added new filed "_resourcename"
[CORE-904]: https://paladincloud.atlassian.net/browse/CORE-904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: [CORE-904] Added new filed "_resourcename"

- installer/resources/pacbot_app/files/DB_Policy.sql
This change will resolve the following polices : 
Disable_3625_Flag_for_SQL_Server_DB_Instances-job
Disable_Contained_DB_Auth_Flag_for_SQL_Server_DB_Instances-job
Disable_Remote_Access_Flag_for_SQL_Server_DB_Instances-job
> fix:[CORE-894]Policy key issue

- README.md
Documentation has migrated away from GitHub Wiki so this change updates the links to their new home on paladincloud.io/docs/
I clicked on the links in preview mode to be sure they worked
> Update docs links in README.md

- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/util/InventoryUtil.java
Ignore data dog alerts in case customers are not using the Trusted Advisor AWS Data collector
> fix:[CORE-1315]Ignore data dog alerts for Trusted advisor

- commons/pac-batch-commons/src/main/java/com/tmobile/pacman/commons/PacmanSdkConstants.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/iam/IAMRoleWithUnapprovedAccessRule.java
1. When NoSuchEntityFoundException is thrown from class IAMRoleWithUnapprovedAccessRule.java(which affects 3 policies), exception is caught and validation is assigned 'unknown' status. Data alert is not published.
> fix:[CORE-1379] handle noentityfound exception for iam policies

- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/Constants.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/Main.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/MainUtil.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/jobs/TenableDataImporter.java
Role name has been added into secret name - now it's possible to add Tenable plugin for more that one customer per AWS account.
Only single tenable secret left:
Job is executing well:
Link to job:
https://us-east-1.console.aws.amazon.com/batch/home?region=us-east-1#jobs/detail/26516c3f-bc78-4494-8e8d-5db7137f7f01
> [PLG-315] Multiple tenable plugins per AWS base account

- installer/resources/pacbot_app/files/DB.sql
remove RedHat Plugin as default as Asset group
[PLG-324]
[PLG-324]: https://paladincloud.atlassian.net/browse/PLG-324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore:[PLG-324] remove RedHat Plugin as default as Asset group

- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/Main.java
- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/jobs/HostAssetDataImporter.java
- jobs/pacman-qualys-enricher/src/main/java/com/tmobile/cso/pacman/qualys/util/ErrorManageUtil.java
Ops alert should not be generated after user is notified of authentication issue
Ran the qualys asset importer in saasdev
> fix:[CORE-1557] Ops alert qualys issue

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/TenableAccountServiceImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/Constants.java
Changed URL to gather non-existing export.
It gives 404 if creds are good, and 401 if they are not.
Will update later when got response from Tenable on what API would be better to use for such purpose.
> [PLG-335] Fix for checking tenable creds

- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/common/PacmanSdkConstants.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/PolicyExecutor.java
For kms asset type, aws managed keys doesn't need to be evaluated by policies as they cannot be changed by user. So we are filtering out the aws managed kms resources before policy evaluation.
> fix[CUS-253]: filter out aws managed keys from policy evaluation

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/TenableAccountServiceImpl.java
Since Tenable URL is static - it doesn't need to be passed from UI and can be just a global constant
Ran admin API and tested locally via postman.
Test results for correct creds:
Results for wrong creds:
> Removed Tenable URL from request check

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/TaggingRule.java
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/util/InventoryUtil.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/PolicyExecutor.java
The issue was due to evaluating the AWS-managed keys which are not editable by the user. The fix will stop collecting the AWS-managed keys, so only the customer-managed keys will be evaluated by kms policies.
> fix:[CUS-253]stop collecting aws managed keys

- webapp/src/app/pacman-features/modules/compliance/policy-details/policy-details.component.css
- webapp/src/app/pacman-features/modules/compliance/policy-details/policy-details.component.html
- webapp/src/app/pacman-features/modules/compliance/policy-details/policy-details.component.ts
Made following changes in policy params widget :
1. Used display names for keys.
2. Increased width of keys.
3. Removed max height and scroll from the widget.
Before changes:
After changes:
Policy Params widget in Policy Compliance Screen.
> fix:[UIUX-443] used display names for keys in policy params widget

- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/common/PacmanSdkConstants.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/executor/PolicyExecutor.java
This reverts the change done in https://github.com/PaladinCloud/CE/pull/1750, since we are fixing this by filtering out the aws managed keys in collector
> revert:[CUS-253]filter out aws managed keys from policy evaluation

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/EntityManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/util/Constants.java
CQ Collector **does not contain AccountName** but AccountID. So we are fetching accountName using RDS from cf_Accounts table by passing accountId. We are using shipper module since it already contains code for RDS connection besides we also need to ship accountName to ES. So shipper module is apt one to make this changes.
Made shipper changes and ran the Shipper job for GCP using JobExecutor and checked ES data for accountName. Ensured these data are populated at SAASDEV as well as part of Paladin portal. Also tested negative test case of Azure Data -Shipper to make this RDS Call is only getting executed only for gcp-data-shipper but not for others.
> fix:[PLG-352]AccountName population Issue for CQ Collector-GCP

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/utils/GCPFirewallUtils.java
**VPC_firewall_OuBound_Egress_should_not_be_publicly_accessible** policy execution got failed due to source range being NULL for some of the assets. If the source range is NULL, policy execution should happen as if it wasn’t equal to public access source range(like 0.0.0.0/0).
Mocked Mapper generated data where source range is NULL and tested the policy execution using local Junit execution to make sure that NULL pointer exception not getting thrown at local execution
> fix:[PLG-357]OpsAlert-NullPointerexception fix for VPC Outbound rule

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/cloudfunctions/IngressSettingRule.java
This policy got failed across all tenants(cquence/testdrive) due to class not found exception. During investigation it has been found policy param key **"GCP_Cloud_Function_configured_with_overly_permissive_Ingress_setting"** is not matching with IngressSettingRule.java @PacmanPolicy annotation value
**Expected key value :** GCP_Cloud_Function_configured_with_overly_permissive_Ingress_setting
**Actual Value present:** GCP-Cloud-Function-configured-with-overly-permissive-Ingress-setting
Tested without fixing to replicate class not found exception.Able to reproduce the issue as below at my local using PolicyExecutor.
Checking the value of Policy param key at **cf_PolicyParams** table.
klist:
Post Change 
List any documentation …
> fix:[PLG-370]ClassNotfoundException for Check_permission_of_Ingress_Setting_of_GCP_cloud_Function

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/cloudstorage/CloudStorageWithPublicAccessRule.java
**@policyId:Cloud_Storage_should_not_be_public** got failed due to **"users"** attribute is not present during policy execution. If users attribute is not present policy should handle as if users list is empty or null.
-
**- Positive Test Case** Users Attribute present in Mock Json(Mapper Generated Json)
**Negative Test Case : Users Attribute is not present in Mock Json**
**Expected** : Policy should execute without Null Pointer exception
Actual: Executed without any issue
> fix:[PLG-367]Users Atrribute Not found issue for Policy

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/VMsWithSeverityVulnerabilityRule.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/Constants.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/Main.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/jobs/TenableVMVulnerabilityDataImporter.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/util/ConfigUtil.java
- jobs/pacman-tenable-enricher/src/main/java/com/tmobile/cso/pacman/tenable/util/ElasticSearchManager.java
Changed filtering for assets - asset must have "aws_ec2_instance_id" != null.
Number of assets per vulnerabilities chunk made fixed: 200
Added some checks to avoid null exceptions in policy
Tested in SaaSQA:
> Fixed tenable collector and policy

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/encryption/CMKEncryptionRule.java
**@policyId:GCP_cloud_sql_encryption_cmks_rule** job failed due to missing attribute of **kmsKeyName** for resourceId
**"central-run-349616:us-east1:test-mysql-with-network"**. So if ksmKeyName is absent we should handle policy as if kmsKeyName is NULL.
**Positive Case**: Keep ksmKeyName in Mapper json file in Junit file and check the policy is getting executed successfully
****Negative Test case:**** Absence of kmsKeyName. It is expected policy should execute without any NULL pointer exception with negative result.
> fix:[PLG-371]KmsKeyName issue for Failing Policy

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/vminstance/VMInstanceWithPublicAccess.java
@PolicyID **GCP_Virtual_Machine_public_access_version** got failed to execute to incorrect mapper attribute as well as null pointer exception at policy side
Mapper side also attribute fix addressed as part of https://github.com/PaladinCloud/Plugins/pull/85/files.
Besides this also needs to be addressed at Policy side as well which exactly getting done as part of this PR
**Mock the Junit Test case with CQ/Mapper data**
**Test Case with NatIp being NULL**
Execution results
Checklist:
> fix:[PLG-366]NatIp Null Pointer fix for PolicyExecution

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/Disks/DeleteUnusedVMDisk.java
@PolicyID **"delete_unused_vm_disk"** got failed due to "users" attribute being NULL for resource ID "1316521205842241414". Policy should handle this scenario as if users are empty which is already handled by policy engine.
We are changing the policy engine to execute this scenario as if users are empty.
**Mock the Test file using CQ/Mapper Data**
**Negative Test scenario:**
Mock the test data using  **Mapper/CQ** generated data where users attribute is just NULL and try to execute the policy to make sure that NULL pointer exception is not being thrown.
Expected behaviour
1) Null pointer exception should not get thrown
2) Policy should throw violation because because users are not attached
****Positive Test Case**
Mock the test …
> fix:[PLG-369]UsersNull fix for "delete_unused_vm_disk" Policy Engine

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/APIKeys/ConfigureApiRestriction.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/APIKeys/EnableAPIApplicationRestriction.java
Enable_API_Key_Application_Restrictions,Enable_API_Key_Restrictions policies got failed due to absence of **"restrictions"** attribute.Handled null case in a such as way if attribute is not present this means there is not restrictions with respect to API Keys. So returning default true in those cases
-
Tested by mocking the data at  Junit test file and executing the policy using mocked data. This mocked data is nothing but CQ/Mapper data. **No NULL pointer exception is getting thrown after recent fix**
Recent Test execution
> fix:[PLG-358]API Keys- NULL Handling in Policy execution

- installer/resources/batch/job.py
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/file/ErrorManageUtil.java
- Regional endpoint credentials are needed for reading the data from non-default regions. Currently, we are using temporary credentials from the global STS endpoint which are by default valid only in default AWS regions. Because of this, we are unable to read any data from non-default AWS regions (e.g. af-south-1).
- Added an env variable to force SDK to use regional STS endpoints. By default regional endpoint tokens are valid across all the regions.
- Also, omitted the errors coming from disabled regions from raising alerts. As they we can ignore them.
- Printing all the remaining errors at the end of the log file for easy access.
list any relevant details for your test …
> fix: [CORE-1303] Using regional endpoints for STS

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/cloudstorage/CloudStorageWithPublicAccessRule.java
**@policyId:Cloud_Storage_should_not_be_public failure**  got failed due to users attribute being NULL. Earlier this was failing due to missing attribute. Now though this users attribute present it got failed users being NULL. So handled additional condition to make sure policy does not throw NULL pointer exception at any cost.
**Step 1: Mock the **CloudStorageWithPublicAccessRuleTest** Junit Test case file with CQ/Mapper data with **users being NULL****
Step 2: Execute Junit Test file /Method
> fix:[PLG-374]NullPointer exception fix

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/VMsWithSeverityVulnerabilityRule.java
-Changed the cve url in Vulnerability Information for tenable to nvd.nist.gov. This change is not dependent on anything
This fixes the  cve url in Vulnerability Information for tenable 
> fix:[CORE-1679] Updated the cve url for tenable vulnerabilty info

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/util/AssetGroupUtil.java
- jobs/pacman-rule-engine-2.0/src/main/java/com/tmobile/pacman/commons/autofix/manager/IAutofixManger.java
Trend graph in compliance overview screen is not showing up data for category graph. 
Recently /overallcompliance api is updated to improve performance and response time of api.
'overall' attribute is removed from response of the above api because overall compliance percent is not used when this api is directly invoked. But data shipper invokes this api and saves all 5 attributes tagging, cost, operations, security, overall to assetgroup_stats index. This index is queried to plot category graph in compliance overview screen using 'overall' value.
In this commit, overall compliance percent is calculated in data shipper …
> fix:[CORE-1678] trend graph in compliance overview screen is not showing data for category graph.

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/TenableAccountServiceImpl.java
Tenable provided API which suits for checking API keys without hacks.
`/session`
Successful validation:
Failed validation:
> feat:[PLG-356] Changing validation URL to /session

- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/AssetGroupManager.java
Renamed all-resources to all-sources
SQL query updated for all-sources
New SQL query genearated for redhat
`SELECT DISTINCT
agd.groupId, agd.groupName, agd.groupType, agd.aliasQuery
FROM
cf_AssetGroupDetails AS agd
WHERE
(agd.groupId NOT IN (SELECT DISTINCT
agcd.groupId
FROM
cf_AssetGroupCriteriaDetails AS agcd
WHERE
agcd.attributeName = 'CloudType')
AND agd.groupType <> 'user'
AND agd.groupType <> 'System'
AND agd.groupName <> 'all-sources'
AND aliasQuery LIKE '%_*%')
OR (agd.groupType = 'user')
OR (agd.groupName = 'redhat'
AND agd.groupType = 'System')
OR (agd.groupName = 'all-sources')
OR (agd.groupType <> 'user'
AND agd.groupType <> 'System'
AND agd.groupName <> 'all-sources'
AND aliasQuery LIKE '%redhat_*%')`
List any …
> feat:[PLG-360] SQL query updated for all-sources

- installer/resources/pacbot_app/files/DB.sql
As we changing the target nam, we need to make changes to the aliasQuery in cf_AssetGroupDetails table.
- renamed indices in cf_AssetGroupDetails.aliasQuery for azure_kubernetes and gcp_gkecluster
Fixes the index name in cf_AssetGroupDetails.aliasQuery
> fix:[CORE-1647] Updated aliasQuery in cf_AssetGroupDetails

- installer/resources/pacbot_app/files/DB_Policy.sql
- Issue is because the esSgRulesUrl in policyParams table is still pointing to old ES index even after reindexing gcp_gkecluster as per CORE-1647
- Fixed the esSgRulesUrl to point to the new index gcp_gke
esSgRulesUrl in policyParams table
> fix:[CORE-1723] Update ES url to new index as per core-1647

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/ComplianceServiceImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/Constants.java
- The issue is beacause for 'Enable Qualys EC2 Vulnerability Scan policy' only running ec2 assets are considered but for ‘Qualys Found S3/S4/S5 Vulnerabilities on EC2 Instance’ policies all ec2 assets are consider(both running and stopped) and thats the reason we see different asset count for these qualys policies.
- Fixed it by considering only running ec2 assets for all qualys policies.
Fixes the Assets scanned count for policy summary
> fix:[CORE-1535] Include only running ec2 assets for qualys policies

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AbstractAccountServiceImpl.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AssetGroupService.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AssetGroupServiceImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/Constants.java
Tried to add redhat in new saasdev env
it was the first time for a plugin of type redhat
data collector and shipper ran successfully
https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/saasdev%2Fjobs/log-events/saasdev%2Fdefault%2Fbda8e156ba0c4eac8775238e8db74be2
asset group added
plugin added and counts populated
redhat data available in all-sources
Now deleting redhat plugin
---------
asset group removed
plugin removed
data removed from all-sources
Now adding redhat again to see if data is available in …
> feat:[PLG-362] Deletion of a plugin should be self contained

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/gcprules/vminstance/IPFowardingRule.java
"tags" attribute may or may not have "goog-gke-node" member for gcp virtual machine
1. Run "IP_forwarding_for_Instances" policy
2. The below error should not occur
> fix:[CORE-1701] tags value fix

- webapp/src/app/pacman-features/modules/assets/asset-details/asset-details.component.ts
Bug: [Asset Details] The Red Hat Source logo is not loading.
https://paladincloud.atlassian.net/browse/UIUX-550
Fixes # (issue) 
The issue was caused by a white space in the image name. It has been resolved by removing the white space.
Bug: 
Fix:
> Fix:[UIUX-550] asset details red hat source logo is not getting loaded

- webapp/src/app/pacman-features/modules/assets/asset-details/asset-details.component.ts
Bug: [Asset Details] The Red Hat Source logo is not loading.
https://paladincloud.atlassian.net/browse/UIUX-550
Fixes # (issue) 
The issue was caused by a white space in the image name. It has been resolved by removing the white space.
Bug: 
Fix:
> Fix/UI ux 550/asset details red hat logo

- lambda-functions/notification-es-logging-service/src/main/java/com/paladincloud/notification_log/LogNotificationToOpenSearch.java
- lambda-functions/notification-es-logging-service/src/main/resources/log4j2.xml
- lambda-functions/notification-invoke-service/pom.xml
- lambda-functions/notification-invoke-service/src/main/java/com/paladincloud/SendNotification.java
- lambda-functions/notification-invoke-service/src/main/resources/log4j2.xml
- lambda-functions/notification-send-email-service/pom.xml
- lambda-functions/notification-send-email-service/src/main/java/com/paladincloud/InvokeNotificationsApi.java
- lambda-functions/notification-send-email-service/src/main/java/com/paladincloud/utils/HttpUtil.java
- lambda-functions/notification-send-email-service/src/main/resources/log4j2.xml
- lambda-functions/notification-template-formatter-service/pom.xml
- lambda-functions/notification-template-formatter-service/src/main/java/com/paladincloud/FetchNotificationSettings.java
- lambda-functions/notification-template-formatter-service/src/main/java/com/paladincloud/HttpUtil.java
- lambda-functions/notification-template-formatter-service/src/main/resources/log4j2.xml
- Issue was when notification lambdas log everything including request(which contains violation info that has "error" text in it), ops alert is generated
- Fixed it by making default log level to error in log4j2.xml config file
- the default log level can be overriden by setting an env variable LOG_LEVEL=<DEBUG/INFO/WARN/ERROR>, so that log level can be set to INFO only for dev env
- for all other envs except dev, we dont need to set the env variable, since ERROR will be the default level
ops alert for notification lambdas
List any documentation updates that …
> fix:[CORE-1702] Set default logger level to ERROR for notification lambdas

- webapp/src/app/pacman-features/modules/compliance/policy-details/policy-details.component.css
- webapp/src/app/pacman-features/modules/compliance/policy-details/policy-details.component.html
- webapp/src/app/pacman-features/modules/compliance/policy-details/policy-details.component.ts
1. Fixed the lengthy values overflowing out of the widget by adding ellipsis to both the key and value.
Before:
After:
Policy Param Widget in Policy Compliance
> style: added ellipses for values in policy param widget

- installer/resources/lambda_rule_engine/files/rule_engine_cloudwatch_aws_rules.json
Removed policy
Policy id aws_ec2_should_not_be_publicly_accessible_on_port3306
> chore:Removed Policy(ec2 shouldn't access 3306)

- installer/settings/common.py
- issue was that, LAMBDA_PATH wasn't updated after the lambda changes done in CORE-1702
- bumped the LAMBDA_PATH version
LAMBDA_PATH version
> fix:[CORE-1702] Update the lambda path

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/controller/AssetTrendController.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepositoryImpl.java
This feature is to enable api/asset/v1/trend/assetcount api to return number of assets date wise for each asset type also. Presently it is returning total assets of asset group only.
assettrendgraph
> fix:[CUS-239] asset trend graph for asset type in a asset group

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/AccountsRepository.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/AzureAccountRepository.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/CreateAssetGroupServiceImpl.java
- issue: policy count includes all cloud providers' policies
- root cause: when an asset group is created by accountId, aliases are added for all cloud types even if the accountId is not relevant to a cloud type. Due to this, based on alias, policies of all cloud types are fetched.
- solution: during assetgroup creation, when assetgroup criteria contains accountId, restrict alias creation to only the cloud type to which the accountId belongs to.
- Jira link: https://paladincloud.atlassian.net/browse/CORE-1282
Fixes policy count in asset group selector and policies screen
list any relevant details for your test …
> fix:[CORE-1282] Fix incorrect policy count in asset group selector

- webapp/src/app/shared/services/utils.service.ts
UI has a logic which splits the filter key-value string based on '=' operator.
In this fix, We are trying to encode the filter values and decode them so that they are not split based on '='.
Test results:
Now, the filter values containing '=' operator will work as expected
> fix:[CORE-1816]fixed filters not working when value contains = operator

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/InventoryConstants.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/PolicyDefinitionInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/SecurityPricingsInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/SubscriptionInventoryCollector.java
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/InventoryConstants.java
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/file/FileManager.java
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/util/InventoryUtil.java
- issue: for global assets in aws and azure, the region is populated as null, due to which the region column shows 'No Data' in both assets and violation screen
- root cause: since these assets are global and not specific to a region, we don't get a region for them during collection
- the global asset types are aws_checks(Trusted Advisor Checks), aws_iamrole,aws_iamuser, aws_iampolicies, aws_iamgroup, aws_iamcertificate, aws_account, aws_cloudfront, aws_phd, azure_policydefinitions, azure_securitypricings, azure_subscription
- solution: added region as 'global' for these asset types during collection
- needs plugin change for gcp
The region for global assets which shows 'No data'
Please describe the tests that you ran to verify …
> fix:[CORE-1728] Region for global assets must be 'global' instead of 'No Data'

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/domain/AuditTrailDTO.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/Constants.java
- We want to display the exemption reason and exemption expiry date on violation details screen
- for this, we are adding the exemption reason and exemption expiry date in the /v1/issueauditlog API, so that it can be displayed on UI
- technical detail: on adding an exception, saved the exemption reason and expiry date in the audit logs, so that it can be retrieved along with the audit log that performed it
Adds exemption detail to audit log in /v1/issueauditlog API
> fix:[CORE-1262] Violation audit logs API must contain exemption info

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/misc/CheckAWSConfigEnabled.java
- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/constants/PacmanRuleConstants.java
- for all the assetTypes which are not region specific, we added "global" as the default region
- issue: aws sdk client doesn't have an enum "global" expected when creating the client, so it fails
- fix: for assetType account, the default region was given as "us-east-1" which comes from cf_PolicyParams. Since, "global" was used as alternative for UI, we are fixing this by setting the default region if the region of the account is null/global
aws sdk client doesn't have an enum "global" expected when creating the client
setting the default region from cf_PolicyParams if the region of the account is null/global
policy "Enable AWS Config service"
Please describe the tests that you ran to verify your changes. Provide instructions so we can …
> fix:[CORE-1879] create default region as us-east-1 for sdk client in policy rule

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/controller/AssetTrendController.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepository.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepositoryImpl.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetService.java
- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/service/AssetServiceImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/Constants.java
1.  If user provides 'totalassets' along with other asset types in the payload of api /trend/assetcount (trend graph api), then api should return total assets and assets for each provided asset type in the response. Earlier, api used to return data either for totalassets or individual asset types. Now with these changes, api will simultaneously return both as shown in the below image.
List …
> fix:[CORE-1860] update /trend/assetcount api to return asset count of all assets and individual asset types together

- api/pacman-api-asset/src/main/java/com/tmobile/pacman/api/asset/repository/AssetRepositoryImpl.java
There is some state data in recently viewed asset groups data for some tenants. That happened due to a bug while delivering the Red Hat plugin. Though we fixed that bug, some tenants have the data populated in the recently viewed asset groups table.
The stale data is causing issues when the plugin is unavailable in the system. Added a check in the API to avoid the issue.
Tested the API locally and it is not throwing any errors.
> fix:[CORE-1843] Added isVisible check

- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/AzureDiscoveryApplication.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/PolicyDefinitionInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/collector/PolicyStatesInventoryCollector.java
- jobs/azure-discovery/src/main/java/com/tmobile/pacbot/azure/inventory/file/AssetDataFactory.java
- using @EnableCaching needs the class to be proxied through interface
- so, autowired the class that uses caching through interface so its correctly proxied
- added missing config for cache manager
spring is not able to proxy the class autowired through impl
autowired by interface
> fix:[CORE-1881] EnableCaching needs proxying through interface

- installer/resources/pacbot_app/files/DB.sql
- different cloud providers have assetTypes that have similar name and those are displayed on UI with (cloudtType) as suffix.
- we are removing the cloudType suffix for the assetTypes with same names, so that the assets of multiple cloud sources can be selected with a common display name.
different cloud providers have assetTypes that have similar name and those are displayed on UI with (cloudtType) as suffix
- remove the suffixed cloud provider name for the colliding asset names in cf_Target table, so that they are displayed under single name in Ui
- rename the taegetTypeDisplayName in ES to remove the suffix(ES script attached in the ticket)
Please describe the tests that you ran to verify your changes. Provide instructions so we can …
> feat:[CORE-1653] Standardize asset display names which are same for different sources

- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/TargetTypesRepository.java
- api/pacman-api-admin/src/main/java/com/tmobile/pacman/api/admin/repository/service/AssetGroupServiceImpl.java
- commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/repo/ElasticSearchRepository.java
- Issue: when an asset group is created with a certain asset type and later the account doesn't have an asset of that asset type and the "Edit asset group" screen shows blank for that asset type
- cause: this is because the list of asset types are fetched from the ES data which only stores the assets that are currently active and hence when the asset is no longer in the account, it is not included in the list of asset types displayed on the asset group creation/edit screen
- fix: getting the list of asset types from cf_Target table which will always return all the asset types valid for cloud types irrespective of if the cloud account has an active asset
- get the valid assets only with status enabled or active
this is because the list of asset types are fetched from the ES data which only …
> fix:[CORE-1771] Get the target types from db for asset group creation screen

- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/file/FileManager.java
Because of the wrong filenames, AWS collector stopped collecting assets for Account and DMS.
Corrected the file names accordingly.
Ran the collector and can see the data appearing in S3 files.
> fix:[CUS-278] Corrected the filenames for account and dms target types

- installer/resources/pacbot_app/files/DB.sql
Asset Group screen showing the error for fresh installs. Due to an incorrect date values for AWS record post converting the column to timestamp.
Removed the default data value and inserted the current timestamp for the default AWS asset group.
Inserted a few sample asset group records into saasdev using `now()` function and was able to see records inserted using the proper timestamp value and the asset group screen is not broken in saasdev.
> fix:[CORE-1914] Corrected the time format for default asset group

- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/domain/AuditTrailDTO.java
- api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
- handled NPE for optional fields during Request/Deny exemption
- For Revoke request and Deny exemption, the reason and expiry date are null
NPE when optional fields are null
handled NPE checks
NPE
> fix:[CORE-1893] Add NPE check for optional fields in Request/Deny exemption

- webapp/src/app/shared/services/filter-management.service.ts
Earlier, We were showing duplicate options if exists and when a filter option was selected we were finding only the first occurrence of corresponding id (expecting one to one correspondence) but now, since we can have multiple id's pointing to same display name.. we are finding all the corresponding id's and also we showing only unique filter optons.
https://paladincloud.atlassian.net/browse/UIUX-572
https://github.com/PaladinCloud/EE/pull/1605
list any …
> fix:[UIUX-572]fixed bug related to duplicate filter options

- webapp/src/app/pacman-features/secondary-components/pacman-policy-violations/pacman-policy-violations.component.ts
- webapp/src/app/shared/services/filter-management.service.ts
- webapp/src/app/shared/table/table.component.css
- webapp/src/app/shared/table/table.component.html
- webapp/src/app/shared/table/table.component.ts
1. Fixed associated policies not refreshing in asset details.
2. Added loader in associated policies.
3. Added tooltip for column header in lists.
https://github.com/PaladinCloud/EE/pull/1611
https://github.com/PaladinCloud/EE/pull/1646
1. Verified associated policies refreshes correctly when clicked on related asset types.
> fix:[UIUX-580] fixed associated policies not refreshing in asset details

- webapp/src/app/pacman-features/modules/assets/asset-details/asset-details.component.css
- webapp/src/app/pacman-features/modules/assets/asset-details/asset-details.component.html
- webapp/src/app/pacman-features/modules/compliance/card/card.component.css
- webapp/src/app/pacman-features/modules/compliance/card/card.component.html
- webapp/src/app/pacman-features/modules/compliance/progress-bar-chart/progress-bar-chart.component.css
- webapp/src/app/shared/components/molecules/multi-tab-switcher/multi-tab-switcher.component.css
- webapp/src/app/shared/doughnut-chart/doughnut-chart.component.css
- webapp/src/app/shared/doughnut-chart/doughnut-chart.component.ts
https://paladincloud.atlassian.net/browse/UIUX-592
When we can fit in the same number of digits for Critical severity, we should show the full number for High too.
https://github.com/PaladinCloud/CE/assets/152586069/ebc11eeb-ffc6-44f1-8769-a47df116f933
- Resolving issue with label display for long numbers on the chart.
- Adjusting the starting angle of the donut chart to commence from 0 degrees for improved visualisation.
- Enhancing alignment for all utilised donut charts.
- Improving UI design for multi-tab switching.
> fix:[UIUX-592] doughnut chart ui fix

- installer/resources/pacbot_app/files/DB.sql
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/EntityManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/ExternalPolicies.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/entity/ViolationAssociationManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/error/ErrorManager.java
- jobs/pacman-data-shipper/src/main/java/com/tmobile/cso/pacman/datashipper/es/ESManager.java
Condition for CQ GCP case breaks data shipping for Wiz GCP data by setting `aacountname` to `null` because with Wiz we don't have all customer accounts and those data fields (such as `accountid` and `accountname`) are set in mapper.
Added condition to the shipper so when account name is set - it's not get set again from the DB (crucial for Wiz).
Meanwhile updating all GCP mapping files in this [PLG PR 155](https://github.com/PaladinCloud/Plugins/pull/155) so they won't have '-' as a project name.
Did run shipper with changes - all project IDs where loaded properly for GCP (via regular CQ collection).
> fix:[PLG-440] Fix shipper for CQ GCP and Wiz case

- installer/resources/pacbot_app/files/DB.sql
During Testing at SAASDEV it has been identified, asset type incorrectly displays as "Dast Assets" instead of environment  and also ES url is wrong at DB. So corrected both the bugs identified as part of this PR
Incorrect AssetType for Checkmarx
Make changes to AssetType
DB Change
-
Tested at SAASDEV after making changing db changes. Before fix below graph had Dast Assets, after fix it changed to Environment
**Dast Assets================>Environment**
> fix:[PLG-411]Bugfixes-CheckMarxAssetType Display fix

- jobs/azure-discovery/pom.xml
- jobs/gcp-discovery/pom.xml
- jobs/pacman-aqua-enricher/pom.xml
- jobs/pacman-awsrules/pom.xml
- jobs/pacman-cloud-discovery/pom.xml
- jobs/pacman-cloud-notifications/pom.xml
- jobs/pacman-data-shipper/pom.xml
- jobs/pacman-qualys-enricher/pom.xml
- jobs/pacman-rule-engine-2.0/pom.xml
- jobs/pacman-tenable-enricher/pom.xml
- jobs/recommendation-enricher/pom.xml
Removing the provided scope as the batch-commons are not available at the container. We need to include these classes in the JAR.
Build AWS collector locally and could see batch commons being included in the final JAR.
> fix: Removing the provided scope for commons so that they are included in the final jar

- jobs/job-scheduler/pom.xml
- After major refactoring done in https://github.com/PaladinCloud/CE/pull/2123 for reducing the jar file size, few dependencies were missed out which caused issues in running job scheduler
- fix: added the missing dependencies
dependencies missing after maven pom refactor
added the missing dependencies
dependency issue
> fix:[CORE-1968] Fix failing job scheduler due to missing dependencies

- installer/resources/pacbot_app/files/DB.sql
- Issue: creating asset group fails due to cf_AssetGroupDetails table createdUser and modifiedUser column length(75) and actual userName from cognito exceeds 75 chars
- increased the column length to 200
actual userName from cognito exceeds 75 chars and table column length is only 75 chars
increased the column length to 200
column length of createdUser and modifiedUser column in cf_AssetGroupDetails
> fix:[CORE-1962] Increase created and modified user column length for AssetGroupDetails

- installer/resources/pacbot_app/files/DB.sql
For Checkmarx Scheduler is not triggering CollectorBatch Job
We need to add checkmarx as entry in pac_config_properties table for any plugin to be considered as part of scheduler Job
Added checkmarx in pac_config_properties  
DB Changes
1)Ran the Scheduler job locally after updating values at SAASDEV db 
2) Checked at SAASDEV whether Scheduler service is triggering Collector job for Checkmarx
> fix:[PLG-410]Scheduler Bug fix for Checkmarx-Config Changes

- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/util/InventoryUtil.java
- issue: the issue is in the way we collect and describe snapshots in the collector. The collector seems to skip collecting if its not able to find and describe a snapshot id that it had listed
- in this case, the snapshot could not be found using snapshotID
- fix: handle exception during describing individual snapshots, so that it doesn't stop describing other listed snapshots
- handled the case when snapshot could not be found using snapshotID
collector skips collecting snapshot if there is an issue describing a single snapshot
handle exception for individual snapshots
> fix:[CUS-286] Fix dips in collected snapshot assets for vertex

- jobs/job-scheduler/src/main/java/com/paladincloud/jobscheduler/service/JobScheduler.java
[CORE-2024]
Our config url is not  able to fetch “application” properties
CONFIG_URL=[https://saasqa.paladincloud.io/api/config/application,batch,inventory,job-scheduler/prd/latest](https://saasqa.paladincloud.io/api/config/batch,inventory,job-scheduler/prd/latest)
during the release of v1.90, we changed the type of application to “application” from “job-scheduler” for aws.enabled, azure.enabled, etc
we made the because, it was necessary to make it available to api-services
[CORE-2024]: https://paladincloud.atlassian.net/browse/CORE-2024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …
> fix:[CORE-2024] scheduler fix

- webapp/src/app/pacman-features/modules/compliance/issue-details/issue-details.component.css
https://paladincloud.atlassian.net/browse/UIUX-688
UI padding overlaps with the container when the value string is long.
Bug: 
Fix: 
> fix:[UIUX-688] violations details content overlapping border

- webapp/src/app/pacman-features/modules/compliance/issue-details/issue-details.component.css
- webapp/src/app/post-login-app/asset-groups/asset-groups.component.html
https://paladincloud.atlassian.net/browse/UIUX-685
The Asset Group Selector category text is in lowercase; it should be capitalized.
Added a CSS class to handle label capitalization.
> fix:[UIUX-685] selector label text lowercase

- webapp/src/app/shared/multiline-zoom-graph/multiline-zoom-graph.component.ts
https://paladincloud.atlassian.net/browse/UIUX-693
Asset Trend graph showing negative yAxis value.
> fix:[UIUX-693] asset trend graph min round off value fix

- jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/AssetTypeGroupedVulnerabilitiesRule.java
- jobs/pacman-awsrules/src/test/java/com/tmobile/cloud/awsrules/ec2/AssetTypeGroupedVulnerabilitiesRuleTest.java
The Rapid7 'medium' severity policy was showing as having failed when it was empty (there were no associated CVE's). This filters empty CVE's out which results in the 'medium' policy as succeeding.
PLG-534
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the style guidelines of this project
- [x ] My commit message/PR follows the contribution guidelines of this project
- [x ] I have performed a self-review of my code
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
> Filter out polices with no matching violations

- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/file/FileManager.java
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/util/InventoryUtil.java
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/vo/ClassicELBVH.java
- jobs/pacman-cloud-discovery/src/main/java/com/tmobile/cso/pacman/inventory/vo/LoadBalancerVH.java
[CUS-305] Added accesslogbucketprefix attribute for app/classic ELB
[CUS-305]: https://paladincloud.atlassian.net/browse/CUS-305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CUS-305] Added accesslogbucketprefix attribute for app/classic ELB
